####################################################
#                                                  #
#                 HOME ASSISTANT                   #
#                                                  #
####################################################
# https://home-assistant.io/docs/configuration/basic/

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 34
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include customize.yaml
  # Package folder
  packages: !include_dir_named packages

####################################################
#                                                  #
#                     GENERAL                      #
#                                                  #
####################################################

# https://www.home-assistant.io/components/system_health/
system_health:

#---------------------------------------------------
# Show links to resources in log and frontend
#introduction:

#---------------------------------------------------
# Enables the frontend
# Add javascript_version: latest to see if it solve the current problem
frontend:
  javascript_version: latest

#---------------------------------------------------
# Enables configuration UI
# https://home-assistant.io/components/config/
config:

#---------------------------------------------------
# http
# https://home-assistant.io/components/http/
http:
#  api_password: !secret http_password
  ip_ban_enabled: True
  login_attempts_threshold: 3

#---------------------------------------------------
# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

#---------------------------------------------------
# Discover some devices automatically
discovery:

#---------------------------------------------------
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

#---------------------------------------------------
# Enables a map showing the location of tracked devices
#map:

#---------------------------------------------------
# Track the sun
# https://home-assistant.io/components/sun/
sun:

#---------------------------------------------------
# Notifier
#https://home-assistant.io/components/notify.pushetta/
notify:
  name: pushbullet
  platform: pushbullet
  api_key: !secret pushbullet_api_key

#  name: pushetta
#  platform: pushetta
#  channel_name: !secret pushetta_channel_name
#  api_key: !secret pushetta_api_key

####################################################
#                                                  #
#                      LOGGING                     #
#                                                  #
####################################################
recorder: !include logging/recorder.yaml
history: !include logging/history.yaml
logbook: !include logging/logbook.yaml
logger: !include logging/logger.yaml

####################################################
#                                                  #
#      LINKS TO INDIVUAL CONFIGURATION FILES       #
#                                                  #
####################################################

# https://home-assistant.io/docs/configuration/splitting_configuration/

#---------------------------------------------------
automation: !include_dir_merge_list automations/
#---------------------------------------------------
device_tracker: !include device_trackers.yaml
#---------------------------------------------------
sensor: !include_dir_merge_list sensor
#---------------------------------------------------
group: !include_dir_merge_named group
#---------------------------------------------------
script: !include_dir_merge_named script
#---------------------------------------------------

####################################################
#                                                  #
#                    TELLSTICK                     #
#                                                  #
####################################################
tellstick:
  signal_repetitions: 3

####################################################
#                                                  #
#                     COVER                        #
#                                                  #
####################################################
cover:
  - platform: tellstick

####################################################
#                                                  #
#                     LIGHT                        #
#                                                  #
####################################################
light:
  - platform: tellstick

#  - platform: switch
#    name: Louise fönster
#    entity_id: switch.louise_fonster
  - platform: switch
    name: Andreas fönster
    entity_id: switch.andreas_fonster
  - platform: switch
    name: Friggebod lilla fönstret
    entity_id: switch.friggebod_lilla_fonstret
  - platform: switch
    name: Friggebod stora fönstret
    entity_id: switch.friggebod_fonster
  - platform: switch
    name: Friggebod ute
    entity_id: switch.friggebod_ute
  - platform: switch
    name: Hall skåp
    entity_id: switch.hall_skap
  - platform: switch
    name: Kök lilla fönstret
    entity_id: switch.kok_lilla_fonstret
#  - platform: switch
#    name: Kök stora fönstret
#    entity_id: switch.kok_stora_fonstret
  - platform: switch
    name: Sovrum fönster
    entity_id: switch.sovrum_fonster
#  - platform: switch
#    name: Uterum fönster
#    entity_id: switch.uterum_fonster
  - platform: switch
    name: Uterum fotogenlampa
    entity_id: switch.uterum_fotogenlampa
  - platform: switch
    name: Uterum led
    entity_id: switch.uterum_led
  - platform: switch
    name: Vardagsrum vitrinskåp
    entity_id: switch.vardagsrum_vitrinskap
  - platform: switch
    name: Vardagsrum gran
    entity_id: switch.vardagsrum_gran
  - platform: switch
    name: Discolampa
    entity_id: switch.discolampa

####################################################
#                                                  #
#                     SWITCH                       #
#                                                  #
####################################################
switch:
  - platform: tellstick

####################################################
#                                                  #
#                TEXT TO SPEECH                    #
#                                                  #
####################################################
#tts:
#  - platform: google_translate

####################################################
#                                                  #
#                  MEDIA PLAYER                    #
#                                                  #
####################################################
media_player:
  - platform: squeezebox
    host: 192.168.1.13
    port: 9090

  - platform: yamaha
    host: 192.168.1.242

####################################################
#                                                  #
#                    CLOUD                         #
#                                                  #
####################################################
#cloud:

####################################################
#                                                  #
#                 EMULATED HUE                     #
#                                                  #
####################################################
#emulated_hue:

####################################################
#                                                  #
#                 EMULATED HUE                     #
#                                                  #
####################################################
#emulated_roku:
#  host_ip: 192.168.1.14 # should be set to Home Assistant's address
##  advertise_ip: 10.0.0.10 # optional, defaults to host_ip if not specified
##  upnp_bind_multicast: True # optional, defaults to True
#  listen_ports:
#    - 8060
#emulated_roku:
#  servers:
#    - name: Home Assistant
#      listen_port: 8060

####################################################
#                                                  #
#                      OPEN UV                     #
#                                                  #
####################################################
#openuv:
#  api_key: !secret open_uv_api_key

####################################################
#                                                  #
#                  PYTHON_SCRIPT                   #
#                                                  #
####################################################
# https://www.home-assistant.io/components/python_script/
python_script:

####################################################
#                                                  #
#                     WORKDAY                      #
#                                                  #
####################################################
binary_sensor:
  - platform: workday
    country: SE
    name: workday_today

  - platform: workday
    country: SE
    name: workday_tomorrow
    days_offset: 1

#  - platform: template
#    sensors:
#      workday_light:
#        value_template: '{% if is_state("binary_sensor.workday_today", "on") and is_state("binary_sensor.workday_tomorrow", "on") %}on{% else %}on{% endif %}'

####################################################
#                                                  #
#                     INPUT_BOOLEAN                #
#                                                  #
####################################################
input_boolean:
  christmas_light:
    name: Använd julbelysning
    initial: off
    icon: mdi:pine-tree

  rorelsevakt_aktiv:
    name: Rörelsevakt aktiv
    initial: off

####################################################
#                                                  #
#                     INPUT_SELECT                 #
#                                                  #
####################################################
input_select:
  inside_lights:
    name: Innebelysning
    options:
     - Off
     - Morgonbelysning
     - Förmiddagsbelysning
     - Kvällsbelysning
     - Nattbelysning
     - Bortabelysning
#    initial: Off
    icon: mdi:lightbulb

  kitchen_lights:
    name: Köksbelysning
    options:
     - Off
     - 25%
     - 100%
#    initial: Off
    icon: mdi:lightbulb

  uterum_led_lights:
    name: Uterum ledbelysning
    options:
     - Off
     - On
#    initial: Off
    icon: mdi:lightbulb

  outside_lights:
    name: Utebelysning
    options:
     - Off
     - On
#    initial: Off
    icon: mdi:lightbulb

####################################################
#                                                  #
#                     INPUT_NUMBER                 #
#                                                  #
####################################################
# input_number:
  # facade_light_on:
    # name: Fasad belysning on
    # initial: 40
    # min: 1
    # max: 100
    # step: 1
    # mode: box
  # facade_light_off:
    # name: Fasad belysning off
    # initial: 60
    # min: 1
    # max: 100
    # step: 1
    # mode: box

####################################################
#                                                  #
#                       ASUSWRT                    #
#                                                  #
####################################################
asuswrt:
    host: 192.168.1.1
    username: admin
    ssh_key: /home/homeassistant/.ssh/id_rsa
    sensors:
    - upload
    - download
    - upload_speed
    - download_speed

####################################################
#                                                  #
#                       MQTT                       #
#                                                  #
####################################################
# Add broker used on Raspberry Pi 3B used for lux values
# https://www.home-assistant.io/docs/mqtt/broker/
mqtt:
  broker: 192.168.1.17
  port: 1883

####################################################
#                                                  #
#                  VOLVO ON CALL                   #
#                                                  #
####################################################
# https://www.home-assistant.io/integrations/volvooncall/
volvooncall:
  username: !secret voc_username
  password: !secret voc_password

####################################################
#                                                  #
#                       CAMERA                     #
#                                                  #
####################################################

camera:
#  - platform: generic
#    name: camera 1
#    still_image_url: !secret Camera_URL
#    stream_source: !secret Camera_1_Source

  - platform: generic
    name: camera 2
    still_image_url: !secret Camera_URL
    stream_source: !secret Camera_2_Source

# Enable stream
stream:
 
####################################################
#                                                  #
#            END OF CONFIGURATION FILE             #
#                                                  #
####################################################
