default_config:

####################################################
#                                                  #
#                 HOME ASSISTANT                   #
#                                                  #
####################################################
# https://home-assistant.io/docs/configuration/basic/

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 34
  # Country in which Home Assistant is running
  country: SE
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include customize.yaml
  # Package folder
  packages: !include_dir_named packages

  media_dirs:
    local: /media
    
  allowlist_external_dirs:
    - /config
    - /media
        
####################################################
#                                                  #
#                     GENERAL                      #
#                                                  #
####################################################
api:

# https://www.home-assistant.io/components/system_health/
system_health:

#---------------------------------------------------
# Show links to resources in log and frontend
#introduction:

#---------------------------------------------------
# Enables the frontend
frontend:

#---------------------------------------------------
# Enables configuration UI
# https://home-assistant.io/components/config/
config:

#---------------------------------------------------
# http
http:

#---------------------------------------------------
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

#---------------------------------------------------
# Track the sun
sun:

####################################################
#                                                  #
#                      LOGGING                     #
#                                                  #
####################################################
recorder: !include logging/recorder.yaml
logbook: !include logging/logbook.yaml
logger: !include logging/logger.yaml

###################################################
#                                                 #
#                     lovelace                    #
#                                                 #
###################################################
# https://www.home-assistant.io/lovelace/yaml-mode/
lovelace:
  mode: storage
#  mode: yaml

  # Add more dashboards
  dashboards:
    # Standard
    lovelace-standard:
      mode: yaml
      title: Standard
      show_in_sidebar: true
      filename: ui-lovelace.yaml

    # Kamera
    lovelace-camera:
      mode: yaml
      title: Kamera
      show_in_sidebar: true
      filename: ui-camera.yaml

    # Automation
    lovelace-automation:
      mode: yaml
      title: Automation
      show_in_sidebar: true
      filename: ui-automation.yaml

    # Ventilaton
    lovelace-ventilation:
      mode: yaml
      title: Ventilation
      show_in_sidebar: true
      filename: ui-ventilation.yaml


    # Generated
    lovelace-generated: # Needs to contain a hyphen (-)
      mode: yaml
      filename: notexist.yaml
      title: Generated
      icon: mdi:tools
      show_in_sidebar: false
      require_admin: true

####################################################
#                                                  #
#      LINKS TO INDIVUAL CONFIGURATION FILES       #
#                                                  #
####################################################

# https://home-assistant.io/docs/configuration/splitting_configuration/

#---------------------------------------------------
automation: !include_dir_merge_list automations/
#---------------------------------------------------
# device_tracker: !include device_trackers.yaml
#---------------------------------------------------
sensor: !include_dir_merge_list sensor
#---------------------------------------------------
group: !include_dir_merge_named group
#---------------------------------------------------
script: !include_dir_merge_named script
#---------------------------------------------------

####################################################
#                                                  #
#                  PYTHON_SCRIPT                   #
#                                                  #
####################################################
python_script:

####################################################
#                                                  #
#                     INPUT_NUMBER                 #
#                                                  #
####################################################
# input_number:
  # facade_light_on:
    # name: Fasad belysning on
    # initial: 40
    # min: 1
    # max: 100
    # step: 1
    # mode: box
  # facade_light_off:
    # name: Fasad belysning off
    # initial: 60
    # min: 1
    # max: 100
    # step: 1
    # mode: box

####################################################
#                                                  #
#                       ASUSWRT                    #
#                                                  #
####################################################
#asuswrt:
#    host: 192.168.1.1
#    username: admin
#    password: !secret asuswrt_password
##    ssh_key: /config/ssh/asuswrt
##    sensors:
##    - upload
##    - download
##    - upload_speed
##    - download_speed

####################################################
#                                                  #
#                       MQTT                       #
#                                                  #
####################################################
# MQTT configuration moved to packages/integrations/mqtt.yaml
# https://www.home-assistant.io/docs/mqtt/broker/

####################################################
#                                                  #
#                  VOLVO ON CALL                   #
#                                                  #
####################################################
# https://www.home-assistant.io/integrations/volvooncall/
#volvooncall:
#  username: !secret voc_username
#  password: !secret voc_password

####################################################
#                                                  #
#                   COMMAND LINE                   #
#                                                  #
####################################################
command_line:
  - sensor:
        name: Acpitz 0 Temperature
        command: "cat /sys/class/thermal/thermal_zone0/temp"
        # If errors occur, remove degree symbol below
        unit_of_measurement: "°C"
        value_template: '{{ value | multiply(0.001) | round(1) | int(85) }}'

  - sensor:
        name: Acpitz 1 Temperature
        command: "cat /sys/class/thermal/thermal_zone1/temp"
        # If errors occur, remove degree symbol below
        unit_of_measurement: "°C"
        value_template: '{{ value | multiply(0.001) | round(1) | int(85) }}'

  - sensor:
        name: CPU Temperature
        command: "cat /sys/class/thermal/thermal_zone2/temp"
        # If errors occur, remove degree symbol below
        unit_of_measurement: "°C"
        value_template: '{{ value | multiply(0.001) | round(1) | int(85) }}'

####################################################
#                                                  #
#            END OF CONFIGURATION FILE             #
#                                                  #
####################################################
