title: Hagaholm
views:
  - path: automation
    title: Automation
    badges: []
    cards:
      - type: entities
        entities:
          - automation.ny_enhet_hittad
          - automation.hassbian_uppdatering
        title: Hassbian
        show_header_toggle: true
        state_color: true
      - type: entities
        entities:
          - automation.hassbian_startad
          - automation.hassbian_stoppad
          - automation.restart_ha
        title: Hassbian off
        show_header_toggle: true
        state_color: true
      - type: entities
        entities:
          - automation.ringklocka_tvattstuga_dag
          - automation.ringklocka_tvattstuga_natt
          - automation.ringklocka_tvattstuga_borta
          - automation.ringklocka_hall_dag
          - automation.ringklocka_hall_natt
          - automation.ringklocka_hall_borta
          - automation.blinka_med_lyset_nar_ringklocka_ringer
          - automation.ringklocka_off_borta
          - automation.ringklocka_on_hemma
        title: Ringklocka
        show_header_toggle: true
        state_color: true
      - type: entities
        entities:
          - automation.ringklocka_tand_allt_lyse_1
          - automation.ringklocka_tand_allt_lyse_2
        title: Ringklocka off
        show_header_toggle: true
        state_color: true
      - type: entities
        entities:
          - automation.starta_luftavfuktare
          - automation.stoppa_luftavfuktare
        title: Garage luftavfuktare
        show_header_toggle: true
        state_color: true
      - type: entities
        entities:
          - automation.starta_elvarme_5_grader
          - automation.stoppa_elvarme_7_grader
          - automation.starta_elvarme_8_grader
          - automation.stoppa_elvarme_10_grader
        title: Garage elvärme
        show_header_toggle: true
        state_color: true
      - type: entities
        entities:
          - automation.apple_tv_i_forrad_startad
          - automation.apple_tv_i_forrad_stoppad
        title: Garage Zwift
        show_header_toggle: true
        state_color: true
      - type: entities
        entities:
          - automation.dagligen_mandag
          - automation.dagligen_onsdag
          - automation.dagligen_fredag
          - automation.dammsugaren_har_problem
        title: Dammsugare off
        show_header_toggle: true
        state_color: true
    icon: 'mdi:home-automation'
  - path: alarm
    title: Larm
    badges: []
    cards:
      - type: entities
        entities:
          - automation.larm_rorelse_i_hallen
          - automation.larm_rorelse_i_louise_rum
        title: Larm
        show_header_toggle: true
        state_color: true
      - type: entities
        entities:
          - input_boolean.frys_reading_missing_alarm
          - input_boolean.kyl_reading_missing_alarm
          - input_boolean.badrum_reading_missing_alarm
          - input_boolean.tvattstuga_reading_missing_alarm
          - input_boolean.varmepump_reading_missing_alarm
          - input_boolean.vardagsrum_reading_missing_alarm
          - input_boolean.hall_reading_missing_alarm
          - input_boolean.forrad_reading_missing_alarm
          - input_boolean.garage_reading_missing_alarm
          - input_boolean.friggebod_reading_missing_alarm
          - input_boolean.ute_friggebod_reading_missing_alarm
          - automation.avlasning_saknas_frys
          - automation.avlasning_saknas_kyl
          - automation.avlasning_saknas_badrum
          - automation.avlasning_saknas_tvattstuga
          - automation.avlasning_saknas_varmepump
          - automation.avlasning_saknas_vardagsrum
          - automation.avlasning_saknas_hall
          - automation.avlasning_saknas_forrad
          - automation.avlasning_saknas_garage
          - automation.avlasning_saknas_friggebod
          - automation.avlasning_saknas_ute_friggebod
        title: Larm avläsningar saknas
        show_header_toggle: true
        state_color: true
      - type: entities
        entities:
          - automation.uterum_larm_hog_temp
          - automation.friggebod_larm_hog_temp
          - automation.larm_hog_temp_i_kyl
          - automation.larm_varning_hog_temp_i_frys
          - automation.larm_hog_temp_i_frys
          - automation.larm_lag_temp_i_frys
          - automation.hog_temp_raspberry
          - automation.lag_temp_ackumulatortank
          - automation.hog_temp_ackumulatortank
          - automation.lag_temp_franluft
          - automation.hog_temp_franluft
          - automation.hog_temp_tilluft
        title: Larm temperatur
        show_header_toggle: true
        state_color: true
      - type: entities
        entities:
          - automation.friggebod_larm_lag_temp
          - automation.friggebod_frysvakt
          - automation.larm_lag_temp_i_kyl
          - automation.lag_temp_tilluft
        title: Larm temperatur off
        show_header_toggle: true
        state_color: true
      - type: entities
        entities:
          - automation.ingen_kontakt_med_forrad_fasadbelysning
          - automation.ingen_kontakt_med_fotogenlampa_i_uterum
          - automation.ingen_kontakt_med_friggebod_brytare_vid_stora_fonstret
          - automation.ingen_kontakt_med_friggebod_fasadbelysning
          - automation.ingen_kontakt_med_garage_avfuktare
          - automation.ingen_kontakt_med_garage_elvarme
          - automation.ingen_kontakt_med_tvattstuga_fasadbelysning
          - automation.ingen_kontakt_med_uterum_fonster
          - automation.ingen_kontakt_med_vardagsrum_skank
          - automation.ingen_kontakt_med_vardagsrum_vagn
          - automation.kontakt_med_forrad_fasadbelysning
          - automation.kontakt_med_fotogenlampa_i_uterum
          - automation.kontakt_med_friggebod_brytare_vid_stora_fonstret
          - automation.kontakt_med_friggebod_fasadbelysning
          - automation.kontakt_med_garage_avfuktare
          - automation.kontakt_med_garage_elvarme
          - automation.kontakt_med_tvattstuga_fasadbelysning
          - automation.kontakt_med_uterum_fonster
          - automation.kontakt_med_vardagsrum_skank
          - automation.kontakt_med_vardagsrum_vagn
        title: IKEA
        show_header_toggle: true
        state_color: true
      - type: entities
        entities:
          - automation.raspberry_pi_b_1_wire_offline
          - automation.raspberry_pi_3b_hagaholm_offline
          - automation.raspberry_pi_3b_lux_offline
          - automation.raspberry_pi_3b_offline
          - automation.raspberry_pi_4b_hassbian_offline
        title: Larm Raspberry Pi offline off
        show_header_toggle: true
        state_color: true
  - path: lights
    title: Belysning
    badges: []
    cards:
      - type: entities
        entities:
          - automation.startar_timers_kok
          - automation.stanger_av_rorelsedetektor_kok_aktiv
          - automation.stanger_av_rorelsedetektor_kok_aktiv_for_nattbelysning
        title: Rörelsedetektor i kök
        show_header_toggle: true
        state_color: true
      - type: entities
        entities:
          - automation.kok_100_borta
          - automation.kok_100_hemma_av
          - automation.kok_100_hemma_pa
          - automation.kok_off_ingen_rorelse
          - automation.kok_off_borta
          - automation.kok_off_ljust
          - automation.kok_rorelsedetektor_reset
        title: Köksbelysning
        show_header_toggle: true
        state_color: true
      - type: entities
        entities:
          - automation.morgonbelysning_on
          - automation.morgonbelysning_off
        title: Morgonbelysning
        show_header_toggle: true
        state_color: true
      - type: entities
        entities:
          - automation.dagbelysning_on_morkt
          - automation.dagbelysning_on_hemma_pa
          - automation.dagbelysning_on_sovrumsfonster_on
          - automation.dagbelysning_off_ljust
          - automation.dagbelysning_off_borta
          - automation.dagbelysning_kvallsbelysning_sovrumsfonster_off
        title: Dagbelysning
        show_header_toggle: true
        state_color: true
      - type: entities
        entities:
          - automation.nattbelysning_on
          - automation.nattbelysning_off
        title: Nattbelysning
        show_header_toggle: true
        state_color: true
      - type: entities
        entities:
          - automation.bortabelysning_on_borta
          - automation.bortabelysning_on_morgon
          - automation.bortabelysning_on_morkt
          - automation.bortabelysning_off_kvall
          - automation.bortabelysning_off_ljust
        title: Bortabelysning
        show_header_toggle: true
        state_color: true
      - type: entities
        entities:
          - automation.uterums_belysning_on_18
          - automation.uterums_belysning_on_150
          - automation.uterums_belysning_on_home
          - automation.uterums_belysning_off_17
          - automation.uterums_belysning_off_all_off_hemma
          - automation.uterums_belysning_off_borta
        title: Uterumsbelysning
        show_header_toggle: true
        state_color: true
      - type: entities
        entities:
          - automation.friggebod_belysning_on_1
          - automation.friggebod_ute_on_sensor_on_500
          - automation.friggebod_ute_on_500
          - automation.friggebod_ute_off_600
          - automation.spabelysning_on_5
          - automation.utebelysning_off_22_00_00_borta
          - automation.utebelysning_off_22_00_00_hemma_vardag
          - automation.utebelysning_off_all_off_hemma_helg
        title: Utebelysning
        show_header_toggle: true
        state_color: true
      - type: entities
        entities:
          - automation.friggebod_fasadbelysning_on_sensor_on_40
          - automation.friggebod_fasadbelysning_on_home_40
          - automation.friggebod_fasadbelysning_on_away_40
          - automation.forrad_fasadbelysning_on_40
          - automation.huvudentre_belysning_on_40
          - automation.tvattstuga_fasadbelysning_on_40
          - automation.friggebod_fasadbelysning_off
          - automation.friggebod_fasadbelysning_off_60
          - automation.forrad_fasadbelysning_off_60
          - automation.huvudentre_belysning_off_60
          - automation.tvattstuga_fasadbelysning_off_60
        title: Fasadbelysning
        show_header_toggle: true
        state_color: true
      - type: entities
        entities:
          - entity: automation.tradgardsbelysning_off
          - entity: automation.tradgardsbelysning_on_away_40
          - entity: automation.tradgardsbelysning_on_home_40
          - entity: automation.tradgardsbelysning_on_sensor_on_40
          - entity: automation.tradgardsbelysning_off_60
        title: Trädgårdsbelysning
        show_header_toggle: true
        state_color: true
  - path: ventilation
    title: Ventilation
    badges: []
    cards:
      - type: entities
        entities:
          - automation.forcerad_snabbt_okande_fukt
          - automation.forcerad_badrumsfonster_hog_fukt
          - automation.normal_badrumsfonster_lag_fukt
          - automation.normal_badrumsfonster_stabiliserad_fukt 
          - automation.normal_hog_fukt_i_huset 
        title: Ventilation Low/High
        show_header_toggle: true
        state_color: true
      - type: entities
        entities:
          - automation.badrumsfonster_hog_fukt_larm
        title: Ventilation Low/High off
        show_header_toggle: true
        state_color: true
      - type: entities
        entities:
          - automation.ventilation_off_60_borta_ute_24degc_inne_23degc
          - automation.ventilation_off_borta_ute_24degc_60_inne_23degc
          - automation.ventilation_off_inne_23degc_borta_60_ute_24degc
          - automation.ventilation_off_ute_24degc_borta_60_inne_23degc
          - automation.ventilation_on_60_off
          - automation.ventilation_on_hemma_off
          - automation.ventilation_on_inne_23degc_off
          - automation.ventilation_on_ute_22degc_off
        title: Ventilation On/Off
        show_header_toggle: true
        state_color: true
  - path: mediaplayer
    title: Mediaspelare
    badges: []
    cards:
      - type: entities
        entities:
          - automation.mediaspelare_off_borta
          - automation.satt_pa_mediaspelare_vid_watch_tv
          - automation.satt_pa_mediaspelare_vid_listen_to_radio
          - automation.satt_pa_mediaspelare_vid_watch_chromecast
          - automation.satt_pa_mediaspelare_vid_listen_to_spotify
          - automation.satt_pa_mediaspelare_vid_watch_chromecast_ultra
          - automation.satt_pa_mediaspelare_vid_listen_to_chromecast_ultra
          - automation.satt_pa_subbasar_vid_poweron
          - automation.stang_av_subbasar_vid_poweroff
          - automation.satt_pa_subbasar_vid_hog_volym
          - automation.stang_av_subbasar_vid_lag_volym
          - automation.satt_pa_tv_bank_vid_rorelse
          - automation.sank_ljuset_vid_hog_volym_pa_tv
          - automation.aterstall_ljuset_vid_lag_volym_pa_tv
          - automation.sank_ljuset_vid_start_av_tv_pa_morgonen
          - automation.sank_ljuset_om_tv_ar_pa_nar_sovrum_tands_pa_morgonen
          - automation.aterstall_ljuset_vid_stang_av_tv_pa_morgonen
        title: Mediaspelare
        show_header_toggle: true
        state_color: true
  - path: bilen
    title: Bilen
    badges: []
    cards:
      - type: entities
        entities:
          - automation.bilen_startar
          - automation.bilen_stannar
        title: Bilen
        show_header_toggle: true
        state_color: true