esphome:
  name: esp32-bathroom
  friendly_name: esp32_bathroom

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret esp32_bathroom_api_key

ota:
  - platform: esphome
    password: !secret esp32_bathroom_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Bathroom Fallback Hotspot"
    password: !secret esp32_bathroom_ap_password

captive_portal:
    