#- alias: "Cam 1 color extractor"
#  trigger:
#    - platform: time_pattern
#      seconds: "/30"

#  action:
#    - service: color_extractor.turn_on
#      data_template:
#        color_extract_path: /media/Day/camera_1_latest.jpg
#        entity_id: light.cam_1_color

#- alias: "Cam 2 color extractor"
#  trigger:
#    - platform: time_pattern
#      seconds: "/30"

#  action:
#    - service: color_extractor.turn_on
#      data_template:
#        color_extract_path: /media/Day/camera_2_latest.jpg
#        entity_id: light.cam_2_color

- alias: "Cam 3 color extractor"
  trigger:
    - platform: time_pattern
      minutes: "/2"

  action:
    - service: color_extractor.turn_on
      data_template:
        color_extract_path: "/media/Day/camera_3_latest.jpg"
        entity_id: light.cam_3_color
        brightness_pct: 100

    - service: automation.turn_off
      entity_id: automation.cam_3_color_extractor

- alias: "Cam 4 color extractor"
  trigger:
    - platform: time_pattern
      minutes: "/2"

  action:
    - service: color_extractor.turn_on
      data_template:
        color_extract_path: "/media/Day/camera_4_latest.jpg"
        entity_id: light.cam_4_color
        brightness_pct: 100

    - service: automation.turn_off
      entity_id: automation.cam_4_color_extractor