- alias: "Cam 1 color extractor"
  trigger:
    - platform: time_pattern
      seconds: "/2"

  action:
    - service: color_extractor.turn_on
      data_template:
        color_extract_path: "/media/Day/camera_1_latest.jpg"
        entity_id: light.cam_1_color
        brightness_pct: 100

    - service: automation.turn_off
      entity_id: automation.cam_1_color_extractor

- alias: "Cam 2 color extractor"
  trigger:
    - platform: time_pattern
      seconds: "/2"

  action:
    - service: camera.snapshot
      target:
        entity_id: camera.yourcamera
      data:
#        filename: '/media/color_extractor/cam_2_{{ now().strftime("%Y%m%d-%H%M%S") }}.jpg'
        filename: '/media/color_extractor/cam_2.jpg'
    - delay: '00:00:05'
    - service: color_extractor.turn_on
      data_template:
        color_extract_path: "/media/color_extractor/cam_2.jpg"
        entity_id: light.cam_2_color
        brightness_pct: 100

    - service: automation.turn_off
      entity_id: automation.cam_2_color_extractor
      
- alias: "Cam 3 color extractor"
  trigger:
    - platform: time_pattern
      seconds: "/2"

  action:
    - service: color_extractor.turn_on
      data_template:
        color_extract_path: "/media/Day/camera_3_latest.jpg"
        entity_id: light.cam_3_color
        brightness_pct: 100

    - service: automation.turn_off
      entity_id: automation.cam_3_color_extractor

- alias: "Cam 4 color extractor"
  trigger:
    - platform: time_pattern
      seconds: "/2"

  action:
    - service: color_extractor.turn_on
      data_template:
        color_extract_path: "/media/Day/camera_4_latest.jpg"
        entity_id: light.cam_4_color
        brightness_pct: 100

    - service: automation.turn_off
      entity_id: automation.cam_4_color_extractor