  ########################################
  ### Starta elvärme garage            ###
  ### T: sensor.forrad_temperature < 5 ###
  ### T: sensor.garage_temperature < 5 ###
  ### A: switch.garage_elvarme = on    ###
  ########################################
- alias: Starta elvärme 5 grader
  trigger:
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      below: '5'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      below: '5'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.garage_elvarme

  ########################################
  ### Starta elvärme garage            ###
  ### T: sensor.forrad_temperature < 8 ###
  ### T: sensor.garage_temperature < 8 ###
  ### A: switch.garage_elvarme = on    ###
  ########################################
- alias: Starta elvärme 8 grader
  trigger:
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      below: '8'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      below: '8'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.garage_elvarme

  #########################################
  ### Stoppa elvärme garage             ###
  ### T: sensor.forrad_temperature > 7  ###
  ### T: sensor.garage_temperature > 7  ###
  ### A: switch.garage_elvarme = off    ###
  #########################################
- alias: Stoppa elvärme 7 grader
  trigger:
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      above: '7'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      above: '7'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.garage_elvarme

  #########################################
  ### Stoppa elvärme garage             ###
  ### T: sensor.forrad_temperature > 10 ###
  ### T: sensor.garage_temperature > 10 ###
  ### A: switch.garage_elvarme = off    ###
  #########################################
- alias: Stoppa elvärme 10 grader
  trigger:
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      above: '10'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      above: '10'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.garage_elvarme
