automation:
    ########################################
    ### Starta elv채rme                   ###
    ### T: sensor.forrad_temperature < 8 ###
    ### A: switch.garage_elvarme = on    ###
    ########################################
  - alias: Starta elv채rme
    trigger:
      platform: numeric_state
      entity_id: sensor.forrad_temperature
      above: '66'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.garage_elvarme

    #########################################
    ### Stoppa elv채rme                    ###
    ### T: sensor.forrad_temperature > 10 ###
    ### A: switch.garage_elvarme = off    ###
    #########################################
  - alias: Stoppa elv채rme
    trigger:
      platform: numeric_state
      entity_id: sensor.forrad_temperature
      below: '64'
    action:
      - service: homeassistant.turn_off
        entity_id: switch.garage_elvarme
