  ########################################
  ### Starta elvärme garage            ###
  ### T: sensor.forrad_temperature < 5 ###
  ### A: switch.garage_elvarme = on    ###
  ########################################
- alias: Starta elvärme 5 grader
  mode: queued

  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.ute
        below: 4

  trigger:
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      below: '5'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      below: '4'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      below: '3'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      below: '2'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      below: '1'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.garage_elvarme

  ########################################
  ### Starta elvärme garage            ###
  ### T: sensor.forrad_temperature < 8 ###
  ### A: switch.garage_elvarme = on    ###
  ########################################
- alias: Starta elvärme 8 grader
  mode: queued

    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.ute
        below: 7

  trigger:
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      below: '8'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      below: '7'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      below: '6'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      below: '5'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      below: '4'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      below: '3'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      below: '2'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      below: '1'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.garage_elvarme

  #########################################
  ### Stoppa elvärme garage             ###
  ### T: sensor.forrad_temperature > 7  ###
  ### T: sensor.garage_temperature > 7  ###
  ### A: switch.garage_elvarme = off    ###
  #########################################
- alias: Stoppa elvärme 7 grader
  mode: queued
  trigger:
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      above: '7'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      above: '8'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      above: '9'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      above: '10'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      above: '11'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      above: '12'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      above: '13'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      above: '14'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      above: '15'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      above: '7'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      above: '8'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      above: '9'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      above: '10'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      above: '11'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      above: '12'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      above: '13'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      above: '14'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      above: '15'

  action:
    - service: homeassistant.turn_off
      entity_id: switch.garage_elvarme

  #########################################
  ### Stoppa elvärme garage             ###
  ### T: sensor.forrad_temperature > 10 ###
  ### T: sensor.garage_temperature > 10 ###
  ### A: switch.garage_elvarme = off    ###
  #########################################
- alias: Stoppa elvärme 10 grader
  mode: queued
  trigger:
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      above: '10'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      above: '11'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      above: '12'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      above: '13'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      above: '14'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      above: '15'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      above: '10'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      above: '11'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      above: '12'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      above: '13'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      above: '14'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      above: '15'

  action:
    - service: homeassistant.turn_off
      entity_id: switch.garage_elvarme
