  ########################################
  ### Starta elvärme garage            ###
  ### T: sensor.forrad_temperature < 7 ###
  ### T: sensor.garage_temperature < 7 ###
  ### A: switch.garage_elvarme = on    ###
  ########################################
- alias: Starta elvärme 7 grader
  id: ABCDEFGHIJKLM 
  mode: queued

  trigger:
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      below: '7'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      below: '6'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      below: '5'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      below: '4'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      below: '3'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      below: '2'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      below: '1'

    - platform: numeric_state
      entity_id: sensor.garage_temperature
      below: '7'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      below: '6'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      below: '5'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      below: '4'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      below: '3'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      below: '2'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      below: '1'
      
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.ute
        below: 6

  action:
    - service: homeassistant.turn_on
      entity_id: switch.garage_elvarme

  #########################################
  ### Starta elvärme garage             ###
  ### T: sensor.forrad_temperature < 12 ###
  ### T: sensor.garage_temperature < 12 ###
  ### A: switch.garage_elvarme = on     ###
  #########################################
- alias: Starta elvärme 12 grader
  id: ABCDEFGHIJKLM 
  mode: queued

  trigger:
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      below: '12'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      below: '11'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      below: '10'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      below: '9'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      below: '8'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      below: '7'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      below: '6'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      below: '5'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      below: '4'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      below: '3'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      below: '2'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      below: '1'

    - platform: numeric_state
      entity_id: sensor.garage_temperature
      below: '12'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      below: '11'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      below: '10'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      below: '9'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      below: '8'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      below: '7'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      below: '6'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      below: '5'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      below: '4'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      below: '3'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      below: '2'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      below: '1'

  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.ute
        below: 10

  action:
    - service: homeassistant.turn_on
      entity_id: switch.garage_elvarme

  #########################################
  ### Stoppa elvärme garage             ###
  ### T: sensor.forrad_temperature > 9  ###
  ### T: sensor.garage_temperature > 9  ###
  ### A: switch.garage_elvarme = off    ###
  #########################################
- alias: Stoppa elvärme 9 grader
  id: ABCDEFGHIJKLM 
  mode: queued

  trigger:
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      above: '9'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      above: '10'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      above: '11'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      above: '12'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      above: '13'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      above: '14'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      above: '15'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      above: '16'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      above: '17'

    - platform: numeric_state
      entity_id: sensor.garage_temperature
      above: '9'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      above: '10'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      above: '11'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      above: '12'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      above: '13'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      above: '14'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      above: '15'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      above: '16'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      above: '17'

  action:
    - service: homeassistant.turn_off
      entity_id: switch.garage_elvarme

  #########################################
  ### Stoppa elvärme garage             ###
  ### T: sensor.forrad_temperature > 14 ###
  ### T: sensor.garage_temperature > 14 ###
  ### A: switch.garage_elvarme = off    ###
  #########################################
- alias: Stoppa elvärme 14 grader
  id: ABCDEFGHIJKLM 
  mode: queued

  trigger:
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      above: '14'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      above: '15'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      above: '16'
    - platform: numeric_state
      entity_id: sensor.forrad_temperature
      above: '17'

    - platform: numeric_state
      entity_id: sensor.garage_temperature
      above: '14'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      above: '15'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      above: '16'
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      above: '17'

  action:
    - service: homeassistant.turn_off
      entity_id: switch.garage_elvarme
