- alias: "Hall: tänd 1% vid Dagbelysning"
  description: "Kör script.hall_taklampor_1_procent när input_select.light_inside == Dagbelysning och input_select.facade_lights != Släckt"
  id: hall_tand_1_vid_dagbelysning
  mode: single
  trigger:
    - platform: state
      entity_id: input_select.light_inside
      to: 'Dagbelysning'
    - platform: state
      entity_id: input_select.facade_lights
  condition:
    - condition: state
      entity_id: input_select.light_inside
      state: 'Dagbelysning'
    - condition: template
      value_template: "{{ states('input_select.facade_lights') != 'Släckt' }}"
  action:
    - service: script.hall_taklampor_1_procent
