- alias: Frigate - Snapshot on person detected
  mode: parallel
  max: 10

  trigger:
    - platform: mqtt
      topic: frigate/events

  condition:
    - condition: template
      value_template: >
        {{ trigger.payload_json["type"] == "new" and
           trigger.payload_json["after"]["label"] == "person" and
           trigger.payload_json["after"]["camera"] in
           ["cam3","cam5","cam6","cam7","cam8"] }}

  action:
    - service: camera.snapshot
      target:
        entity_id: >
          camera.{{ trigger.payload_json["after"]["camera"] }}
      data:
        filename: >
          /media/snapshots/frigate/
          {{ trigger.payload_json["after"]["camera"] }}/
          {{ now().strftime("%Y-%m-%d_%H-%M-%S") }}_
          {{ trigger.payload_json["after"]["id"] }}.jpg

    - service: camera.snapshot
      target:
        entity_id: >
          camera.{{ trigger.payload_json["after"]["camera"] }}
      data:
        filename: >
          /media/snapshots/frigate/
          {{ trigger.payload_json["after"]["camera"] }}/latest.jpg


- alias: Reolink - Snapshot on person detected
  mode: parallel
  max: 10

  trigger:
    - platform: state
      entity_id:
        - binary_sensor.cam3_person_detected
        - binary_sensor.cam5_person_detected
        - binary_sensor.cam6_person_detected
        - binary_sensor.cam7_person_detected
        - binary_sensor.cam8_person_detected
      to: "on"

  action:
    - service: camera.snapshot
      target:
        entity_id: >
          camera.{{ trigger.entity_id.split('.')[1].replace('_person_detected','') }}
      data:
        filename: >
          /media/snapshots/reolink/
          {{ trigger.entity_id.split('.')[1].replace('_person_detected','') }}/
          {{ now().strftime("%Y-%m-%d_%H-%M-%S") }}.jpg

    - service: camera.snapshot
      target:
        entity_id: >
          camera.{{ trigger.entity_id.split('.')[1].replace('_person_detected','') }}
      data:
        filename: >
          /media/snapshots/reolink/
          {{ trigger.entity_id.split('.')[1].replace('_person_detected','') }}/latest.jpg
