- alias: Stäng av automationer
  trigger:
    platform: state
    entity_id: binary_sensor.turn_off_automation
    to: 'on'
  action:
    - service: automation.turn_off
      entity_id:
        - automation.uterums_ledbelysning_on_18
        - automation.uterums_ledbelysning_on_250
        - automation.uterums_ledbelysning_on_home
        - automation.uterums_ledbelysning_off_15
        - automation.uterums_ledbelysning_off_all_off_hemma
        - automation.uterums_ledbelysning_off_borta
        - automation.satt_pa_mediaspelare_om_off
        - automation.satt_pa_mediaspelare_vid_mediaspelare_on
        - automation.satt_pa_subbasar_vid_mediaspelare_on

- alias: Sätt på automationer
  trigger:
    platform: state
    entity_id: binary_sensor.turn_off_automation
    to: 'off'
  action:
    - service: automation.turn_on
      entity_id:
        - automation.uterums_ledbelysning_on_18
        - automation.uterums_ledbelysning_on_250
        - automation.uterums_ledbelysning_on_home
        - automation.uterums_ledbelysning_off_15
        - automation.uterums_ledbelysning_off_all_off_hemma
        - automation.uterums_ledbelysning_off_borta
        - automation.satt_pa_mediaspelare_om_off
        - automation.satt_pa_mediaspelare_vid_mediaspelare_on
        - automation.satt_pa_subbasar_vid_mediaspelare_on
