automation:
    #############################################
    ### Starta luftavfuktare                  ###
    ### T: sensor.forrad_humidity > 66        ###
    ### A: switch.garage_luftavfuktare_2 = on ###
    #############################################
  - alias: Starta luftavfuktare
    initial_state: 'on'
    trigger:
      platform: numeric_state
      entity_id: sensor.forrad_humidity
      above: '66'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.garage_luftavfuktare_2

    ##############################################
    ### Stoppa luftavfuktare                   ###
    ### T: sensor.forrad_humidity < 64         ###
    ### A: switch.garage_luftavfuktare_2 = off ###
    ##############################################
  - alias: Stoppa luftavfuktare
    initial_state: 'on'
    trigger:
      platform: numeric_state
      entity_id: sensor.forrad_humidity
      below: '64'
    action:
      - service: homeassistant.turn_off
        entity_id: switch.garage_luftavfuktare_2
