

binary_sensor:
  - platform: template
    sensors:
      object_detected:
        friendly_name: "Objekt detekterat"
        value_template: >-
          {{ is_state('binary_sensor.cam5_all_occupancy', 'on') or is_state('binary_sensor.cam7_all_occupancy', 'on') }}
        device_class: motion  # Optional: Set the type of the sensor (e.g., motion, door, etc.)

##################
### Automation ###
##################
automation:
  #########################
  ### Camera 5 Light on ###
  #########################
  - alias: Camera 5 Light on 
    id: '1416857464436' 
    mode: single

    trigger:
      - platform: state
        entity_id: binary_sensor.object_detected
        to: 'on'

    condition:
      condition: and
      conditions:
        - condition: numeric_state
          entity_id: sensor.ljusstyrka
          below: 5

    action:
      - service: light.turn_on
        target:
          entity_id: light.stralkastare_husgavel

  ##########################
  ### Camera 5 Light off ###
  ##########################
  - alias: Camera 5 Light off 
    id: '1415557464436' 
    mode: single

    trigger:
      - platform: state
        entity_id: binary_sensor.object_detected
        to: 'off'

    conditions:
      - condition: state
        entity_id: light.stralkastare_husgavel
        state: 'on'

    action:
      - service: light.turn_off
        target:
          entity_id: light.stralkastare_husgavel
