##################
### Automation ###
##################
automation:
  #####################################
  ### Processes image for detection ###
  #####################################
  ### - every 4 sec                 ###    
  ### - detection activated         ###
  #####################################
  - alias: Camera 2 Image processing detection activated

    # Every 4 sec
    trigger:
      - platform: time_pattern
        seconds: "/4"

    # Alarm activated
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.camera_detection_activated
          state: 'on'

    # Scan a new image
    action:
      - service: image_processing.scan
        data:
          entity_id: image_processing.deepstack_camera_2

  #####################################
  ### Processes image for detection ###
  #####################################
  ### - every 10 sec                ###
  ### - detection inactivated       ###
  #####################################
  - alias: Camera 2 Image processing detection inactivated

    # Every 10 sec
    trigger:
      - platform: time_pattern
        seconds: "/10"

    # Alarm activated
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.camera_detection_activated
          state: 'off'

    # Scan a new image
    action:
      - service: image_processing.scan
        data:
          entity_id: image_processing.deepstack_camera_2
