##################
### Automation ###
##################
automation:
  ####################################
  ### Processes image mode Warning ###
  ####################################
  ### - every 4 sec                ###    
  ### - mode Warning               ###
  ####################################
  - alias: Camera 2 Image processing mode Warning

    # Every 4 sec
    trigger:
      - platform: time_pattern
        seconds: "/4"

    # Mode Warning
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.camera_mode
          state: 'Warning'

    # Scan a new image
    action:
      - service: image_processing.scan
        data:
          entity_id: image_processing.deepstack_camera_2

  #################################
  ### Processes image mode Info ###
  #################################
  ### - every 10 sec            ###
  ### - mode Info               ###
  #################################
  - alias: Camera 2 Image processing mode Info

    # Every 10 sec
    trigger:
      - platform: time_pattern
        seconds: "/10"

    # Mode Info
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.camera_mode
          state: 'Info'

    # Scan a new image
    action:
      - service: image_processing.scan
        data:
          entity_id: image_processing.deepstack_camera_2
