##################
### Automation ###
##################
automation:
  - alias: Camera 1 Ir on
    id: '1782448553242' 
    mode: single

    trigger:
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: input_select.camera_mode
        to: "Away"
      - platform: state
        entity_id: input_select.camera_mode
        to: "Night"

    action:
      - service: homeassistant.turn_on
        entity_id: switch.kamera1_infra_red_lights_in_night_mode

  - alias: Camera 1 Ir off
    id: '1782447693242' 
    mode: single

    trigger:
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: input_select.camera_mode
        to: "Day"

    action:
      - service: homeassistant.turn_off
        entity_id: switch.kamera1_infra_red_lights_in_night_mode
