####################################################
#                                                  #
#                      FFMPEG                      #
#                                                  #
####################################################
#https://www.home-assistant.io/integrations/ffmpeg/
ffmpeg:

####################################################
#                                                  #
#                     STREAM                       #
#                                                  #
####################################################
# Enable stream
# https://www.home-assistant.io/integrations/stream/
stream:

####################################################
#                                                  #
#                      CAMERA                      #
#                                                  #
####################################################
#camera:
#  - platform: reolink_dev
#    name: Kamera 1
#    host: 192.168.1.20
#    username: !secret Camera_User
#    password: !secret Camera_Password
#    scan_interval: 5

#  - platform: reolink_dev
#    name: Kamera 2
#    host: 192.168.1.21
#    username: !secret Camera_User
#    password: !secret Camera_Password
#    scan_interval: 5

#  - platform: reolink_dev
#    name: Kamera 3
#    host: 192.168.1.22
#    username: !secret Camera_User
#    password: !secret Camera_Password
#    scan_interval: 5

#  - platform: reolink_dev
#    name: Kamera 4
#    host: 192.168.1.34
#    username: !secret Camera_User
#    password: !secret Camera_Password
#    scan_interval: 5


####################################################
#                                                  #
#                    COMMAND_LINES                 #
#                                                  #
####################################################
command_line:
  - sensor:
      name: Media files
      command: "ls -l /media | wc -l"
      value_template: "{{ value | round(1) }}"

  - sensor:
      name: Camera files
      command: "ls -l /config/camera | wc -l"
      value_template: "{{ value | round(1) }}"

####################################################
#                                                  #
#                    INPUT_SELECT                  #
#                                                  #
####################################################
input_select:
  camera_mode:
    name: Kamera mode
    icon: mdi:video-outline
    options:
     - Off   # Off
     - Day   # Info
     - Night # Warning
     - Away  # Warning

####################################################
#                                                  #
#                    INPUT_NUMBER                  #
#                                                  #
####################################################
input_number:
  # Used for control the delay time between image processing
  camera_duration:
    name: Kamera väntetid mellan bild analys
    initial: 500
    min: 0
    max: 1000
    step: 100

####################################################
#                                                  #
#                        TIMER                     #
#                                                  #
####################################################
timer:
  # Used for control the delay time between image processing
  timer_camera_motion_detected:
    name: Timer camera motion detected
    duration: '00:00:30'

##################
### Automation ###
##################
automation:
  #################################
  ### Activate camera mode Away ###
  #################################
  - alias: Camera mode Away
    trigger:
      - platform: state
        entity_id: input_select.home_status
        to: 'Borta'

    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.camera_mode
          option: Away

  ################################
  ### Activate camera mode Day ###
  ################################
  - alias: Camera mode Day
    trigger:
      - platform: state
        entity_id: input_select.home_status
        to: 'Hemma på'

    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.camera_mode
          option: Day

  ##################################
  ### Activate camera mode Night ###
  ##################################
  - alias: Camera mode Night
    trigger:
      platform: state
      entity_id: input_select.home_status
      to: "Hemma av"

    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.camera_mode
          option: Night

  #########################
  ### Delete old images ###
  #########################
  - alias: Camera delete 10 days old images
    trigger:
      - platform: time
        at: "00:01:00" # HH:MM:SS

    action:
      - service: shell_command.delete_10_days_old_images_in_camera_deepstack_photo
      - service: shell_command.delete_10_days_old_images_in_camera_motion_detected
      - service: shell_command.delete_10_days_old_images_in_media_animal
      - service: shell_command.delete_10_days_old_images_in_media_away
      - service: shell_command.delete_10_days_old_images_in_media_day
      - service: shell_command.delete_10_days_old_images_in_media_night
      - service: shell_command.delete_10_days_old_videos_in_media_video_away
      - service: shell_command.delete_10_days_old_videos_in_media_video_night

  #######################################
  ### Camera Motion Set duration time ###
  #######################################
  - alias: Camera Motion Set duration time
    mode: restart

    trigger:
      - platform: event
        event_type: deepstack.object_detected

   # Need to be a person on the image from camera 3
    condition:
      condition: and
      conditions:

        # Person on image is needed
        - condition: template
          value_template: >
            {{ trigger.event.data.object_type == 'person' }}

    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.camera_duration
          value: 0

      # Cancel timer and reset to max time
      - service: timer.cancel
        entity_id: timer.timer_camera_motion_detected

      # Start timer and count down
      - service: timer.start
        entity_id: timer.timer_camera_motion_detected

  #########################################
  ### Camera Motion Reset duration time ###
  #########################################
  - alias: Camera Motion Reset duration time
    trigger:
      # Timer finished after 30 sec
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.timer_camera_motion_detected
 
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.camera_duration
          value: 500


  - alias: Cpu temp below 58.0
    trigger:
      platform: numeric_state
      entity_id: sensor.cpu_temperature
      below: '58.0'

    condition:
      condition: and
      conditions:
        - condition: numeric_state
          entity_id: input_number.camera_duration
          above: '0'

    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.camera_duration
          value: 500

  - alias: Cpu temp 58.0
    trigger:
      platform: numeric_state
      entity_id: sensor.cpu_temperature
      below: '58.1'
      above: '57.9'

    condition:
      condition: and
      conditions:
        - condition: numeric_state
          entity_id: input_number.camera_duration
          above: '0'

    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.camera_duration
          value: 600

  - alias: Cpu temp 58.5
    trigger:
      platform: numeric_state
      entity_id: sensor.cpu_temperature
      below: '58.6'
      above: '58.4'

    condition:
      condition: and
      conditions:
        - condition: numeric_state
          entity_id: input_number.camera_duration
          above: '0'

    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.camera_duration
          value: 700

  - alias: Cpu temp 59.0
    trigger:
      platform: numeric_state
      entity_id: sensor.cpu_temperature
      below: '59.1'
      above: '58.9'

    condition:
      condition: and
      conditions:
        - condition: numeric_state
          entity_id: input_number.camera_duration
          above: '0'

    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.camera_duration
          value: 800

  - alias: Cpu temp 59.5
    trigger:
      platform: numeric_state
      entity_id: sensor.cpu_temperature
      below: '59.6'
      above: '59.4'

    condition:
      condition: and
      conditions:
        - condition: numeric_state
          entity_id: input_number.camera_duration
          above: '0'

    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.camera_duration
          value: 900

  - alias: Cpu temp above 59.5
    trigger:
      platform: numeric_state
      entity_id: sensor.cpu_temperature
      above: '59.9'

    condition:
      condition: and
      conditions:
        - condition: numeric_state
          entity_id: input_number.camera_duration
          above: '0'

    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.camera_duration
          value: 1000

##############
### Script ###
##############
script:
  # Delete all files, Used by user
  delete_camera_files:
    sequence:
      - service: shell_command.delete_camera_files_1
      - service: shell_command.delete_camera_files_2
      - service: shell_command.delete_camera_files_3
      - service: shell_command.delete_camera_files_4
      - service: shell_command.delete_camera_files_5
      - service: shell_command.delete_camera_files_6
      - service: shell_command.delete_camera_files_7
      - service: shell_command.delete_camera_files_8

  # Delete 5 days old files, Used by user
  delete_5_days_old_camera_files:
    sequence:
      - service: shell_command.delete_5_days_old_images_in_camera_deepstack_photo
      - service: shell_command.delete_5_days_old_images_in_camera_motion_detected
      - service: shell_command.delete_5_days_old_images_in_media_animal
      - service: shell_command.delete_5_days_old_images_in_media_away
      - service: shell_command.delete_5_days_old_images_in_media_day
      - service: shell_command.delete_5_days_old_images_in_media_night
      - service: shell_command.delete_5_days_old_videos_in_media_video_away
      - service: shell_command.delete_5_days_old_videos_in_media_video_night

#####################
### Shell command ###
#####################
shell_command:
  # Delete 10 days old images from folders:
  delete_10_days_old_images_in_camera_deepstack_photo: 'find /config/camera/deepstack_photo -mtime +10 -type f -delete' 
  delete_10_days_old_images_in_camera_motion_detected: 'find /config/camera/motion_detected -mtime +10 -type f -delete' 
  delete_10_days_old_images_in_media_animal: 'find /media/animal -mtime +10 -type f -delete' 
  delete_10_days_old_images_in_media_away: 'find /media/Away -mtime +10 -type f -delete' 
  delete_10_days_old_images_in_media_day: 'find /media/Day -mtime +10 -type f -delete' 
  delete_10_days_old_images_in_media_night: 'find /media/Night -mtime +10 -type f -delete' 

  # Delete 10 days old videos from folders:
  delete_10_days_old_videos_in_media_video_away: 'find /media/video/Away -mtime +10 -type f -delete' 
  delete_10_days_old_videos_in_media_video_night: 'find /media/video/Night -mtime +10 -type f -delete' 

  # Delete 5 days old images from folders:
  delete_5_days_old_images_in_camera_deepstack_photo: 'find /config/camera/deepstack_photo -mtime +5 -type f -delete' 
  delete_5_days_old_images_in_camera_motion_detected: 'find /config/camera/motion_detected -mtime +5 -type f -delete' 
  delete_5_days_old_images_in_media_animal: 'find /media/animal -mtime +5 -type f -delete' 
  delete_5_days_old_images_in_media_away: 'find /media/Away -mtime +5 -type f -delete' 
  delete_5_days_old_images_in_media_day: 'find /media/Day -mtime +5 -type f -delete' 
  delete_5_days_old_images_in_media_night: 'find /media/Night -mtime +5 -type f -delete' 

  # Delete 5 days old videos from folders:
  delete_5_days_old_videos_in_media_video_away: 'find /media/video/Away -mtime +5 -type f -delete' 
  delete_5_days_old_videos_in_media_video_night: 'find /media/video/Night -mtime +5 -type f -delete' 

  # Used by script delete_camera_files
  delete_camera_files_1: 'rm -f /config/camera/deepstack_photo/*'
  delete_camera_files_2: 'rm -f /config/camera/motion_detected/*'
  delete_camera_files_3: 'rm -f /media/animal/*'
  delete_camera_files_4: 'rm -f /media/Away/*'
  delete_camera_files_5: 'rm -f /media/Day/*'
  delete_camera_files_6: 'rm -f /media/Night/*'
  delete_camera_files_7: 'rm -f /media/video/Away/*'
  delete_camera_files_8: 'rm -f /media/video/Night/*'



