#####################
### Input Boolean ###
#####################
input_boolean:
  camera_3_light_control:
    name: Camera 3 ljus kontroll 
    initial: off

  camera_2_light_control:
    name: Camera 2 ljus kontroll 
    initial: off

  camera_light_control:
    name: Camera ljus kontroll 
    initial: off

# Sätts till on när person detekterats vid kamera 2 och entre lampa är tänd
# Sätts till off när entre lampa släcks
  camera_2_max_light:
    name: Camera 2 max ljus
    initial: off

#############
### Timer ###
#############
timer:
  timer_camera_3_light_control:
    name: Timer camera 3 ljus kontroll
    duration: '00:00:45'

  timer_camera_2_light_control:
    name: Timer camera 2 ljus kontroll
    duration: '00:00:45'

##################
### Automation ###
##################
automation:
  ###########################################################
  ### Light Friggebod on if Person detected and light off ###
  ###########################################################
  - alias: Light Friggebod on if Person detected and light off
    mode: single

    trigger:
      - platform: state
        entity_id: input_boolean.camera_3_light_control
        to: 'on'
      - platform: state
        entity_id: input_boolean.camera_2_light_control
        to: 'on'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.huvudentre
          state: 'off'
        - condition: state
          entity_id: light.friggebod_fasad
          state: 'off'
    action:
      - service: script.friggebod_fasadbelysning_min

  ############################################################
  ### Light Friggebod off if Person detected and light off ###
  ############################################################
  - alias: Light Friggebod off if Person detected and light off
    mode: single

    trigger:
      - platform: state
        entity_id: input_boolean.camera_3_light_control
        to: 'off'
      - platform: state
        entity_id: input_boolean.camera_2_light_control
        to: 'off'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.huvudentre
          state: 'off'
        - condition: state
          entity_id: light.friggebod_fasad
          state: 'on'

    action:
      - service: script.friggebod_fasadbelysning_off

  #############################
  ### Camera 2 max light on ###
  #############################
  - alias: Camera 2 max light on
    mode: single

    trigger:
      - platform: state
        entity_id: input_boolean.camera_2_light_control
        to: 'on'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.camera_2_max_light
          state: 'off'
        - condition: state
          entity_id: light.huvudentre
          state: 'on'

    action:
      - delay:
          seconds: 1 # Need to delay 1 sec to make automation "Camera 2 switch max light to normal" work
          
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.camera_2_max_light

  ##############################
  ### Camera 2 max light off ###
  ##############################
  - alias: Camera 2 max light off
    mode: single

    trigger:
      - platform: state
        entity_id: light.huvudentre
        to: 'off'

    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.camera_2_max_light

  #################################################
  ### Camera 2 entre switch max light to normal ###
  #################################################
  - alias: Camera 2 entre switch max light to normal
    mode: single

    trigger:
      - platform: state
        entity_id: input_boolean.camera_light_control
        to: 'off'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.camera_2_max_light
          state: 'off'
        - condition: state
          entity_id: light.huvudentre
          state: 'on'

    action:
      - service: script.huvudentre_belysning_on

  #################################
  ### Camera 3 Light control on ###
  #################################
  - alias: Camera 3 Light control on
    mode: single

    # Object detected
    trigger:
      - platform: event
        event_type: deepstack.object_detected

   # Need to be a person on the image from camera 3
    condition:
      condition: and
      conditions:

        # Needs to be image processing from camera 3
        - condition: template
          value_template: >
            {{ trigger.event.data.entity_id == 'image_processing.deepstack_camera_3' }}

        # Person on image is needed
        - condition: template
          value_template: >
            {{ trigger.event.data.object_type == 'person' }}

    action:
      # camera_3_light_control = on
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.camera_3_light_control

      # Cancel timer and reset to max time
      - service: timer.cancel
        entity_id: timer.timer_camera_3_light_control

      # Start timer and count down
      - service: timer.start
        entity_id: timer.timer_camera_3_light_control

  ##################################
  ### Camera 3 Light control off ###
  ##################################
  - alias: Camera 3 Light control off
    trigger:
      # Timer finished after 45 sec
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.timer_camera_3_light_control
 
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.camera_3_light_control
          state: 'on'
 
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.camera_3_light_control

  #################################
  ### Camera 2 Light control on ###
  #################################
  - alias: Camera 2 Light control on
    mode: single

    trigger:
    # Object detected
    trigger:
      - platform: event
        event_type: deepstack.object_detected

   # Need to be a person on the image from camera 2
    condition:
      condition: and
      conditions:

        # Needs to be image processing from camera 2
        - condition: template
          value_template: >
            {{ trigger.event.data.entity_id == 'image_processing.deepstack_camera_2' }}

        # Person on image is needed
        - condition: template
          value_template: >
            {{ trigger.event.data.object_type == 'person' }}

    action:
      # camera_2_light_control = on
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.camera_2_light_control

      # Cancel timer and reset to max time
      - service: timer.cancel
        entity_id: timer.timer_camera_2_light_control

      # Start timer and count down
      - service: timer.start
        entity_id: timer.timer_camera_2_light_control

  ##################################
  ### Camera 2 Light control off ###
  ##################################
  - alias: Camera 2 Light control off
    trigger:
      # Timer finished after 45 sec
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.timer_camera_2_light_control
 
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.camera_2_light_control
          state: 'on'
 
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.camera_2_light_control

  ###############################
  ### Camera Light control on ###
  ###############################
  - alias: Camera Light control on
    mode: restart

    trigger:
      - platform: state
        entity_id: input_boolean.camera_3_light_control
        to: 'on'
      - platform: state
        entity_id: input_boolean.camera_2_light_control
        to: 'on'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.camera_light_control
          state: 'off'

    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.camera_light_control

  ##################################
  ### Camera Light control off 3 ###
  ##################################
  - alias: Camera Light control off 3
    mode: restart

    trigger:
      - platform: state
        entity_id: input_boolean.camera_3_light_control
        to: 'off'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.camera_2_light_control
          state: 'off'
        - condition: state
          entity_id: input_boolean.camera_light_control
          state: 'on'

    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.camera_light_control

  ##################################
  ### Camera Light control off 2 ###
  ##################################
  - alias: Camera Light control off 2
    mode: restart

    trigger:
      - platform: state
        entity_id: input_boolean.camera_2_light_control
        to: 'off'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.camera_3_light_control
          state: 'off'
        - condition: state
          entity_id: input_boolean.camera_light_control
          state: 'on'

    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.camera_light_control

  ###############################################
  ### Max light huvudentre if person detected ###
  ###############################################
  - alias: Max light huvudentre if person detected
    mode: single

    trigger:
      - platform: state
        entity_id: input_boolean.camera_light_control
        to: 'on'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.huvudentre
          state: 'on'

    action:
      - service: script.huvudentre_belysning_max
          
  #####################################################
  ### Max light tvättstuga fasad if person detected ###
  #####################################################
  - alias: Max light tvättstuga fasad if person detected
    mode: single

    trigger:
      - platform: state
        entity_id: input_boolean.camera_light_control
        to: 'on'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.tvattstugan_fasad
          state: 'on'

    action:
      - service: script.tvattstuga_fasadbelysning_max

  ####################################################
  ### Max light friggebod fasad if person detected ###
  ####################################################
  - alias: Max light friggebod fasad if person detected
    mode: single

    trigger:
      - platform: state
        entity_id: input_boolean.camera_light_control
        to: 'on'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.friggebod_fasad
          state: 'on'

    action:
      - service: script.friggebod_fasadbelysning_max

  #################################################
  ### Max light förråd fasad if person detected ###
  #################################################
  - alias: Max light förråd fasad if person detected
    mode: single

    trigger:
      - platform: state
        entity_id: input_boolean.camera_light_control
        to: 'on'
 
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.forrad_fasad
          state: 'on'

    action:
      - service: script.forrad_fasadbelysning_max

  #######################################################
  ### Reset light huvudentre when switch from home on ###
  #######################################################
  - alias: Reset light huvudentre when switch from home on
    mode: restart

    trigger:
      - platform: state
        entity_id: input_select.home_status
        to: 'Borta'
      - platform: state
        entity_id: input_select.home_status
        to: 'Hemma av'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.huvudentre
          state: 'on'

    action:
      - service: script.huvudentre_belysning_on
          
  ##########################################################
  ### Reset light tvättstuga fasad if no person detected ###
  ##########################################################
  - alias: Reset light tvättstuga fasad if person no detected
    mode: restart

    trigger:
      - platform: state
        entity_id: input_boolean.camera_light_control
        to: 'off'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.tvattstugan_fasad
          state: 'on'

    action:
      - service: script.tvattstuga_fasadbelysning_on

  #########################################################
  ### Reset light friggebod fasad if no person detected ###
  #########################################################
  - alias: Reset light friggebod fasad if person no detected
    mode: restart

    trigger:
      - platform: state
        entity_id: input_boolean.camera_light_control
        to: 'off'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.friggebod_fasad
          state: 'on'

    action:
      - service: script.friggebod_fasadbelysning_on

  ######################################################
  ### Reset light förråd fasad if no person detected ###
  ######################################################
  - alias: Reset light förråd fasad if person no detected
    mode: restart

    trigger:
      - platform: state
        entity_id: input_boolean.camera_light_control
        to: 'off'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.forrad_fasad
          state: 'on'

    action:
      - service: script.forrad_fasadbelysning_on

  ######################################
  ### Flash light if person detected ###
  ######################################
  - alias: Flash light if person detected
    mode: single

    trigger:
      - platform: state
        entity_id: input_boolean.camera_light_control
        to: 'on'

    action:        
      - service: light.toggle
        entity_id: light.vardagsrum_vitrinskap
      - delay:
          seconds: 2
      - service: light.toggle
        entity_id: light.vardagsrum_vitrinskap
      - delay:
          seconds: 2
      - service: light.toggle
        entity_id: light.vardagsrum_vitrinskap
      - delay:
          seconds: 2
      - service: light.toggle
        entity_id: light.vardagsrum_vitrinskap

      - service: automation.turn_off
        entity_id: automation.flash_light_if_person_detected
