##################
### Automation ###
##################
automation:
  #################################
  ### Processes image mode Away ###
  #################################
  ### - every 4 sec             ###    
  ### - mode Away               ###
  #################################
  - alias: Camera 2 Image processing mode Away

    # Every 4 sec
    trigger:
      - platform: time_pattern
        seconds: "/4"

    # Mode Away
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.camera_mode
          state: 'Away'

    # Scan a new image
    action:
      - service: image_processing.scan
        data:
          entity_id: image_processing.deepstack_camera_2

  ################################
  ### Processes image mode Day ###
  ################################
  ### - every 10 sec           ###
  ### - mode Day               ###
  ################################
  - alias: Camera 2 Image processing mode Day

    # Every 10 sec
    trigger:
      - platform: time_pattern
        seconds: "/10"

    # Mode Day
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.camera_mode
          state: 'Day'

    # Scan a new image
    action:
      - service: image_processing.scan
        data:
          entity_id: image_processing.deepstack_camera_2
