#####################
### Input Boolean ###
#####################
input_boolean:
  camera_1_light_control:
    name: Camera 1 ljus kontroll 
    initial: off

  camera_2_light_control:
    name: Camera 2 ljus kontroll 
    initial: off

  camera_light_control:
    name: Camera ljus kontroll 
    initial: off

#############
### Timer ###
#############
timer:
  timer_camera_1_light_control:
    name: Timer camera 1 ljus kontroll
    duration: '00:00:20'

  timer_camera_2_light_control:
    name: Timer camera 2 ljus kontroll
    duration: '00:00:20'

##################
### Automation ###
##################
automation:
  #################################
  ### Camera 1 Light control on ###
  #################################
  - alias: Camera 1 Light control on
    mode: restart

    trigger:
      - platform: event
        event_type: folder_watcher
        event_data:
          event_type: modified
          path: '/config/camera/deepstack_photo/deepstack_camera_1_latest.jpg'

    action:
      # camera_1_light_control = on
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.camera_1_light_control

      # Cancel timer and reset to max time
      - service: timer.cancel
        entity_id: timer.timer_camera_1_light_control

      # Start timer and count down
      - service: timer.start
        entity_id: timer.timer_camera_1_light_control

  ##################################
  ### Camera 1 Light control off ###
  ##################################
  - alias: Camera 1 Light control off
    trigger:
      # Timer finished after 20 sec
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.timer_camera_1_light_control
 
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.camera_1_light_control
          state: 'on'
 
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.camera_1_light_control

  #################################
  ### Camera 2 Light control on ###
  #################################
  - alias: Camera 2 Light control on
    mode: restart

    trigger:
      - platform: event
        event_type: folder_watcher
        event_data:
          event_type: modified
          path: '/config/camera/deepstack_photo/deepstack_camera_2_latest.jpg'

    action:
      # camera_2_light_control = on
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.camera_2_light_control

      # Cancel timer and reset to max time
      - service: timer.cancel
        entity_id: timer.timer_camera_2_light_control

      # Start timer and count down
      - service: timer.start
        entity_id: timer.timer_camera_2_light_control

  ##################################
  ### Camera 2 Light control off ###
  ##################################
  - alias: Camera 2 Light control off
    trigger:
      # Timer finished after 20 sec
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.timer_camera_2_light_control
 
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.camera_2_light_control
          state: 'on'
 
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.camera_2_light_control

  ###############################
  ### Camera Light control on ###
  ###############################
  - alias: Camera Light control on
    mode: restart

    trigger:
      - platform: state
        entity_id: input_boolean.camera_1_light_control
        to: 'on'
      - platform: state
        entity_id: input_boolean.camera_2_light_control
        to: 'on'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.camera_light_control
          state: 'off'

    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.camera_light_control

  ##################################
  ### Camera Light control off 1 ###
  ##################################
  - alias: Camera Light control off 1
    mode: restart

    trigger:
      - platform: state
        entity_id: input_boolean.camera_1_light_control
        to: 'off'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.camera_2_light_control
          state: 'off'
        - condition: state
          entity_id: input_boolean.camera_light_control
          state: 'on'

    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.camera_light_control

  ##################################
  ### Camera Light control off 2 ###
  ##################################
  - alias: Camera Light control off 2
    mode: restart

    trigger:
      - platform: state
        entity_id: input_boolean.camera_2_light_control
        to: 'off'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.camera_1_light_control
          state: 'off'
        - condition: state
          entity_id: input_boolean.camera_light_control
          state: 'on'

    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.camera_light_control

  ###############################################
  ### Max light huvudentre if person detected ###
  ###############################################
  - alias: Max light huvudentre if person detected
    mode: single

    trigger:
      - platform: state
        entity_id: input_boolean.camera_light_control
        to: 'on'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.huvudentre
          state: 'on'

    action:
      - service: light.turn_on
        data:
          entity_id: light.huvudentre
          brightness_pct: 50
          transition: 1
          
  #####################################################
  ### Max light tvättstuga fasad if person detected ###
  #####################################################
  - alias: Max light tvättstuga fasad if person detected
    mode: single

    trigger:
      - platform: state
        entity_id: input_boolean.camera_light_control
        to: 'on'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.tvattstugan_fasad
          state: 'on'

    action:
      - service: light.turn_on
        data:
          entity_id: light.tvattstugan_fasad
          brightness_pct: 100
          transition: 1

  ####################################################
  ### Max light friggebod fasad if person detected ###
  ####################################################
  - alias: Max light friggebod fasad if person detected
    mode: single

    trigger:
      - platform: state
        entity_id: input_boolean.camera_light_control
        to: 'on'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.friggebod_fasad
          state: 'on'

    action:
      - service: light.turn_on
        data:
          entity_id: light.friggebod_fasad
          brightness_pct: 100
          transition: 1

  #################################################
  ### Max light förråd fasad if person detected ###
  #################################################
  - alias: Max light förråd fasad if person detected
    mode: single

    trigger:
      - platform: state
        entity_id: input_boolean.camera_light_control
        to: 'on'
 
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.forrad_fasad
          state: 'on'

    action:
      - service: light.turn_on
        data:
          entity_id: light.forrad_fasad
          brightness_pct: 100
          transition: 1

  #######################################################
  ### Reset light huvudentre when switch from home on ###
  #######################################################
  - alias: Reset light huvudentre when switch from home on
    mode: restart

    trigger:
      - platform: state
        entity_id: input_select.home_status
        to: 'Borta'
      - platform: state
        entity_id: input_select.home_status
        to: 'Hemma av'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.huvudentre
          state: 'on'

    action:
      - service: light.turn_on
        data:
          entity_id: light.huvudentre
          brightness_pct: 10
          transition: 1
          
  ##########################################################
  ### Reset light tvättstuga fasad if no person detected ###
  ##########################################################
  - alias: Reset light tvättstuga fasad if person no detected
    mode: restart

    trigger:
      - platform: state
        entity_id: input_boolean.camera_light_control
        to: 'off'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.tvattstugan_fasad
          state: 'on'

    action:
      - service: light.turn_on
        data:
          entity_id: light.tvattstugan_fasad
          brightness_pct: 65
          transition: 1

  #########################################################
  ### Reset light friggebod fasad if no person detected ###
  #########################################################
  - alias: Reset light friggebod fasad if person no detected
    mode: restart

    trigger:
      - platform: state
        entity_id: input_boolean.camera_light_control
        to: 'off'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.friggebod_fasad
          state: 'on'

    action:
      - service: light.turn_on
        data:
          entity_id: light.friggebod_fasad
          brightness_pct: 30
          transition: 1

  ######################################################
  ### Reset light förråd fasad if no person detected ###
  ######################################################
  - alias: Reset light förråd fasad if person no detected
    mode: restart

    trigger:
      - platform: state
        entity_id: input_boolean.camera_light_control
        to: 'off'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.forrad_fasad
          state: 'on'

    action:
      - service: light.turn_on
        data:
          entity_id: light.forrad_fasad
          brightness_pct: 30
          transition: 1

  ######################################
  ### Flash light if person detected ###
  ######################################
  - alias: Flash light if person detected
    mode: single

    trigger:
      - platform: state
        entity_id: input_boolean.camera_light_control
        to: 'on'

    action:
      - service: automation.turn_off
        entity_id: automation.flash_light_if_person_detected
        
      - service: light.toggle
        entity_id: light.hall_skap
      - service: light.toggle
        entity_id: light.hall_byra

      - delay:
          seconds: 2

      - service: light.toggle
        entity_id: light.hall_skap
      - service: light.toggle
        entity_id: light.hall_byra
