##################
### Automation ###
##################
automation:
  #################################
  ### Processes image mode Away ###
  #################################
  ### - every 4 sec             ###    
  ### - mode Away               ###
  #################################
  - alias: Camera 2 Image processing mode Away
    mode: queued

    # Every 4 sec
    trigger:
      - platform: time_pattern
        seconds: "/4"

    # Mode Away
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.camera_mode
          state: 'Away'

    # Scan a new image
    action:
      - service: image_processing.scan
        data:
          entity_id: image_processing.deepstack_camera_2

  ################################
  ### Processes image mode Day ###
  ################################
  ### - every 10 sec           ###
  ### - mode Day               ###
  ### - light control off      ###
  ################################
  - alias: Camera 2 Image processing mode Day Light control off
    mode: queued
        
    # Every 10 sec
    trigger:
      - platform: time_pattern
        seconds: "/10"

    # Mode Day
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.camera_mode
          state: 'Day'
        - condition: state
          entity_id: input_boolean.camera_light_control
          state: 'off'

    # Scan a new image
    action:
      - service: image_processing.scan
        data:
          entity_id: image_processing.deepstack_camera_2

  ################################
  ### Processes image mode Day ###
  ################################
  ### - every 3  sec           ###
  ### - mode Day               ###
  ### - light control on       ###
  ################################
  - alias: Camera 2 Image processing mode Day Light control on
    mode: queued
        
    # Every 3 sec
    trigger:
      - platform: time_pattern
        seconds: "/3"

    # Mode Day
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.camera_mode
          state: 'Day'
        - condition: state
          entity_id: input_boolean.camera_light_control
          state: 'on'

    # Scan a new image
    action:
      - service: image_processing.scan
        data:
          entity_id: image_processing.deepstack_camera_2

input_boolean.camera_light_control

  ##################################
  ### Processes image mode Night ###
  ##################################
  ### - every 4 sec              ###    
  ### - mode Night               ###
  ##################################
  - alias: Camera 2 Image processing mode Night
    mode: queued

    # Every 4 sec
    trigger:
      - platform: time_pattern
        seconds: "/4"

    # Mode Night
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.camera_mode
          state: 'Night'

    # Scan a new image
    action:
      - service: image_processing.scan
        data:
          entity_id: image_processing.deepstack_camera_2
