ffmpeg:

camera:
  - platform: reolink_dev
    name: Kamera 1
    host: 192.168.1.20
    username: !secret Camera_User
    password: !secret Camera_Password
    scan_interval: 5

  - platform: reolink_dev
    name: Kamera 2
    host: 192.168.1.21
    username: !secret Camera_User
    password: !secret Camera_Password
    scan_interval: 5

binary_sensor:
  - platform: template
    sensors:
      motion_kamera_1:
        friendly_name: Motion Kamera 1
        device_class: motion
        entity_id: camera.kamera_1
        value_template: "{{ is_state('camera.kamera_1', 'motion') }}"
        delay_off: 
          seconds: 30

  - platform: template
    sensors:
      motion_kamera_2:
        friendly_name: Motion Kamera 2
        device_class: motion
        entity_id: camera.kamera_2
        value_template: "{{ is_state('camera.kamera_2', 'motion') }}"
        delay_off: 
          seconds: 30


#binary_sensor:
#  - platform: rest
#    resource: !secret Camera_1_Motion
#    name: Motion Kamera 1
#    scan_interval: 5
#    value_template: “{{ value_json[0].value.state }}”
#    device_class: motion

#  - platform: rest
#    resource: !secret Camera_2_Motion
#    name: Motion Kamera 2
#    scan_interval: 5
#    value_template: “{{ value_json[0].value.state }}”
#    device_class: motion

####################################################
#                                                  #
#                      TIMER                       #
#                                                  #
####################################################
# https://www.home-assistant.io/integrations/timer/
timer:
  # Timers för camera 1
  # Home
  timer_camera_1_home:
    name: Tid kvar camera 1 hemma
    duration: '00:03:00'

  # Away
  timer_camera_1_away:
    name: Tid kvar camera 1 borta
    duration: '00:03:00'

  # Timers för camera 2
  # Home
  timer_camera_2_home:
    name: Tid kvar camera 2 hemma
    duration: '00:03:00'

  # Away
  timer_camera_2_away:
    name: Tid kvar camera 2 borta
    duration: '00:03:00'

####################################################
#                                                  #
#                     INPUT_BOOLEAN                #
#                                                  #
####################################################
# https://www.home-assistant.io/integrations/input_boolean/
input_boolean:
  camera_1_aktiv:
    name: Kamera 1 aktiv
    initial: off

  camera_2_aktiv:
    name: Kamera 2 aktiv
    initial: off

automation:
    ################################################
    ### Startar båda timers vid rörelse camera 1 ###
    ### T: binary_sensor.kamera_1_rorelse == on  ###
    ### A: input_boolean.camera_1_aktiv = on     ###
    ###    timer.timer_camera_1_home = cancel    ###
    ###    timer.timer_camera_1_away = cancel    ###
    ###    timer.timer_camera_1_home = start     ###
    ###    timer.timer_camera_1_away = start     ###
    ################################################
  - alias: Startar Camera 1 timers
    trigger:
      - platform: state
        entity_id: binary_sensor.kamera_1_rorelse
        to: 'on'
    action:
      # Aktiverar rorelsevakt_aktiv
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.camera_1_aktiv

      # Cancel timers, återställer till maxtid
      - service: timer.cancel
        entity_id: timer.timer_camera_1_home
      - service: timer.cancel
        entity_id: timer.timer_camera_1_away

      # Start timers, börjar räkna ner tiden
      - service: timer.start
        entity_id: timer.timer_camera_1_home
      - service: timer.start
        entity_id: timer.timer_camera_1_away

    ################################################
    ### Startar båda timers vid rörelse camera 2 ###
    ### T: binary_sensor.kamera_2_rorelse == on  ###
    ### A: input_boolean.camera_2_aktiv = on     ###
    ###    timer.timer_camera_2_home = cancel    ###
    ###    timer.timer_camera_2_away = cancel    ###
    ###    timer.timer_camera_2_home = start     ###
    ###    timer.timer_camera_2_away = start     ###
    ################################################
  - alias: Startar Camera 2 timers
    trigger:
      - platform: state
        entity_id: binary_sensor.kamera_2_rorelse
        to: 'on'
    action:
      # Aktiverar rorelsevakt_aktiv
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.camera_2_aktiv

      # Cancel timers, återställer till maxtid
      - service: timer.cancel
        entity_id: timer.timer_camera_2_home
      - service: timer.cancel
        entity_id: timer.timer_camera_2_away

      # Start timers, börjar räkna ner tiden
      - service: timer.start
        entity_id: timer.timer_camera_2_home
      - service: timer.start
        entity_id: timer.timer_camera_2_away

    ################################################
    ### Stänger av camera_1_aktiv (home)         ###
    ### T: timer.timer_camera_1_home == finished ###
    ### C: group.track_for_home_devices == home  ###
    ###    input_boolean.camera_1_aktiv == on    ###
    ### A: input_boolean.camera_1_aktiv = off    ###
    ################################################
  - alias: Stänger av camera_1_aktiv (home)
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.timer_camera_1_home
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: group.track_for_home_devices
          state: 'home'
        - condition: state
          entity_id:  input_boolean.camera_1_aktiv
          state: 'on'
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.camera_1_aktiv

    ################################################
    ### Stänger av camera_1_aktiv (away)         ###
    ### T: timer.timer_camera_1_away == finished ###
    ### C: group.track_for_home_devices == away  ###
    ###    input_boolean.camera_1_aktiv == on    ###
    ### A: input_boolean.camera_1_aktiv = off    ###
    ################################################
  - alias: Stänger av camera_1_aktiv (away)
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.timer_camera_1_away
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: group.track_for_home_devices
          state: 'away'
        - condition: state
          entity_id:  input_boolean.camera_1_aktiv
          state: 'on'
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.camera_1_aktiv

    ################################################
    ### Stänger av camera_2_aktiv (home)         ###
    ### T: timer.timer_camera_2_home == finished ###
    ### C: group.track_for_home_devices == home  ###
    ###    input_boolean.camera_2_aktiv == on    ###
    ### A: input_boolean.camera_2_aktiv = off    ###
    ################################################
  - alias: Stänger av camera_2_aktiv (home)
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.timer_camera_2_home
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: group.track_for_home_devices
          state: 'home'
        - condition: state
          entity_id:  input_boolean.camera_2_aktiv
          state: 'on'
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.camera_2_aktiv

    ################################################
    ### Stänger av camera_2_aktiv (away)         ###
    ### T: timer.timer_camera_2_away == finished ###
    ### C: group.track_for_home_devices == away  ###
    ###    input_boolean.camera_2_aktiv == on    ###
    ### A: input_boolean.camera_2_aktiv = off    ###
    ################################################
  - alias: Stänger av camera_2_aktiv (away)
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.timer_camera_2_away
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: group.track_for_home_devices
          state: 'away'
        - condition: state
          entity_id:  input_boolean.camera_2_aktiv
          state: 'on'
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.camera_2_aktiv
