####################################################
#                                                  #
#                      FFMPEG                      #
#                                                  #
####################################################
#https://www.home-assistant.io/integrations/ffmpeg/
ffmpeg:

####################################################
#                                                  #
#                     STREAM                       #
#                                                  #
####################################################
# Enable stream
# https://www.home-assistant.io/integrations/stream/
stream:

####################################################
#                                                  #
#                      CAMERA                      #
#                                                  #
####################################################
camera:
  - platform: reolink_dev
    name: Kamera 1
    host: 192.168.1.20
    username: !secret Camera_User
    password: !secret Camera_Password
    scan_interval: 5

  - platform: reolink_dev
    name: Kamera 2
    host: 192.168.1.21
    username: !secret Camera_User
    password: !secret Camera_Password
    scan_interval: 5

####################################################
#                                                  #
#                    INPUT_SELECT                  #
#                                                  #
####################################################
input_select:
  camera_mode:
    name: Kamera mode
    icon: mdi:video-outline
    options:
     - Off
     - Info
     - Larm

##################
### Automation ###
##################
automation:
  ##################################
  ### Activate camera mode Alarm ###
  ##################################
  - alias: Camera mode Alarm
    trigger:
      - platform: state
        entity_id: input_select.home_status
        to: 'Borta'
      - platform: state
        entity_id: input_select.home_status
        to: 'Hemma av'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.camera_mode
          option: Larm

  #################################
  ### Activate camera mode Info ###
  #################################
  - alias: Camera mode Info
    trigger:
      - platform: state
        entity_id: input_select.home_status
        to: 'Hemma på'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.camera_mode
          option: Info

  #########################
  ### Remove old images ###
  #########################
  - alias: Camera Remove old images
    trigger:
      - platform: time
        at: "00:01:00" # HH:MM:SS
    action:
      - service: shell_command.remove_old_images_in_camera_deepstack_photo
      - service: shell_command.remove_old_images_in_www_latest_person_away
      - service: shell_command.remove_old_images_in_www_latest_person_away_small

##############
### Script ###
##############
script:
  # Delete all files, Used by user
  delete_camera_files:
    sequence:
      - service: shell_command.delete_camera_files_1
      - service: shell_command.delete_camera_files_2
      - service: shell_command.delete_camera_files_3
      - service: shell_command.delete_camera_files_4
      - service: shell_command.delete_camera_files_5
      - service: shell_command.delete_camera_files_6

#####################
### Shell command ###
#####################
shell_command:
  # Delete 10 days old images from folder /config/camera/deepstack_photo
  remove_old_images_in_camera_deepstack_photo: 'find /config/camera/deepstack_photo -mtime +14 -type f -delete' 
  
  # Delete 10 days old images from folder /config/www/motion_detected_away
  remove_old_images_in_www_latest_person_away: 'find /config/camera/www/motion_detected_away -mtime +14 -type f -delete' 

  # Delete 10 days old images from folder /config/www/motion_detected_away
  remove_old_images_in_www_latest_person_away_small: 'find /config/camera/www/motion_detected_away_small -mtime +14 -type f -delete' 

  # Used by script delete_camera_files
  delete_camera_files_1: 'rm /config/camera/deepstack_photo/*'
  delete_camera_files_2: 'rm /config/camera/motion_detected/*'
  delete_camera_files_3: 'rm /config/camera/person/*'
  delete_camera_files_4: 'rm /config/www/motion_detected/*'
  delete_camera_files_5: 'rm /config/www/motion_detected_away/*'
  delete_camera_files_6: 'rm /config/www/motion_detected_away_small/*'