##################
### Automation ###
##################
automation:
  #################################
  ### Processes image mode Away ###
  #################################
  ### - every 3 sec             ###    
  ### - mode Away               ###
  #################################
  - alias: Camera 1 Image processing mode Away
    mode: queued
    
    # Every 3 sec
    trigger:
      - platform: time_pattern
        seconds: "/3"

    # Mode Away
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.camera_mode
          state: 'Away'

    # Scan a new image
    action:
      - service: image_processing.scan
        data:
          entity_id: image_processing.deepstack_camera_1

  ################################
  ### Processes image mode Day ###
  ################################
  ### - every 4 sec            ###
  ### - mode Day               ###
  ################################
  - alias: Camera 1 Image processing mode Day
    mode: queued
    
    # Every 4 sec
    trigger:
      - platform: time_pattern
        seconds: "/4"

    # Mode Day
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.camera_mode
          state: 'Day'

    # Scan a new image
    action:
      - service: image_processing.scan
        data:
          entity_id: image_processing.deepstack_camera_1

  ##################################
  ### Processes image mode Night ###
  ##################################
  ### - every 3 sec              ###    
  ### - mode Night               ###
  ##################################
  - alias: Camera 1 Image processing mode Night
    mode: queued
    
    # Every 3 sec
    trigger:
      - platform: time_pattern
        seconds: "/3"

    # Mode Night
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.camera_mode
          state: 'Night'

    # Scan a new image
    action:
      - service: image_processing.scan
        data:
          entity_id: image_processing.deepstack_camera_1

  ###############################################
  ### Max light huvudentre if person detected ###
  ###############################################
  - alias: Max light huvudentre if person detected
    mode: single
    trigger:
      - platform: state
        entity_id: input_boolean.camera_1_folder_watcher_detected
        to: 'on'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.huvudentre
          state: 'on'

    action:
      - service: light.turn_on
        data:
          entity_id: light.huvudentre
          brightness_pct: 50
          transition: 1
          
  #####################################################
  ### Max light tvättstuga fasad if person detected ###
  #####################################################
  - alias: Max light tvättstuga fasad if person detected
    mode: single
    trigger:
      - platform: state
        entity_id: input_boolean.camera_1_folder_watcher_detected
        to: 'on'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.tvattstuga_fasad
          state: 'on'

    action:
      - service: light.turn_on
        data:
          entity_id: light.tvattstuga_fasad
          brightness_pct: 100
          transition: 1

  ####################################################
  ### Max light friggebod fasad if person detected ###
  ####################################################
  - alias: Max light friggebod fasad if person detected
    mode: single
    trigger:
      - platform: state
        entity_id: input_boolean.camera_1_folder_watcher_detected
        to: 'on'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.friggebod_fasad
          state: 'on'

    action:
      - service: light.turn_on
        data:
          entity_id: light.friggebod_fasad
          brightness_pct: 100
          transition: 1

  #################################################
  ### Max light förråd fasad if person detected ###
  #################################################
  - alias: Max light förråd fasad if person detected
    mode: single

    trigger:
      - platform: state
        entity_id: input_boolean.camera_1_folder_watcher_detected
        to: 'on'
 
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.forrad_fasad
          state: 'on'

    action:
      - service: light.turn_on
        data:
          entity_id: light.forrad_fasad
          brightness_pct: 100
          transition: 1

  #######################################################
  ### Reset light huvudentre when switch from home on ###
  #######################################################
  - alias: Reset light huvudentre when switch from home on
    mode: restart

    trigger:
      - platform: state
        entity_id: input_select.home_status
        from: 'Hemma på'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.huvudentre
          state: 'on'

    action:
      - service: light.turn_on
        data:
          entity_id: light.huvudentre
          brightness_pct: 10
          transition: 1
          
  ##########################################################
  ### Reset light tvättstuga fasad if no person detected ###
  ##########################################################
  - alias: Reset light tvättstuga fasad if person no detected
    mode: restart

    trigger:
      - platform: state
        entity_id: binary_sensor.camera_1_person_detected
        to: 'off'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.tvattstuga_fasad
          state: 'on'

    action:
      - delay:
          seconds: 15

      - service: light.turn_on
        data:
          entity_id: light.tvattstuga_fasad
          brightness_pct: 65
          transition: 1

  #########################################################
  ### Reset light friggebod fasad if no person detected ###
  #########################################################
  - alias: Reset light friggebod fasad if person no detected
    mode: restart

    trigger:
      - platform: state
        entity_id: binary_sensor.camera_1_person_detected
        to: 'off'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.friggebod_fasad
          state: 'on'

    action:
      - delay:
          seconds: 15

      - service: light.turn_on
        data:
          entity_id: light.friggebod_fasad
          brightness_pct: 30
          transition: 1

  ######################################################
  ### Reset light förråd fasad if no person detected ###
  ######################################################
  - alias: Reset light förråd fasad if person no detected
    mode: restart

    trigger:
      - platform: state
        entity_id: binary_sensor.camera_1_person_detected
        to: 'off'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.forrad_fasad
          state: 'on'

    action:
      - delay:
          seconds: 15

      - service: light.turn_on
        data:
          entity_id: light.forrad_fasad
          brightness_pct: 30
          transition: 1

  ######################################
  ### Flash light if person detected ###
  ######################################
  - alias: Flash light if person detected
    mode: single

    trigger:
      - platform: state
        entity_id: input_boolean.camera_1_folder_watcher_detected
        to: 'on'

    action:
      - service: automation.turn_off
        entity_id: automation.flash_light_if_person_detected
        
      - service: light.toggle
        entity_id: light.hall_skap
      - service: light.toggle
        entity_id: light.hall_byra

      - delay:
          seconds: 2

      - service: light.toggle
        entity_id: light.hall_skap
      - service: light.toggle
        entity_id: light.hall_byra
