#####################
### Shell command ###
#####################
shell_command:

  mv_file: "mv -f {{source_file}} {{dest_file}}"

  # Used by automation Camera 1 Person detected create video
  cp_file: "cp -f {{source_file}} {{dest_file}}"

##################
### Automation ###
##################
automation:
  - alias: "Cam color extractor every hour"
    trigger:
      - platform: time_pattern
        hour: 0
      - platform: time_pattern
        hour: 1
      - platform: time_pattern
        hour: 2
      - platform: time_pattern
        hour: 3
      - platform: time_pattern
        hour: 4
      - platform: time_pattern
        hour: 5
      - platform: time_pattern
        hour: 6
      - platform: time_pattern
        hour: 7
      - platform: time_pattern
        hour: 8
      - platform: time_pattern
        hour: 9
      - platform: time_pattern
        hour: 10
      - platform: time_pattern
        hour: 11
      - platform: time_pattern
        hour: 12
      - platform: time_pattern
        hour: 13
      - platform: time_pattern
        hour: 14
      - platform: time_pattern
        hour: 15
      - platform: time_pattern
        hour: 16
      - platform: time_pattern
        hour: 17
      - platform: time_pattern
        hour: 18
      - platform: time_pattern
        hour: 19
      - platform: time_pattern
        hour: 20
      - platform: time_pattern
        hour: 21
      - platform: time_pattern
        hour: 22
      - platform: time_pattern
        hour: 23

    condition:
      condition: and
      conditions:
        - condition: numeric_state
          entity_id: sensor.ljusstyrka
          above: 0

    action:
      - service: camera.snapshot
        target:
          entity_id: camera.kamera1_snapshots
        data:
          filename: '/media/color_extractor/cam_1.jpg'

      - delay: '00:00:01'

      - service: camera.snapshot
        target:
          entity_id: camera.kamera1_snapshots
        data:
          filename: '/media/color_extractor/cam_1_{{ now().strftime("%Y%m%d-%H%") }}.jpg'

      - service: color_extractor.turn_on
        data_template:
          color_extract_path: "/media/color_extractor/cam_1.jpg"
          entity_id: light.cam_1_color
          brightness_pct: 100
###
      - service: camera.snapshot
        target:
          entity_id: camera.kamera2_snapshots
        data:
          filename: '/media/color_extractor/cam_2.jpg'

      - delay: '00:00:01'

      - service: camera.snapshot
        target:
          entity_id: camera.kamera2_snapshots
        data:
          filename: '/media/color_extractor/cam_2_{{ now().strftime("%Y%m%d-%H%") }}.jpg'

      - service: color_extractor.turn_on
        data_template:
          color_extract_path: "/media/color_extractor/cam_2.jpg"
          entity_id: light.cam_2_color
          brightness_pct: 100
###
      - service: camera.snapshot
        target:
          entity_id: camera.kamera3_snapshots
        data:
          filename: '/media/color_extractor/cam_3.jpg'

      - delay: '00:00:01'

      - service: camera.snapshot
        target:
          entity_id: camera.kamera3_snapshots
        data:
          filename: '/media/color_extractor/cam_3_{{ now().strftime("%Y%m%d-%H%") }}.jpg'

      - service: color_extractor.turn_on
        data_template:
          color_extract_path: "/media/color_extractor/cam_3.jpg"
          entity_id: light.cam_3_color
          brightness_pct: 100
###
      - service: camera.snapshot
        target:
          entity_id: camera.kamera4_snapshots
        data:
          filename: '/media/color_extractor/cam_4.jpg'

      - delay: '00:00:01'

      - service: camera.snapshot
        target:
          entity_id: camera.kamera4_snapshots
        data:
          filename: '/media/color_extractor/cam_4_{{ now().strftime("%Y%m%d-%H%") }}.jpg'

      - service: color_extractor.turn_on
        data_template:
          color_extract_path: "/media/color_extractor/cam_4.jpg"
          entity_id: light.cam_4_color
          brightness_pct: 100
##################################################################################################


  - alias: "Cam 1 color extractor"
    trigger:
      - platform: time_pattern
        seconds: "/2"

    action:
      - service: camera.snapshot
        target:
          entity_id: camera.kamera1_snapshots
        data:
#          filename: '/media/color_extractor/cam_1_{{ now().strftime("%Y%m%d-%H%M%S") }}.jpg'
          filename: '/media/color_extractor/cam_1.jpg'
      - delay: '00:00:05'
      - service: color_extractor.turn_on
        data_template:
          color_extract_path: "/media/color_extractor/cam_1.jpg"
          entity_id: light.cam_1_color
          brightness_pct: 100

      - service: automation.turn_off
        entity_id: automation.cam_1_color_extractor

##################################################################################################

  - alias: "Cam 2 color extractor"
    trigger:
      - platform: time_pattern
        seconds: "/2"

    action:
      - service: camera.snapshot
        target:
          entity_id: camera.kamera2_snapshots
        data:
#          filename: '/media/color_extractor/cam_2_{{ now().strftime("%Y%m%d-%H%M%S") }}.jpg'
          filename: '/media/color_extractor/cam_2.jpg'
      - delay: '00:00:05'
      - service: color_extractor.turn_on
        data_template:
          color_extract_path: "/media/color_extractor/cam_2.jpg"
          entity_id: light.cam_2_color
          brightness_pct: 100

      - service: automation.turn_off
        entity_id: automation.cam_2_color_extractor

##################################################################################################

  - alias: "Cam 3 color extractor"
    trigger:
      - platform: time_pattern
        seconds: "/2"

    action:
      - service: camera.snapshot
        target:
          entity_id: camera.kamera3_snapshots
        data:
#          filename: '/media/color_extractor/cam_3_{{ now().strftime("%Y%m%d-%H%M%S") }}.jpg'
          filename: '/media/color_extractor/cam_3.jpg'
      - delay: '00:00:05'
      - service: color_extractor.turn_on
        data_template:
          color_extract_path: "/media/color_extractor/cam_3.jpg"
          entity_id: light.cam_3_color
          brightness_pct: 100

      - service: automation.turn_off
        entity_id: automation.cam_3_color_extractor

##################################################################################################

  - alias: "Cam 4 color extractor"
    trigger:
      - platform: time_pattern
        seconds: "/2"

    action:
      - service: camera.snapshot
        target:
          entity_id: camera.kamera4_snapshots
        data:
#          filename: '/media/color_extractor/cam_4_{{ now().strftime("%Y%m%d-%H%M%S") }}.jpg'
          filename: '/media/color_extractor/cam_4.jpg'
      - delay: '00:00:05'
      - service: color_extractor.turn_on
        data_template:
          color_extract_path: "/media/color_extractor/cam_4.jpg"
          entity_id: light.cam_4_color
          brightness_pct: 100

      - service: automation.turn_off
        entity_id: automation.cam_4_color_extractor
