##################
### AUTOMATION ###
##################
automation:
  ###############################
  ### Keep IKEA Tr책dfri alive ###
  ###############################
  - alias: Keep IKEA Tr책dfri alive
    mode: single

    trigger:
      - minutes: /1
        platform: time_pattern

    action:
      - service_template: light.turn_{{ states('light.vardagsrum_skank') }}
        entity_id: light.vardagsrum_skank

  #################################################
  ### Blinka med lyset n채r uppkopplad till wifi ###
  #################################################
  - alias: Blinka med lyset n채r uppkopplad till wifi
    mode: single

    trigger:
      - platform: state
        entity_id: person.micke
        to: 'home'

    action:
      - service: script.flash_light_garage

##############
### SCRIPT ###
##############
script:
  flash_light_garage:
    alias: Blinka med lyset
    sequence:
      - service: light.toggle
        entity_id: light.forrad_fasad
      - delay:
          seconds: 1

      - service: light.toggle
        entity_id: light.forrad_fasad
      - delay:
          seconds: 1

      - service: light.toggle
        entity_id: light.forrad_fasad
      - delay:
          seconds: 1

      - service: light.toggle
        entity_id: light.forrad_fasad