##################
### Automation ###
##################
automation:
  ###################################
  ### Animal Motion Radio Control ###
  ###################################
- alias: Animal Motion Radio Control
  id: '1416857464463'
  mode: restart  # Allows the automation to reset the timer on new triggers

  trigger:
    # Triggers for occupancy changes
    - platform: state
      entity_id: binary_sensor.cam5_all_occupancy
    - platform: state
      entity_id: binary_sensor.cam6_all_occupancy

  condition: []

  action:
    - choose:
        # When either sensor detects motion
        - conditions:
            - condition: or
              conditions:
                - condition: state
                  entity_id: binary_sensor.cam5_all_occupancy
                  state: 'on'
                - condition: state
                  entity_id: binary_sensor.cam6_all_occupancy
                  state: 'on'
            - condition: numeric_state
              entity_id: sensor.ljusstyrka
              below: 5
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.tradack_ute
        # When both sensors are off
        - conditions:
            - condition: state
              entity_id: binary_sensor.cam5_all_occupancy
              state: 'off'
            - condition: state
              entity_id: binary_sensor.cam6_all_occupancy
              state: 'off'
          sequence:
            - delay: '00:00:30'  # Wait 30 seconds
            - condition: and  # Check if both sensors remain off
              conditions:
                - condition: state
                  entity_id: binary_sensor.cam5_all_occupancy
                  state: 'off'
                - condition: state
                  entity_id: binary_sensor.cam6_all_occupancy
                  state: 'off'
            - service: light.turn_off
              target:
                entity_id: light.tradack_ute

  ###################################
  ### Animal Motion Light Control ###
  ###################################
- alias: Animal Motion Light Control
  id: '1416857464346'
  mode: restart  # Allows the automation to reset the timer on new triggers

  trigger:
    # Triggers for occupancy changes
    - platform: state
      entity_id: binary_sensor.cam5_all_occupancy
    - platform: state
      entity_id: binary_sensor.cam6_all_occupancy

  condition: []

  action:
    - choose:
        # When either sensor detects motion
        - conditions:
            - condition: or
              conditions:
                - condition: state
                  entity_id: binary_sensor.cam5_all_occupancy
                  state: 'on'
                - condition: state
                  entity_id: binary_sensor.cam6_all_occupancy
                  state: 'on'
            - condition: numeric_state
              entity_id: sensor.ljusstyrka
              below: 5
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.stralkastare_husgavel
        # When both sensors are off
        - conditions:
            - condition: state
              entity_id: binary_sensor.cam5_all_occupancy
              state: 'off'
            - condition: state
              entity_id: binary_sensor.cam6_all_occupancy
              state: 'off'
          sequence:
            - delay: '00:00:30'  # Wait 30 seconds
            - condition: and  # Check if both sensors remain off
              conditions:
                - condition: state
                  entity_id: binary_sensor.cam5_all_occupancy
                  state: 'off'
                - condition: state
                  entity_id: binary_sensor.cam6_all_occupancy
                  state: 'off'
            - service: light.turn_off
              target:
                entity_id: light.stralkastare_husgavel

  #####################################
  ### Animal Detection Cam 5 Notify ###
  #####################################
  - alias: Animal Detection Cam 5 Notify
    id: '81119011564329' 
    mode: single

    trigger:
      - platform: state
        entity_id:
          - sensor.cam5_person_count
          - sensor.cam5_bear_count
          - sensor.cam5_cat_count
          - sensor.cam5_cow_count
          - sensor.cam5_dog_count
          - sensor.cam5_elephant_count
          - sensor.cam5_giraffe_count
          - sensor.cam5_horse_count
          - sensor.cam5_sheep_count
          - sensor.cam5_zebra_count
          - sensor.cam6_person_count
          - sensor.cam6_bear_count
          - sensor.cam6_cat_count
          - sensor.cam6_cow_count
          - sensor.cam6_dog_count
          - sensor.cam6_elephant_count
          - sensor.cam6_giraffe_count
          - sensor.cam6_horse_count
          - sensor.cam6_sheep_count
          - sensor.cam6_zebra_count

    condition:
      condition: or
      conditions:
        - condition: time
          after: '21:00:00'
          before: '08:00:00'
        - condition: state
          entity_id: input_select.home_status
          state: 'Borta'
        - condition: numeric_state
          entity_id: sensor.ljusstyrka
          below: 10

    action:
      - service: notify.mobile_app_sm_a528b
        data_template:
          title: >
            "Detection Alert {{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
          message: >
            Camera 5 or 6 has detected. lux: {{ states('sensor.ljusstyrka') | int }}:
            - All:      {{ states('sensor.cam5_all_count') | int }} {{ states('sensor.cam6_all_count') | int }}
            - Person:   {{ states('sensor.cam5_person_count') | int }} {{ states('sensor.cam6_person_count') | int }}
            - Bear:     {{ states('sensor.cam5_bear_count') | int }} {{ states('sensor.cam6_bear_count') | int }}
            - Cow:      {{ states('sensor.cam5_cat_count') | int }} {{ states('sensor.cam6_cat_count') | int }}
            - Dog:      {{ states('sensor.cam5_dog_count') | int }} {{ states('sensor.cam6_dog_count') | int }}
            - Elephant: {{ states('sensor.cam5_elephant_count') | int }} {{ states('sensor.cam6_elephant_count') | int }}
            - Giraffe:  {{ states('sensor.cam5_giraffe_count') | int }} {{ states('sensor.cam6_giraffe_count') | int }}
            - Horse:    {{ states('sensor.cam5_horse_count') | int }} {{ states('sensor.cam6_horse_count') | int }}
            - Sheep:    {{ states('sensor.cam5_sheep_count') | int }} {{ states('sensor.cam6_sheep_count') | int }}
            - Zebra:    {{ states('sensor.cam5_zebra_count') | int }} {{ states('sensor.cam6_zebra_count') | int }}

  #####################################
  ### Animal Detection Cam 5 Notify ###
  #####################################
  - alias: Blink Light When Detcection Cam 5
    id: '81119011512345'
    mode: single

    trigger:
      - platform: numeric_state
        entity_id: sensor.cam5_all_count
        above: 0
      - platform: numeric_state
        entity_id: sensor.cam6_all_count
        above: 0

    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: input_select.home_status
          state: 'Hemma av'
        - condition: state
          entity_id: input_select.home_status
          state: 'Hemma på'

    action:
      - delay: "00:00:01"
      - variables:
          sovrum_initial_state: "{{ is_state('light.sovrum_fonster', 'on') }}"
          hall_initial_state: "{{ is_state('light.hall_byra', 'on') }}"
          vardagsrum_initial_state: "{{ is_state('light.vardagsrum_skank', 'on') }}"

      - repeat:
          while:
            - condition: numeric_state
              entity_id: sensor.cam5_all_count
              above: 0
            - condition: numeric_state
              entity_id: sensor.cam6_all_count
              above: 0
          sequence:
            # Handle light.sovrum_fonster
            - choose:
                - conditions:
                    - condition: template
                      value_template: "{{ sovrum_initial_state }}"
                  sequence:
                    - service: light.turn_off
                      target:
                        entity_id: light.sovrum_fonster
                - conditions:
                    - condition: template
                      value_template: "{{ not sovrum_initial_state }}"
                  sequence:
                    - service: light.turn_on
                      target:
                        entity_id: light.sovrum_fonster
            - delay: "00:00:01"
            - service: light.toggle
              target:
                entity_id: light.sovrum_fonster

            # Handle light.hall_byra
            - choose:
                - conditions:
                    - condition: template
                      value_template: "{{ hall_initial_state }}"
                  sequence:
                    - service: light.turn_off
                      target:
                        entity_id: light.hall_byra
                - conditions:
                    - condition: template
                      value_template: "{{ not hall_initial_state }}"
                  sequence:
                    - service: light.turn_on
                      target:
                        entity_id: light.hall_byra
            - delay: "00:00:01"
            - service: light.toggle
              target:
                entity_id: light.hall_byra

            # Handle light.vardagsrum_skank
            - choose:
                - conditions:
                    - condition: template
                      value_template: "{{ vardagsrum_initial_state }}"
                  sequence:
                    - service: light.turn_off
                      target:
                        entity_id: light.vardagsrum_skank
                - conditions:
                    - condition: template
                      value_template: "{{ not vardagsrum_initial_state }}"
                  sequence:
                    - service: light.turn_on
                      target:
                        entity_id: light.vardagsrum_skank
            - delay: "00:00:01"
            - service: light.toggle
              target:
                entity_id: light.vardagsrum_skank

            - delay: "00:00:01"

      # Restore lights to their initial states
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ sovrum_initial_state }}"
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.sovrum_fonster
          - conditions:
              - condition: template
                value_template: "{{ not sovrum_initial_state }}"
            sequence:
              - service: light.turn_off
                target:
                  entity_id: light.sovrum_fonster

      - choose:
          - conditions:
              - condition: template
                value_template: "{{ hall_initial_state }}"
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.hall_byra
          - conditions:
              - condition: template
                value_template: "{{ not hall_initial_state }}"
            sequence:
              - service: light.turn_off
                target:
                  entity_id: light.hall_byra

      - choose:
          - conditions:
              - condition: template
                value_template: "{{ vardagsrum_initial_state }}"
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.vardagsrum_skank
          - conditions:
              - condition: template
                value_template: "{{ not vardagsrum_initial_state }}"
            sequence:
              - service: light.turn_off
                target:
                  entity_id: light.vardagsrum_skank
