#####################
### Binary Sensor ###
#####################
binary_sensor:
  - platform: template
    sensors:
      object_detected:
        friendly_name: "Objekt detekterat"
        value_template: >-
          {{ is_state('binary_sensor.cam5_all_occupancy', 'on') or is_state('binary_sensor.cam7_all_occupancy', 'on') }}
        device_class: motion

##################
### Automation ###
##################
automation:
  ##############################
  ### Animal Motion Light on ###
  ##############################
  - alias: Animal Motion Light on 
    id: '1416857464436' 
    mode: single

    trigger:
      - platform: state
        entity_id: binary_sensor.object_detected
        to: 'on'

    condition:
      condition: and
      conditions:
        - condition: numeric_state
          entity_id: sensor.ljusstyrka
          below: 5

    action:
      - service: light.turn_on
        target:
          entity_id: light.stralkastare_husgavel

  ###############################
  ### Animal Motion Light off ###
  ###############################
  - alias: Animal Motion Light off 
    id: '1415557464436' 
    mode: single

    trigger:
      - platform: state
        entity_id: binary_sensor.object_detected
        to: 'off'

    conditions:
      - condition: state
        entity_id: light.stralkastare_husgavel
        state: 'on'

    action:
      - service: light.turn_off
        target:
          entity_id: light.stralkastare_husgavel

  #####################################
  ### Animal Detection Cam 5 Notify ###
  #####################################
  - alias: Animal Detection Cam 5 Notify
    id: '81119011564329' 
    mode: single

    trigger:
      - platform: numeric_state
        entity_id:
          - sensor.cam5_all_count
        above: 0

    condition:
      condition: and
      conditions:
        - condition: time
          after: '21:00:00'
          before: '08:00:00'
        - condition: or
          conditions:
            - condition: state
              entity_id: input_select.home_status
              state: 'Borta'

    action:
      - service: notify.mobile_app_sm_a528b
        data_template:
          title: >
            "Detection Alert {{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
          message: >
            Camera 5 has detected:
            - All:      {{ states('sensor.cam5_all_count') | int }}
            - Person:   {{ states('sensor.cam5_person_count') | int }}
            - Bear:     {{ states('sensor.cam5_bear_count') | int }}
            - Bird:     {{ states('sensor.cam5_bird_count') | int }}
            - Cow:      {{ states('sensor.cam5_cat_count') | int }}
            - Dog:      {{ states('sensor.cam5_dog_count') | int }}
            - Elephant: {{ states('sensor.cam5_elephant_count') | int }}
            - Giraffe:  {{ states('sensor.cam5_giraffe_count') | int }}
            - Horse:    {{ states('sensor.cam5_horse_count') | int }}
            - Sheep:    {{ states('sensor.cam5_sheep_count') | int }}
            - Zebra:    {{ states('sensor.cam5_zebra_count') | int }}

  #####################################
  ### Animal Detection Cam 7 Notify ###
  #####################################
  - alias: Animal Detection Cam 7 Notify
    id: '81119011764329' 
    mode: single

    trigger:
      - platform: numeric_state
        entity_id:
          - sensor.cam7_all_count
        above: 0

    condition:
      condition: and
      conditions:
        - condition: time
          after: '21:00:00'
          before: '08:00:00'
        - condition: or
          conditions:
            - condition: state
              entity_id: input_select.home_status
              state: 'Borta'

    action:
      - service: notify.mobile_app_sm_a528b
        data_template:
          title: >
            "Detection Alert {{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
          message: >
            Camera 7 has detected:
            - All:      {{ states('sensor.cam7_all_count') | int }}
            - Person:   {{ states('sensor.cam7_person_count') | int }}
            - Bear:     {{ states('sensor.cam7_bear_count') | int }}
            - Bird:     {{ states('sensor.cam7_bird_count') | int }}
            - Cow:      {{ states('sensor.cam7_cat_count') | int }}
            - Dog:      {{ states('sensor.cam7_dog_count') | int }}
            - Elephant: {{ states('sensor.cam7_elephant_count') | int }}
            - Giraffe:  {{ states('sensor.cam7_giraffe_count') | int }}
            - Horse:    {{ states('sensor.cam7_horse_count') | int }}
            - Sheep:    {{ states('sensor.cam7_sheep_count') | int }}
            - Zebra:    {{ states('sensor.cam7_zebra_count') | int }}
