##################
### Automation ###
##################
automation:
  - alias: Person Detection Notify
    id: '81119011564368'
    mode: single

    trigger:
      - platform: state
        entity_id: 
          - binary_sensor.cams_person_active
        to: 'on'

    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: input_select.home_status
          state: 'Borta'
        - condition: state
          entity_id: input_select.home_status
          state: 'Hemma av'

    action:
      - choose:
          # If home_status is 'Borta', add a delay and re-check the state
          - conditions:
              - condition: state
                entity_id: input_select.home_status
                state: 'Borta'
            sequence:
              - delay: "00:03:00"
              - condition: state
                entity_id: input_select.home_status
                state: 'Borta'
              - service: notify.mobile_app_sm_a528b
                data_template:
                  title: >
                    "Person Detection Away Alert {{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
                  message: >
                    Person detected 3 minutes ago:
                    - Cam 3 Uppfart: {{ states('sensor.cam3_person_count') | int }}
                    - Cam 5 Baksida: {{ states('sensor.cam5_person_count') | int }}
                    - Cam 6 Baksida: {{ states('sensor.cam6_person_count') | int }}
                    - Cam 7 Frigge:  {{ states('sensor.cam7_person_count') | int }}
                    - Cam 8 Entre:   {{ states('sensor.cam8_person_count') | int }}
          # If home_status is 'Hemma av', send the notification immediately
          - conditions:
              - condition: state
                entity_id: input_select.home_status
                state: 'Hemma av'
            sequence:
              - service: notify.mobile_app_sm_a528b
                data_template:
                  title: >
                    "Person Detection Sleep Alert {{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
                  message: >
                    Person detected:
                    - Cam 3 Uppfart: {{ states('sensor.cam3_person_count') | int }}
                    - Cam 5 Baksida: {{ states('sensor.cam5_person_count') | int }}
                    - Cam 6 Baksida: {{ states('sensor.cam6_person_count') | int }}
                    - Cam 7 Frigge:  {{ states('sensor.cam7_person_count') | int }}
                    - Cam 8 Entre:   {{ states('sensor.cam8_person_count') | int }}

  ####################################
  ### Blink Light Person Detcected ###
  ####################################
  - alias: Blink Light Person Detected
    id: '81119011512349'
    mode: single

    trigger:
      # Triggers for person detection
      - platform: state
        entity_id: 
          - binary_sensor.cams_person_active
        to: 'on'

    action:
      - variables:
          blink_count: 6
          blink_delay: '00:00:01'

      - repeat:
          count: "{{ blink_count }}"
          sequence:
            - service: light.toggle
              target:
                entity_id:
                  - light.sovrum_fonster
                  - light.hall_byra
                  - light.vardagsrum_skank
            - delay: "{{ blink_delay }}"
