shell_command:
  copy_frigate_config: "cp /share/frigate_config.yaml /config/frigate/config.yaml"
  sanitize_frigate_config: "/config/frigate/sanitize.sh"
  git_sync_frigate_config: "/config/frigate/git-sync.sh"

automation:
  - alias: "Sync Frigate config to Git repo"
    trigger:
      - platform: time
#        at: "03:00:00"
        at: "09:36:00"
      - platform: state
        entity_id: addon.ccab4aaf_frigate
        to: "on"
    action:
      - service: hassio.addon_stdin
        data:
          addon: ccab4aaf_frigate
          input: "cp /config/config.yaml /share/frigate_config.yaml"

      - service: shell_command.copy_frigate_config

  - alias: "Update sanitized Frigate template"
    trigger:
      - platform: time
#        at: "03:05:00"
        at: "09:37:00"
    action:
      - service: shell_command.sanitize_frigate_config

#  - alias: "Sync Frigate config to Git repo"
#    trigger:
#      - platform: time
#        at: "03:00:10"
#      - platform: state
#        entity_id: addon.ccab4aaf_frigate
#        to: "on"
#    action:
#      - service: shell_command.git_sync_frigate_config


