##################
### Automation ###
##################
automation:
  - alias: Person Detection Notify
    id: '81119011564368'
    mode: single

    trigger:
      - platform: state
        entity_id: 
          - binary_sensor.cams_person_active
        to: 'on'

    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: input_select.home_status
          state: 'Borta'
        - condition: state
          entity_id: input_select.home_status
          state: 'Hemma av'

    action:
      - choose:
          # If home_status is 'Borta', add a delay and re-check the state
          - conditions:
              - condition: state
                entity_id: input_select.home_status
                state: 'Borta'
            sequence:
              - delay: "00:03:00"
              - condition: state
                entity_id: input_select.home_status
                state: 'Borta'
              - service: notify.mobile_app_sm_a528b
                data_template:
                  title: >
                    "Person Detection Away Alert {{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
                  message: >
                    Person detected 3 minutes ago:
                    - Cam 3 Uppfart: {{ states('sensor.cam3_person_count') | int }}
                    - Cam 5 Baksida: {{ states('sensor.cam5_person_count') | int }}
                    - Cam 6 Baksida: {{ states('sensor.cam6_person_count') | int }}
                    - Cam 7 Frigge:  {{ states('sensor.cam7_person_count') | int }}
                    - Cam 8 Entre:   {{ states('sensor.cam8_person_count') | int }}
          # If home_status is 'Hemma av', send the notification immediately
          - conditions:
              - condition: state
                entity_id: input_select.home_status
                state: 'Hemma av'
            sequence:
              - service: notify.mobile_app_sm_a528b
                data_template:
                  title: >
                    "Person Detection Sleep Alert {{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
                  message: >
                    Person detected:
                    - Cam 3 Uppfart: {{ states('sensor.cam3_person_count') | int }}
                    - Cam 5 Baksida: {{ states('sensor.cam5_person_count') | int }}
                    - Cam 6 Baksida: {{ states('sensor.cam6_person_count') | int }}
                    - Cam 7 Frigge:  {{ states('sensor.cam7_person_count') | int }}
                    - Cam 8 Entre:   {{ states('sensor.cam8_person_count') | int }}

  ####################################
  ### Blink Light Person Detcected ###
  ####################################
  - alias: Blink Light Person Detected
    id: '81119011512349'
    mode: single

    trigger:
      # Triggers for person detection
      - platform: state
        entity_id: 
          - binary_sensor.cams_person_active
        to: 'on'

    action:
      - variables:
          sovrum_initial_state: "{{ is_state('light.sovrum_fonster', 'on') }}"
          hall_initial_state: "{{ is_state('light.hall_byra', 'on') }}"
          vardagsrum_initial_state: "{{ is_state('light.vardagsrum_skank', 'on') }}"

      - service: automation.turn_off
        entity_id: automation.blink_light_person_detected

      - repeat:
          count: 5

          sequence:

            # Handle light.sovrum_fonster            
            - choose:
                - conditions:
                    - condition: template
                      value_template: "{{ sovrum_initial_state }}"
                  sequence:
                    - service: light.turn_off
                      target:
                        entity_id: light.sovrum_fonster
                - conditions:
                    - condition: template
                      value_template: "{{ not sovrum_initial_state }}"
                  sequence:
                    - service: light.turn_on
                      target:
                        entity_id: light.sovrum_fonster

            # Handle light.hall_byra
            - choose:
                - conditions:
                    - condition: template
                      value_template: "{{ hall_initial_state }}"
                  sequence:
                    - service: light.turn_off
                      target:
                        entity_id: light.hall_byra
                - conditions:
                    - condition: template
                      value_template: "{{ not hall_initial_state }}"
                  sequence:
                    - service: light.turn_on
                      target:
                        entity_id: light.hall_byra

            # Handle light.vardagsrum_skank
            - choose:
                - conditions:
                    - condition: template
                      value_template: "{{ vardagsrum_initial_state }}"
                  sequence:
                    - service: light.turn_off
                      target:
                        entity_id: light.vardagsrum_skank
                - conditions:
                    - condition: template
                      value_template: "{{ not vardagsrum_initial_state }}"
                  sequence:
                    - service: light.turn_on
                      target:
                        entity_id: light.vardagsrum_skank


            - delay: "00:00:01"

            - service: light.toggle
              target:
                entity_id: light.sovrum_fonster
            - service: light.toggle
              target:
                entity_id: light.hall_byra
            - service: light.toggle
              target:
                entity_id: light.vardagsrum_skank

            - delay: "00:00:01"

      # Restore lights to their initial states
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ sovrum_initial_state }}"
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.sovrum_fonster
          - conditions:
              - condition: template
                value_template: "{{ not sovrum_initial_state }}"
            sequence:
              - service: light.turn_off
                target:
                  entity_id: light.sovrum_fonster

      - choose:
          - conditions:
              - condition: template
                value_template: "{{ hall_initial_state }}"
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.hall_byra
          - conditions:
              - condition: template
                value_template: "{{ not hall_initial_state }}"
            sequence:
              - service: light.turn_off
                target:
                  entity_id: light.hall_byra

      - choose:
          - conditions:
              - condition: template
                value_template: "{{ vardagsrum_initial_state }}"
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.vardagsrum_skank
          - conditions:
              - condition: template
                value_template: "{{ not vardagsrum_initial_state }}"
            sequence:
              - service: light.turn_off
                target:
                  entity_id: light.vardagsrum_skank