remote:
  - platform: harmony
    name: Harmony Hub
    host: 192.168.1.247
    activity: Watch TV

group:
  harmony:
    name: Mediaspelare 
    view: yes
#    icon: mdi:information-outline
    entities:
      - group.mediaplayer

  mediaplayer:
    name: Fjärrkontroll
    view: no
#    icon: mdi:information-outline
    entities:
      - sensor.harmony_current
      - script.harmony_off
      - script.harmony_tv
      - script.harmony_radio
      - script.harmony_chromecast
      - script.harmony_spotify
      - media_player.chromecast
      - media_player.rxa1030_a47cf6

sensor:
  - platform: template
    sensors:
      harmony_current:
        value_template: '{{ states.remote.harmony_hub.attributes.current_activity }}'
        friendly_name: 'Aktuell aktivitet' 

script:
  harmony_off:
    alias: Harmony, stäng av allt
    sequence:
      - service: remote.turn_off
        entity_id: remote.harmony_hub

  harmony_radio:
    alias: Starta radio
    sequence:
      - service: remote.turn_on
        entity_id: remote.harmony_hub
        data:
          activity: '31360209'

  harmony_tv:
    alias: Starta Tv
    sequence:
      - service: remote.turn_on
        entity_id: remote.harmony_hub
        data:
          activity: '31360159'

  harmony_chromecast:
    alias: Starta ChromeCast
    sequence:
      - service: remote.turn_on
        entity_id: remote.harmony_hub
        data:
          activity: '31360285'

  harmony_spotify:
    alias: Starta Spotify
    sequence:
      - service: remote.turn_on
        entity_id: remote.harmony_hub
        data:
          activity: '31360307'

automation:
    ###############################################
    ### Stäng av subbasar vid PowerOff          ###
    ### T: remote.harmony_hub                   ###
    ### C: to current_activity == "PowerOff"    ###
    ###    switch.vardagsrum_subbas = on        ###
    ### A: switch.vardagsrum_subbas = off       ###
    ###    switch.vardagsrum_extra_subbas = off ###
    ###############################################
  - alias: "Stäng av subbasar vid PowerOff"
    trigger:
      platform: state
      entity_id: remote.harmony_hub
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{{ trigger.to_state.attributes.current_activity == "PowerOff" }}'
        - condition: state
          entity_id: switch.vardagsrum_subbas
          state: 'on'
    action:
      - service: homeassistant.turn_off
        entity_id: switch.vardagsrum_subbas
      - service: homeassistant.turn_off
        entity_id: switch.vardagsrum_extra_subbas

    #########################################################################
    ### Sätt på subbasar vid PowerOn                                      ###
    ### T: remote.harmony_hub                                             ###
    ### C: to current_activity == "Watch TV"                              ###
    ###    or to current_activity == "Watch ChromeCast"                   ###
    ###    or to current_activity == "Listen to Radio"                    ###
    ###    or to current_activity == "Listen to Spotify"                  ###
    ### A: switch.vardagsrum_subbas = on                                  ###
    ###    switch.vardagsrum_extra_subbas = on                            ###
    #########################################################################
  - alias: "Sätt på subbasar vid PowerOn"
    trigger:
      platform: state
      entity_id: remote.harmony_hub
    condition:
      condition: or
      conditions:
        - condition: template
          value_template: '{{ trigger.to_state.attributes.current_activity == "Watch TV" }}'
        - condition: template
          value_template: '{{ trigger.to_state.attributes.current_activity == "Watch ChromeCast" }}'
        - condition: template
          value_template: '{{ trigger.to_state.attributes.current_activity == "Listen to Radio" }}'
        - condition: template
          value_template: '{{ trigger.to_state.attributes.current_activity == "Listen to Spotify" }}'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.vardagsrum_subbas
      - service: homeassistant.turn_on
        entity_id: switch.vardagsrum_extra_subbas

    ##################################################################
    ### Sätt på mediaspelare om off                                ###
    ### En extra kontroll görs ifall påslag inte tidigare fungerat ###
    ### T: remote.harmony_hub                                      ###
    ### C: current_activity == "Watch TV"                          ###
    ###    sensor.yamaha == offline                                ###
    ###    switch.vardagsrum_stereobank = off                      ###
    ### A: switch.vardagsrum_stereobank = on                       ###
    ###    switch.vardagsrum_tv = on                               ###
    ##################################################################
    #
    # Do not use!!!
    #
  # - alias: "Sätt på mediaspelare om off"
    # initial_state: 'off'
    # trigger:
      # platform: state
      # entity_id: remote.harmony_hub
    # condition:
      # condition: and
      # conditions:
        # - condition: template
          # value_template: '{{ trigger.to_state.attributes.current_activity == "Watch TV" }}'
        # - condition: state
          # entity_id: sensor.yamaha
          # state: 'Offline'
        # - condition: state
          # entity_id: switch.vardagsrum_stereobank
          # state: 'off'
    # action:
      # - service: homeassistant.turn_on
        # entity_id: switch.vardagsrum_stereobank
      # - service: homeassistant.turn_on
        # entity_id: switch.vardagsrum_tv

    #############################################
    ### Stäng av mediaspelare vid PowerOff    ###
    ### T: remote.harmony_hub                 ###
    ### C: current_activity == "PowerOff"     ###
    ### A: switch.vardagsrum_stereobank = off ###
    ###    switch.vardagsrum_tv = off         ###
    #############################################
  # - alias: "Stäng av mediaspelare vid PowerOff"
    # initial_state: 'off'
    # trigger:
      # platform: state
      # entity_id: remote.harmony_hub
    # condition:
      # condition: template
      # value_template: '{{ trigger.to_state.attributes.current_activity == "PowerOff" }}'
    # action:
      # - delay: '00:00:10'
      # - service: homeassistant.turn_off
        # entity_id: switch.vardagsrum_stereobank
      # - service: homeassistant.turn_off
        # entity_id: switch.vardagsrum_tv

    ##############################################
    ### Sätt på mediaspelare vid Watch TV      ###
    ### T: remote.harmony_hub                  ###
    ### C: from current_activity == "PowerOff" ###
    ###    to   current_activity == "Watch TV" ###
    ###    switch.vardagsrum_stereobank = off  ###
    ### A: switch.vardagsrum_extra_subbas = on ###
    ##############################################
  - alias: "Sätt på mediaspelare vid Watch TV"
    trigger:
      platform: state
      entity_id: remote.harmony_hub
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{{ trigger.from_state.attributes.current_activity == "PowerOff" }}'
        - condition: template
          value_template: '{{ trigger.to_state.attributes.current_activity == "Watch TV" }}'
        - condition: state
          entity_id: switch.vardagsrum_stereobank
          state: 'off'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.vardagsrum_stereobank
      - service: homeassistant.turn_on
        entity_id: switch.vardagsrum_tv
      - delay: '00:00:05'
      - service: script.harmony_off
      - delay: '00:00:05'
      - service: script.harmony_tv

    #####################################################
    ### Sätt på mediaspelare vid Listen to Radio      ###
    ### T: remote.harmony_hub                         ###
    ### C: from current_activity == "PowerOff"        ###
    ###    to   current_activity == "Listen to Radio" ###
    ###    switch.vardagsrum_stereobank = off         ###
    ### A: switch.vardagsrum_extra_subbas = on        ###
    #####################################################
  - alias: "Sätt på mediaspelare vid Listen to Radio"
    trigger:
      platform: state
      entity_id: remote.harmony_hub
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{{ trigger.from_state.attributes.current_activity == "PowerOff" }}'
        - condition: template
          value_template: '{{ trigger.to_state.attributes.current_activity == "Listen to Radio" }}'
        - condition: state
          entity_id: switch.vardagsrum_stereobank
          state: 'off'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.vardagsrum_stereobank
      - service: homeassistant.turn_on
        entity_id: switch.vardagsrum_tv
      - delay: '00:00:05'
      - service: script.harmony_off
      - delay: '00:00:25'
      - service: script.harmony_radio

    ######################################################
    ### Sätt på mediaspelare vid Watch ChromeCast      ###
    ### T: remote.harmony_hub                          ###
    ### C: from current_activity == "PowerOff"         ###
    ###    to   current_activity == "Watch ChromeCast" ###
    ###    switch.vardagsrum_stereobank = off          ###
    ### A: switch.vardagsrum_extra_subbas = on         ###
    ######################################################
  - alias: "Sätt på mediaspelare vid Watch ChromeCast"
    trigger:
      platform: state
      entity_id: remote.harmony_hub
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{{ trigger.from_state.attributes.current_activity == "PowerOff" }}'
        - condition: template
          value_template: '{{ trigger.to_state.attributes.current_activity == "Watch ChromeCast" }}'
        - condition: state
          entity_id: switch.vardagsrum_stereobank
          state: 'off'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.vardagsrum_stereobank
      - service: homeassistant.turn_on
        entity_id: switch.vardagsrum_tv
      - delay: '00:00:05'
      - service: script.harmony_off
      - delay: '00:00:05'
      - service: script.harmony_chromecast

    #######################################################
    ### Sätt på mediaspelare vid Listen to Spotify      ###
    ### T: remote.harmony_hub                           ###
    ### C: from current_activity == "PowerOff"          ###
    ###    to   current_activity == "Listen to Spotify" ###
    ###    switch.vardagsrum_stereobank = off           ###
    ### A: switch.vardagsrum_extra_subbas = on          ###
    #######################################################
  - alias: "Sätt på mediaspelare vid Listen to Spotify"
    trigger:
      platform: state
      entity_id: remote.harmony_hub
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{{ trigger.from_state.attributes.current_activity == "PowerOff" }}'
        - condition: template
          value_template: '{{ trigger.to_state.attributes.current_activity == "Listen to Spotify" }}'
        - condition: state
          entity_id: switch.vardagsrum_stereobank
          state: 'off'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.vardagsrum_stereobank
      - service: homeassistant.turn_on
        entity_id: switch.vardagsrum_tv
      - delay: '00:00:05'
      - service: script.harmony_off
      - delay: '00:00:05'
      - service: script.harmony_spotify
