automation:
    ##################################################
    ### Stäng av mediaspelare vid mediaspelare off ###
    ### T: remote.harmony_hub                      ###
    ### C: current_activity == "PowerOff"          ###
    ### A: switch.vardagsrum_stereobank = off      ###
    ###    switch.vardagsrum_tv = off              ###
    ##################################################
  - alias: "Stäng av mediaspelare vid mediaspelare off"
    initial_state: 'off'
    trigger:
      platform: state
      entity_id: remote.harmony_hub
    condition:
      condition: template
      value_template: '{{ trigger.to_state.attributes.current_activity == "PowerOff" }}'
    action:
      - delay: '00:00:10'
      - service: homeassistant.turn_off
        entity_id: switch.vardagsrum_stereobank
      - service: homeassistant.turn_off
        entity_id: switch.vardagsrum_tv

    ################################################
    ### Sätt på mediaspelare vid mediaspelare on ###
    ### T: remote.harmony_hub                    ###
    ### C: current_activity != "PowerOff"        ###
    ###    switch.vardagsrum_stereobank = off    ###
    ###    switch.vardagsrum_extra_subbas = on   ###
    ################################################
  - alias: "Sätt på mediaspelare vid mediaspelare on"
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: remote.harmony_hub
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{{ trigger.to_state.attributes.current_activity != "PowerOff" }}'
        - condition: state
          entity_id: switch.vardagsrum_stereobank
          state: 'off'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.vardagsrum_stereobank
      - service: homeassistant.turn_on
        entity_id: switch.vardagsrum_tv
#      - delay: '00:00:30'
#      - service: remote.turn_on
#        entity_id: remote.harmony_hub
#        data:
#          activity: '{{ states.remote.harmony_hub.attributes.current_activity }}'
#      - service: notify.pushbullet
#        data:
#          message: '{{ states.remote.harmony_hub.attributes.current_activity }}'
