remote:
  - platform: harmony
    name: Harmony Hub
    host: 192.168.1.23
    activity: Watch TV

sensor:
  - platform: template
    sensors:
      harmony_current:
        value_template: '{{ states.remote.harmony_hub.attributes.current_activity }}'
        friendly_name: 'Aktuell aktivitet' 

  - platform: template
    sensors:
      yamaha_volume_level:
        value_template: '{{ states.media_player.yamaha_receiver.attributes.volume_level }}'
        friendly_name: 'Yamaha volym' 

script:
  harmony_off:
    alias: Harmony, stäng av allt
    sequence:
#      - service: remote.send_command
#        data: 
#          entity_id: remote.harmony_hub
#          command:
#            - PowerOff
#          device: 51581499 # Panasonic TV
#          delay_secs: 0.6
#      - service: remote.send_command
#        data: 
#          entity_id: remote.harmony_hub
#          command:
#            - PowerToggle
#          device: 51581556 # CanalDigital SAT
#          delay_secs: 0.6
#      - service: remote.send_command
#        data: 
#          entity_id: remote.harmony_hub
#          command:
#            - PowerOff
#          device: 51581386 # RX-A1030 A47CF6
#          delay_secs: 0.6          
      - service: remote.turn_on
        entity_id: remote.harmony_hub
        data:
          activity: '-1'
      - delay: '00:00:05'
      - service: remote.turn_off
        entity_id: remote.harmony_hub

  harmony_radio:
    alias: Starta radio
    sequence:
      - service: remote.turn_on
        entity_id: remote.harmony_hub
        data:
          activity: '31360209'

  harmony_tv:
    alias: Starta Tv
    sequence:
      - service: remote.turn_on
        entity_id: remote.harmony_hub
        data:
          activity: '31360159'

  harmony_chromecast:
    alias: Starta ChromeCast
    sequence:
      - service: remote.turn_on
        entity_id: remote.harmony_hub
        data:
          activity: '31360285'

  harmony_spotify:
    alias: Starta Spotify
    sequence:
      - service: remote.turn_on
        entity_id: remote.harmony_hub
        data:
          activity: '31360307'

  harmony_chromecast_ultra:
    alias: Starta ChromeCast ultra
    sequence:
      - service: remote.turn_on
        entity_id: remote.harmony_hub
        data:
          activity: '42811819'

  harmony_chromecast_ultra_listen:
    alias: Starta Chromecast ultra radio
    sequence:
      - service: remote.turn_on
        entity_id: remote.harmony_hub
        data:
          activity: '42812128'
automation:
    ###############################################
    ### Stäng av subbasar vid PowerOff          ###
    ### T: remote.harmony_hub                   ###
    ### C: to current_activity == "PowerOff"    ###
    ###    switch.vardagsrum_subbas = on        ###
    ### A: switch.vardagsrum_subbas = off       ###
    ###    switch.vardagsrum_extra_subbas = off ###
    ###############################################
  - alias: "Stäng av subbasar vid PowerOff"
    trigger:
      platform: state
      entity_id: remote.harmony_hub
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{{ trigger.to_state.attributes.current_activity == "PowerOff" }}'
        - condition: state
          entity_id: switch.vardagsrum_subbas
          state: 'on'
    action:
      - service: homeassistant.turn_off
        entity_id: switch.vardagsrum_subbas
      - service: homeassistant.turn_off
        entity_id: switch.vardagsrum_extra_subbas

    #########################################################################
    ### Sätt på subbasar vid PowerOn                                      ###
    ### T: remote.harmony_hub                                             ###
    ### C: to current_activity == "Watch TV"                              ###
    ###    or to current_activity == "Watch ChromeCast"                   ###
    ###    or to current_activity == "Listen to Radio"                    ###
    ###    or to current_activity == "Listen to Spotify"                  ###
    ###    or to current_activity == "Watch ChromeCast ultra"             ###
    ###    or to current_activity == "Listen to ChromeCast ultra"         ###
    ### A: switch.vardagsrum_subbas = on                                  ###
    ###    switch.vardagsrum_extra_subbas = on                            ###
    #########################################################################
  - alias: "Sätt på subbasar vid PowerOn"
    trigger:
      platform: state
      entity_id: remote.harmony_hub
    condition:
      condition: or
      conditions:
        - condition: template
          value_template: '{{ trigger.to_state.attributes.current_activity == "Watch TV" }}'
        - condition: template
          value_template: '{{ trigger.to_state.attributes.current_activity == "Watch ChromeCast" }}'
        - condition: template
          value_template: '{{ trigger.to_state.attributes.current_activity == "Listen to Radio" }}'
        - condition: template
          value_template: '{{ trigger.to_state.attributes.current_activity == "Listen to Spotify" }}'
        - condition: template
          value_template: '{{ trigger.to_state.attributes.current_activity == "Watch ChromeCast ultra" }}'
        - condition: template
          value_template: '{{ trigger.to_state.attributes.current_activity == "Listen to ChromeCast ultra" }}'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.vardagsrum_subbas
      - service: homeassistant.turn_on
        entity_id: switch.vardagsrum_extra_subbas

    ##################################################################
    ### Sätt på mediaspelare om off                                ###
    ### En extra kontroll görs ifall påslag inte tidigare fungerat ###
    ### T: remote.harmony_hub                                      ###
    ### C: current_activity == "Watch TV"                          ###
    ###    sensor.yamaha == offline                                ###
    ###    switch.vardagsrum_stereobank = off                      ###
    ### A: switch.vardagsrum_stereobank = on                       ###
    ###    switch.vardagsrum_tv = on                               ###
    ##################################################################
    #
    # Do not use!!!
    #
  # - alias: "Sätt på mediaspelare om off"
    # initial_state: 'off'
    # trigger:
      # platform: state
      # entity_id: remote.harmony_hub
    # condition:
      # condition: and
      # conditions:
        # - condition: template
          # value_template: '{{ trigger.to_state.attributes.current_activity == "Watch TV" }}'
        # - condition: state
          # entity_id: sensor.yamaha
          # state: 'Offline'
        # - condition: state
          # entity_id: switch.vardagsrum_stereobank
          # state: 'off'
    # action:
      # - service: homeassistant.turn_on
        # entity_id: switch.vardagsrum_stereobank
      # - service: homeassistant.turn_on
        # entity_id: switch.vardagsrum_tv

    #############################################
    ### Stäng av mediaspelare vid PowerOff    ###
    ### T: remote.harmony_hub                 ###
    ### C: current_activity == "PowerOff"     ###
    ### A: switch.vardagsrum_stereobank = off ###
    ###    switch.vardagsrum_tv = off         ###
    #############################################
  # - alias: "Stäng av mediaspelare vid PowerOff"
    # initial_state: 'off'
    # trigger:
      # platform: state
      # entity_id: remote.harmony_hub
    # condition:
      # condition: template
      # value_template: '{{ trigger.to_state.attributes.current_activity == "PowerOff" }}'
    # action:
      # - delay: '00:00:10'
      # - service: homeassistant.turn_off
        # entity_id: switch.vardagsrum_stereobank
      # - service: homeassistant.turn_off
        # entity_id: switch.vardagsrum_tv

    ##############################################
    ### Sätt på mediaspelare vid Watch TV      ###
    ### T: remote.harmony_hub                  ###
    ### C: from current_activity == "PowerOff" ###
    ###    to   current_activity == "Watch TV" ###
    ###    switch.vardagsrum_stereobank = off  ###
    ### A: switch.vardagsrum_extra_subbas = on ###
    ##############################################
  - alias: "Sätt på mediaspelare vid Watch TV"
    trigger:
      platform: state
      entity_id: remote.harmony_hub
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{{ trigger.from_state.attributes.current_activity == "PowerOff" }}'
        - condition: template
          value_template: '{{ trigger.to_state.attributes.current_activity == "Watch TV" }}'
        - condition: state
          entity_id: switch.vardagsrum_stereobank
          state: 'off'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.vardagsrum_stereobank
      - service: homeassistant.turn_on
        entity_id: switch.vardagsrum_tv
      - delay: '00:00:05'
      - service: script.harmony_off
      - delay: '00:00:05'
      - service: script.harmony_tv

    #####################################################
    ### Sätt på mediaspelare vid Listen to Radio      ###
    ### T: remote.harmony_hub                         ###
    ### C: from current_activity == "PowerOff"        ###
    ###    to   current_activity == "Listen to Radio" ###
    ###    switch.vardagsrum_stereobank = off         ###
    ### A: switch.vardagsrum_extra_subbas = on        ###
    #####################################################
  - alias: "Sätt på mediaspelare vid Listen to Radio"
    trigger:
      platform: state
      entity_id: remote.harmony_hub
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{{ trigger.from_state.attributes.current_activity == "PowerOff" }}'
        - condition: template
          value_template: '{{ trigger.to_state.attributes.current_activity == "Listen to Radio" }}'
        - condition: state
          entity_id: switch.vardagsrum_stereobank
          state: 'off'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.vardagsrum_stereobank
      - service: homeassistant.turn_on
        entity_id: switch.vardagsrum_tv
      - delay: '00:00:05'
      - service: script.harmony_off
      - delay: '00:00:25'
      - service: script.harmony_radio

    ######################################################
    ### Sätt på mediaspelare vid Watch ChromeCast      ###
    ### T: remote.harmony_hub                          ###
    ### C: from current_activity == "PowerOff"         ###
    ###    to   current_activity == "Watch ChromeCast" ###
    ###    switch.vardagsrum_stereobank = off          ###
    ### A: switch.vardagsrum_extra_subbas = on         ###
    ######################################################
  - alias: "Sätt på mediaspelare vid Watch ChromeCast"
    trigger:
      platform: state
      entity_id: remote.harmony_hub
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{{ trigger.from_state.attributes.current_activity == "PowerOff" }}'
        - condition: template
          value_template: '{{ trigger.to_state.attributes.current_activity == "Watch ChromeCast" }}'
        - condition: state
          entity_id: switch.vardagsrum_stereobank
          state: 'off'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.vardagsrum_stereobank
      - service: homeassistant.turn_on
        entity_id: switch.vardagsrum_tv
      - delay: '00:00:05'
      - service: script.harmony_off
      - delay: '00:00:05'
      - service: script.harmony_chromecast

    #######################################################
    ### Sätt på mediaspelare vid Listen to Spotify      ###
    ### T: remote.harmony_hub                           ###
    ### C: from current_activity == "PowerOff"          ###
    ###    to   current_activity == "Listen to Spotify" ###
    ###    switch.vardagsrum_stereobank = off           ###
    ### A: switch.vardagsrum_extra_subbas = on          ###
    #######################################################
  - alias: "Sätt på mediaspelare vid Listen to Spotify"
    trigger:
      platform: state
      entity_id: remote.harmony_hub
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{{ trigger.from_state.attributes.current_activity == "PowerOff" }}'
        - condition: template
          value_template: '{{ trigger.to_state.attributes.current_activity == "Listen to Spotify" }}'
        - condition: state
          entity_id: switch.vardagsrum_stereobank
          state: 'off'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.vardagsrum_stereobank
      - service: homeassistant.turn_on
        entity_id: switch.vardagsrum_tv
      - delay: '00:00:05'
      - service: script.harmony_off
      - delay: '00:00:05'
      - service: script.harmony_spotify

    ############################################################
    ### Sätt på mediaspelare vid Watch ChromeCast ultra      ###
    ### T: remote.harmony_hub                                ###
    ### C: from current_activity == "PowerOff"               ###
    ###    to   current_activity == "Watch ChromeCast ultra" ###
    ###    switch.vardagsrum_stereobank = off                ###
    ### A: switch.vardagsrum_extra_subbas = on               ###
    ############################################################
  - alias: "Sätt på mediaspelare vid Watch ChromeCast ultra"
    trigger:
      platform: state
      entity_id: remote.harmony_hub
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{{ trigger.from_state.attributes.current_activity == "PowerOff" }}'
        - condition: template
          value_template: '{{ trigger.to_state.attributes.current_activity == "Watch ChromeCast ultra" }}'
        - condition: state
          entity_id: switch.vardagsrum_stereobank
          state: 'off'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.vardagsrum_stereobank
      - service: homeassistant.turn_on
        entity_id: switch.vardagsrum_tv
      - delay: '00:00:05'
      - service: script.harmony_off
      - delay: '00:00:05'
      - service: script.harmony_chromecast_ultra

    ################################################################
    ### Sätt på mediaspelare vid Listen to ChromeCast ultra      ###
    ### T: remote.harmony_hub                                    ###
    ### C: from current_activity == "PowerOff"                   ###
    ###    to   current_activity == "Listen to ChromeCast ultra" ###
    ###    switch.vardagsrum_stereobank = off                    ###
    ### A: switch.vardagsrum_extra_subbas = on                   ###
    ################################################################
  - alias: "Sätt på mediaspelare vid Listen to ChromeCast ultra"
    trigger:
      platform: state
      entity_id: remote.harmony_hub
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{{ trigger.from_state.attributes.current_activity == "PowerOff" }}'
        - condition: template
          value_template: '{{ trigger.to_state.attributes.current_activity == "Listen to ChromeCast ultra" }}'
        - condition: state
          entity_id: switch.vardagsrum_stereobank
          state: 'off'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.vardagsrum_stereobank
      - service: homeassistant.turn_on
        entity_id: switch.vardagsrum_tv
      - delay: '00:00:05'
      - service: script.harmony_off
      - delay: '00:00:05'
      - service: script.harmony_chromecast_ultra_listen

    ######################################
    ### Sätt på subbasar vid hög volym ###
    ######################################
  - alias: Sätt på subbasar vid hög volym
    trigger:
      platform: numeric_state
      entity_id: media_player.yamaha_receiver
      value_template: "{{ state.attributes.volume_level }}"
      above: '0.65' # > 35
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: media_player.yamaha_receiver
          state: 'on'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.vardagsrum_subbas
      - service: homeassistant.turn_on
        entity_id: switch.vardagsrum_extra_subbas

    #######################################
    ### Stäng av subbasar vid låg volym ###
    #######################################
  - alias: Stäng av subbasar vid låg volym
    trigger:
      platform: numeric_state
      entity_id: media_player.yamaha_receiver
      value_template: "{{ state.attributes.volume_level }}"
      below: '0.65' # < 35
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: media_player.yamaha_receiver
          state: 'on'
    action:
      - service: homeassistant.turn_off
        entity_id: switch.vardagsrum_subbas
      - service: homeassistant.turn_off
        entity_id: switch.vardagsrum_extra_subbas
