remote:
  - platform: harmony
    name: Harmony Hub
    host: 192.168.1.247
    activity: Watch TV

group:
  harmony:
    name: Mediaspelare 
    view: yes
#    icon: mdi:information-outline
    entities:
      - group.mediaplayer

  mediaplayer:
    name: Fjärrkontroll
    view: no
#    icon: mdi:information-outline
    entities:
      - sensor.harmony_current
      - script.harmony_off
      - script.harmony_tv
      - script.harmony_radio
      - script.harmony_chromecast
      - script.harmony_spotify
      - media_player.chromecast
      - media_player.rxa1030_a47cf6

sensor:
  - platform: template
    sensors:
      harmony_current:
        value_template: '{{ states.remote.harmony_hub.attributes.current_activity }}'
        friendly_name: 'Aktuell aktivitet' 

script:
  harmony_off:
    alias: Harmony, stäng av allt
    sequence:
      - service: remote.turn_off
        entity_id: remote.harmony_hub

  harmony_radio:
    alias: Starta radio
    sequence:
      - service: remote.turn_on
        entity_id: remote.harmony_hub
        data:
          activity: '31360209'

  harmony_tv:
    alias: Starta Tv
    sequence:
      - service: remote.turn_on
        entity_id: remote.harmony_hub
        data:
          activity: '31360159'

  harmony_chromecast:
    alias: Starta ChromeCast
    sequence:
      - service: remote.turn_on
        entity_id: remote.harmony_hub
        data:
          activity: '31360285'

  harmony_spotify:
    alias: Starta Spotify
    sequence:
      - service: remote.turn_on
        entity_id: remote.harmony_hub
        data:
          activity: '31360307'

automation:
    ###############################################
    ### Stäng av subbasar vid mediaspelare off  ###
    ### T: remote.harmony_hub                   ###
    ### C: current_activity == "PowerOff"       ###
    ### A: switch.vardagsrum_subbas = off       ###
    ###    switch.vardagsrum_extra_subbas = off ###
    ###############################################
  - alias: "Stäng av subbasar vid mediaspelare off"
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: remote.harmony_hub
    condition:
      condition: template
      value_template: '{{ trigger.to_state.attributes.current_activity == "PowerOff" }}'
    action:
      - service: homeassistant.turn_off
        entity_id: switch.vardagsrum_subbas
      - service: homeassistant.turn_off
        entity_id: switch.vardagsrum_extra_subbas

    ##############################################
    ### Sätt på subbasar vid mediaspelare on   ###
    ### T: remote.harmony_hub                  ###
    ### C: current_activity != "PowerOff"      ###
    ### A: switch.vardagsrum_subbas = on       ###
    ###    switch.vardagsrum_extra_subbas = on ###
    ##############################################
  - alias: "Sätt på subbasar vid mediaspelare on"
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: remote.harmony_hub
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{{ trigger.to_state.attributes.current_activity != "PowerOff" }}'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.vardagsrum_subbas
      - service: homeassistant.turn_on
        entity_id: switch.vardagsrum_extra_subbas

    ##################################################################
    ### Sätt på mediaspelare om off                                ###
    ### En extra kontroll görs ifall påslag inte tidigare fungerat ###
    ### T: remote.harmony_hub                                      ###
    ### C: current_activity != "PowerOff"                          ###
    ###    sensor.yamaha == offline                                ###
    ### A: switch.vardagsrum_stereobank = on                       ###
    ###    switch.vardagsrum_tv = on                               ###
    ##################################################################
  - alias: "Sätt på mediaspelare om off"
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: remote.harmony_hub
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{{ trigger.to_state.attributes.current_activity != "PowerOff" }}'
        - condition: state
          entity_id: sensor.yamaha
          state: 'Offline'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.vardagsrum_stereobank
      - service: homeassistant.turn_on
        entity_id: switch.vardagsrum_tv
