##############
### sensor ###
##############
sensor:
  # Sensor som läser sista raden i när home-assistant.log uppdateras 
  - platform: file
    name: home_assistant_log
    file_path: /config/home-assistant.log
    value_template: >
      {{value|truncate(255,True)}}

  # Antal förekomster av ordet "[coap]" i home-assistant.log
  - platform: command_line
    command: grep -o -i '\[coap\]' home-assistant.log | wc -l
    name: home_assistant_log_coap

  # Antal förekomster av ordet "[coap] Exchange timed out" i home-assistant.log
  - platform: command_line
    command: grep -o -i '\[coap\] Exchange timed out' home-assistant.log | wc -l
    name: home_assistant_log_coap_timed_out

#####################
### input_boolean ###
#####################
input_boolean:
  # Sätts till on när en pågående omladdning av IKEA integrationen pågår och till off när den är klar
  ongoing_reload_ikea_integration:
    name: Pågående omladdning av IKEA integration
    initial: off

####################
### input_number ###
####################
input_number:
  # Visar antal uppdateringar av home-assistant.log, används inte till något
  home_assistant_log_updated:
    name: Antal uppdateringar av home-assistant.log
    initial: 0
    min: 0
    max: 10000

# Visar antal "[coap] i home-assistant.log, används inte till något
  home_assistant_log_coap:
    name: Antal coap i home-assistant.log
    initial: 0
    min: 0
    max: 1000

# Visar antal "[coap] Exchange timed out" i home-assistant.log, används inte till något
  home_assistant_log_coap_timed_out:
    name: Antal coap timed out i home-assistant.log
    initial: 0
    min: 0
    max: 1000

##################
### automation ###
##################
automation:
  - alias: "Updated home-assistant.log"
    mode: queued
    max: 10
    description: 'Körs när home-assistant.log uppdateras'

    trigger:
      - platform: state
        entity_id: sensor.home_assistant_log

    action:
      # Ser till att sensorer uppdateras med nya värden av antal förekomster
      - service: homeassistant.update_entity
        entity_id:
          - sensor.home_assistant_log_coap
          - sensor.home_assistant_log_coap_timed_out
          
      - service: input_number.set_value
        data_template:
          entity_id: input_number.home_assistant_log_updated 
          value: '{{ (states.input_number.home_assistant_log_updated.state | int ) + 1 }}'

  # Vet inte vilken av följande 2 automationer som bör köras, men denna tar fler tillfällen an den andra, men den andra kanske räcker
  # Se till att bara en av de två automationerna är igång
  - alias: "Updated sensor home_assistant_log_coap"
    mode: single
    description: 'Körs vid uppdaterad sensor home_assistant_log_coap'

    trigger:
      - platform: state
        entity_id: sensor.home_assistant_log_coap

    # Körs endast om det inte redan körs
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.ongoing_reload_ikea_integration
          state: 'off'

    action:
      # Sätter ongoing_reload_ikea_integration till on så att inget annat körs samtidigt
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.ongoing_reload_ikea_integration

      # Laddar om IKEA integrationen
      - service: rest_command.reload_ikea
        data: {}
 
      - service: system_log.write
        data:
          message: "Automatisk omstart av IKEA integrationen"
          level: info

      # Uppdaterar värdet, används inte av något
      - service: input_number.set_value
        data_template:
          entity_id: input_number.home_assistant_log_coap 
          value: '{{ (states.input_number.home_assistant_log_coap.state | int ) + 1 }}'

      # Väntar en sekund så att allt har gått klart
      - delay: "00:00:01"

      # Sätter ongoing_reload_ikea_integration till off efteråt
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.ongoing_reload_ikea_integration

################################################################################
  - alias: "Updated sensor home_assistant_log_coap_timed_out"
    mode: single
    description: 'Körs vid uppdaterad sensor home_assistant_log_coap_timed_out'

    trigger:
      - platform: state
        entity_id: sensor.home_assistant_log_coap_timed_out

    # Körs endast om det inte redan körs
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.ongoing_reload_ikea_integration
          state: 'off'

    action:
      # Sätter ongoing_reload_ikea_integration till on så att inget annat körs samtidigt
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.ongoing_reload_ikea_integration

      # Laddar om IKEA integrationen
      - service: rest_command.reload_ikea
        data: {}
 
      - service: system_log.write
        data:
          message: "Automatisk omstart av IKEA integrationen"
          level: warning

      # Uppdaterar värdet, används inte av något
      - service: input_number.set_value
        data_template:
          entity_id: input_number.home_assistant_log_coap_timed_out
          value: '{{ (states.input_number.home_assistant_log_coap_timed_out.state | int ) + 1 }}'

      # Väntar en sekund så att allt har gått klart
      - delay: "00:00:01"

      # Sätter ongoing_reload_ikea_integration till off efteråt
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.ongoing_reload_ikea_integration

  - alias: "Notify Laddar om IKEA integration"
    mode: single

    trigger:
      - platform: state
        entity_id: input_boolean.ongoing_reload_ikea_integration
        to: "on"

    action:
      - service: notify.pushbullet
        data:
          title: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
          message: "Laddar om IKEA integration"

##############
### script ###
##############
script:
  # Script som ska köras av alla script som uppdaterar IKEA enheter
  wait_for_reload_ikea_integration:
    alias: Vänta på restart av IKEA Integration
    sequence: 
    
      # Om en omstart av IKEA integrationen så väntar scriptet här till det är klart
      - wait_template: "{{ is_state('input_boolean.ongoing_reload_ikea_integration', 'off') }}"
        timeout: "00:00:10"

  reload_ikea:
    alias: Starta om IKEA integration manuellt
    sequence: 
      - service: system_log.write
        data:
          message: "Manuell omstart av IKEA integrationen"
          level: warning

####################
### rest_command ###
####################
rest_command:
  # Kommando för att ladda om IKEA integrationen
  # Värdet efter entry måste bytas ut mot ett nytt korrekt om IKEA integrationen tas bort och läses in igen
  reload_ikea:
    url: http://192.168.1.9:8123/api/config/config_entries/entry/dacd1b3f3313cc46cff31f8c1f0e87d2/reload 
    method: POST
    headers:
      authorization: !secret api_bearer_token
      content-type: 'application/json'