input_boolean:
  reload_ikea:
    name: Ladda om IKEA
    initial: off

automation:
- alias: "Keep IKEA running" 
  mode: single
  description: 'Check IKEA HUB down'
  trigger:
  - platform: state
    entity_id: light.vardagsrum_fonster # use any entity that is an IKEA device 
    to: unavailable
    for: 00:05:00
  condition: []
  action:
  - service: rest_command.reload_ikea
    data: {}

script:
  restart_ikea:
    alias: Starta om IKEA integration
    sequence: 
      - conditions: state 
        entity_id_ input_boolean.reload_ikea
        state: on
      - service: rest_command.reload_ikea
        data: {}
      - delay: "00:00:01"

rest_command:
  reload_ikea:
    url: http://192.168.1.9:8123/api/config/config_entries/entry/322c5a3db3cc555140caa8574613e3f9/reload 
    method: POST
    headers:
      authorization: !secret api_bearer_token
      content-type: 'application/json'