###################################################################################################################################
### ikea.yaml har skapats för att automatiskt kunna ladda om IKEA integrationen när ordet "[coap]" skrivs ut home-assistant.log ###
###################################################################################################################################

##############
### sensor ###
##############
sensor:
  # Sensor som läser sista raden i home-assistant.log när den uppdaterats 
  - platform: file
    name: home_assistant_log
    file_path: /config/home-assistant.log
    value_template: >
      {{value|truncate(255,True)}}

  # Antal förekomster av ordet "[coap]" i home-assistant.log
  - platform: command_line
    command: grep -o -i '\[coap\]' home-assistant.log | wc -l
    name: home_assistant_log_coap

#####################
### input_boolean ###
#####################
input_boolean:
  # Sätts till on när en pågående omladdning av IKEA integrationen pågår och till off när den är klar
  ongoing_reload_ikea_integration:
    name: Pågående omladdning av IKEA integration
    initial: off

##################
### automation ###
##################
automation:
  #########################################################################################################################
  ### Körs när home-assistant.log uppdateras                                                                            ###
  ### - Triggar sensor home_assistant_log_coap. Sensorn räknar antal förekomster av ordet "[coap]" i home_assistant.log ###
  #########################################################################################################################
  - alias: "Updated home-assistant.log"
    mode: queued
    max: 10
    description: 'Körs när home-assistant.log uppdateras'

    trigger:
      - platform: state
        entity_id: sensor.home_assistant_log

    action:
      - service: homeassistant.update_entity
        entity_id:
          - sensor.home_assistant_log_coap

  ################################################################################################################
  ### Körs när sensor home_assistant_log_coap har uppdaterats                                                  ###
  ### - uppdaterar sensor home_assistant_log_coap med antal förekomster av ordet "[coap]" i home_assistant.log ###
  ################################################################################################################
  - alias: "Updated sensor home_assistant_log_coap"
    mode: single
    description: 'Körs vid uppdaterad sensor home_assistant_log_coap'

    trigger:
      - platform: state
        entity_id: sensor.home_assistant_log_coap

    # Körs endast om det inte redan körs
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.ongoing_reload_ikea_integration
          state: 'off'

    action:
      # Sätter ongoing_reload_ikea_integration till on så att inget annat körs samtidigt
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.ongoing_reload_ikea_integration

      # Skriver till logfil
      - service: system_log.write
        data:
          message: "Automatisk omstart av IKEA integrationen, startar"
          level: warning

      # Laddar om IKEA integrationen
      - service: rest_command.reload_ikea
        data: {}
 
      # Skriver till logfil
      - service: system_log.write
        data:
          message: "Automatisk omstart av IKEA integrationen, klar"
          level: warning

      # Väntar en sekund så att allt har gått klart
      - delay: "00:00:01"

      # Sätter ongoing_reload_ikea_integration till off efteråt
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.ongoing_reload_ikea_integration

  ##############################################################
  ### Skickar pushbullet om att IKEA integrationen laddas om ###
  ##############################################################
  - alias: "Notify Laddar om IKEA integration"
    mode: single

    trigger:
      - platform: state
        entity_id: input_boolean.ongoing_reload_ikea_integration
        to: "on"

    action:
      - service: notify.pushbullet
        data:
          title: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
          message: "Laddar om IKEA integration"

##############
### script ###
##############
script:
  #######################################################################
  ### Script som ska köras av alla script som uppdaterar IKEA enheter ###
  #######################################################################
  wait_for_reload_ikea_integration:
    alias: Vänta på restart av IKEA Integration
    sequence: 
    
      # Om en omstart av IKEA integrationen så väntar scriptet här till det är klart
      - wait_template: "{{ is_state('input_boolean.ongoing_reload_ikea_integration', 'off') }}"
        timeout: "00:00:10"

  ##########################################################
  ### Script för att starta om IKEA integration manuellt ###
  ##########################################################
  reload_ikea:
    alias: Starta om IKEA integration manuellt
    sequence: 
      # Skriver till logfil
      - service: system_log.write
        data:
          message: "Manuell omstart av IKEA integrationen, startar"
          level: warning

      # Laddar om IKEA integrationen
      - service: rest_command.reload_ikea
        data: {}

      # Skriver till logfil
      - service: system_log.write
        data:
          message: "Manuell omstart av IKEA integrationen, klar"
          level: warning

####################
### rest_command ###
####################
rest_command:
  # Kommando för att ladda om IKEA integrationen
  # Värdet efter entry måste bytas ut mot ett nytt korrekt om IKEA integrationen tas bort och läses in igen
  # https://community.home-assistant.io/t/add-service-integration-reload/231940/37
  # IP: is your home assistant IP
  # Config Entry: is the unique config entry for your Tradfri and can be found in your directory config/.storage/core.config_entries. Search for Tradfri and use code Identity
  # Long-Lived Access Token can be created in the HA menu under your instance name
  reload_ikea:
    url: http://192.168.1.9:8123/api/config/config_entries/entry/a182dbdc14b566174f6f4acf2595af02/reload 
    method: POST
    headers:
      authorization: !secret api_bearer_token
      content-type: 'application/json'