#camera:
#  - platform: local_file
#    file_path: /config/kamera_1_images/kamera_1.jpg

#automation:
#  - alias: Sparar ner bild från kamera 1
#    trigger:
#      - platform: state
#        entity_id: binary_sensor.motion_kamera_1
#        to: 'on'
#    action:
#      service: camera.snapshot
#      data:
#        entity_id: camera.kamera_1
#        filename: '/config/kamera_1_images/kamera_1.jpg'

image_processing:
  - platform: deepstack_object
    ip_address: localhost
    port: 5000
    api_key: !secret deepstack_password
    # scan_interval: 30 # Optional, in seconds
    save_file_folder: /config/snapshots/
    save_timestamped_file: True
#    confidence: 90
    targets:
      - person
      - car
    source:
      - entity_id: camera.kamera_1
        name: deepstack_kamera_1

automation:
  - alias: Image processing
    trigger:
      - platform: time_pattern
        seconds: "/5"
    action:
      service: image_processing.scan
      data:
        entity_id: image_processing.deepstack_kamera_1
