image_processing:
  - platform: deepstack_object
    ip_address: localhost
    port: 5000
    api_key: !secret deepstack_password
    # scan_interval: 30 # Optional, in seconds
    save_file_folder: /config/camera_1_target_found/
    save_timestamped_file: True
#    confidence: 90
    targets:
      - person
#      - car
    source:
      - entity_id: camera.kamera_1
        name: deepstack_camera_1

automation:
  - alias: Image processing camera 1
    trigger:
      - platform: time_pattern
        seconds: "/5"
    action:
      service: image_processing.scan
      data:
        entity_id: image_processing.deepstack_camera_1
