image_processing:
  - platform: deepstack_object
    ip_address: localhost
    port: 5000
    api_key: !secret deepstack_password
    # scan_interval: 30 # Optional, in seconds
    save_file_folder: /config/camera_1_persons_found/
    save_timestamped_file: True
#    confidence: 90
    targets:
      - person
#      - car
    source:
      - entity_id: camera.kamera_1
        name: deepstack_camera_1

automation:
  - alias: Camera 1 Image processing
    trigger:
      - platform: time_pattern
        seconds: "/5"
    action:
      - service: image_processing.scan
        data:
          entity_id: image_processing.deepstack_camera_1

  - alias: Camera 1 Copy latest motion
    trigger:
      platform: event
      event_type: folder_watcher
      event_data:
        event_type: modified
    action:
      - service: shell_command.camera_1_copy_latest_motion

  - alias: Larm person detekterad del 1
    trigger:
      platform: state
      entity_id: sensor.camera_1_person
      to: '1'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: group.track_for_home_devices
          state: 'not_home'
    action:
      - delay: '00:01:00'
      - service: automation.trigger
        entity_id: automation.larm_person_detekterad_del_2

  - alias: Larm person detekterad del 2
    trigger:
      platform: state
      entity_id: group.track_for_home_devices
      to: 'not_home'
    action:
      - service: notify.pushbullet
        data:
          title: "Person detekterad"
          message: "och ingen är hemma"

shell_command:
  camera_1_copy_latest_motion: 'cp /config/camera_1_persons_found/deepstack_camera_1_latest.jpg /config/www/cam_captures/deepstack_camera_1_latest.jpg'

sensor:
  - platform: template
    sensors:
      camera_1_person:
        friendly_name: Camera 1 Person
        value_template: "{{ states.image_processing.deepstack_camera_1.attributes.summary['person'] }}"

      camera_1_bicycle:
        friendly_name: Camera 1 Cykel
        value_template: "{{ states.image_processing.deepstack_camera_1.attributes.summary['bicycle'] }}"

      camera_1_car:
        friendly_name: Camera 1 Bil
        value_template: "{{ states.image_processing.deepstack_camera_1.attributes.summary['car'] }}"

      camera_1_motorcycle:
        friendly_name: Camera 1 Motorcykel
        value_template: "{{ states.image_processing.deepstack_camera_1.attributes.summary['motorcycle'] }}"

      camera_1_bus:
        friendly_name: Camera 1 Buss
        value_template: "{{ states.image_processing.deepstack_camera_1.attributes.summary['bus'] }}"

      camera_1_truck:
        friendly_name: Camera 1 Lastbil
        value_template: "{{ states.image_processing.deepstack_camera_1.attributes.summary['truck'] }}"

      camera_1_boat:
        friendly_name: Camera 1 Båt
        value_template: "{{ states.image_processing.deepstack_camera_1.attributes.summary['boat'] }}"

      camera_1_bird:
        friendly_name: Camera 1 Fågel
        value_template: "{{ states.image_processing.deepstack_camera_1.attributes.summary['bird'] }}"

      camera_1_cat:
        friendly_name: Camera 1 Katt
        value_template: "{{ states.image_processing.deepstack_camera_1.attributes.summary['cat'] }}"

      camera_1_dog:
        friendly_name: Camera 1 Hund
        value_template: "{{ states.image_processing.deepstack_camera_1.attributes.summary['dog'] }}"

      camera_1_horse:
        friendly_name: Camera 1 Häst
        value_template: "{{ states.image_processing.deepstack_camera_1.attributes.summary['horse'] }}"

      camera_1_sheep:
        friendly_name: Camera 1 Får
        value_template: "{{ states.image_processing.deepstack_camera_1.attributes.summary['sheep'] }}"

      camera_1_cow:
        friendly_name: Camera 1 Ko
        value_template: "{{ states.image_processing.deepstack_camera_1.attributes.summary['cow'] }}"


# Used: 
# person, bicycle, car, motorcycle, bus, truck, boat,
# bird, cat, dog, horse, sheep, cow
# Not used: elephant, bear, zebra, giraffe,

# Unused:
# airplane, train, traffic light, fire hydrant, stop_sign,
# parking meter, bench,  backpack, umbrella, handbag, tie, suitcase,
# frisbee, skis, snowboard, sports ball, kite, baseball bat, baseball glove,
# skateboard, surfboard, tennis racket, bottle, wine glass, cup, fork,
# knife, spoon, bowl, banana, apple, sandwich, orange, broccoli, carrot,
# hot dog, pizza, donot, cake, chair, couch, potted plant, bed, dining table,
# toilet, tv, laptop, mouse, remote, keyboard, cell phone, microwave,
# oven, toaster, sink, refrigerator, book, clock, vase, scissors, teddy bear,
# hair dryer, toothbrush.