####################
### Input Number ###
####################
input_number:

  #############################
  # Values from inside sensor #
  #############################
  inside_kitchen_light_on:
    name: Inside kitchen light On
    initial: 35
    max: 50
    min: 5
    step: 1
    mode: box

  inside_kitchen_light_off:
    name: Inside kitchen light Off
    initial: 40
    max: 50
    min: 5
    step: 1
    mode: box

  inside_morning_light_on:
    name: Inside morning light On
    initial: 4
    max: 20
    min: 2
    step: 1
    mode: box

  inside_morning_light_off:
    name: Inside morning light Off
    initial: 5
    max: 20
    min: 4
    step: 1
    mode: box
    
  inside_daylight_on:
    name: Inside daylight On
    initial: 6
    max: 20
    min: 3
    step: 1
    mode: box

  inside_daylight_off:
    name: Inside daylight Off
    initial: 9
    max: 20
    min: 5
    step: 1
    mode: box

  inside_awaylight_on:
    name: Inside awaylight On
    initial: 3
    max: 20
    min: 1
    step: 1
    mode: box

  inside_awaylight_off:
    name: Inside awaylight Off
    initial: 5
    max: 20
    min: 3
    step: 1
    mode: box

  ##############################
  # Values from outside sensor #
  ##############################
  kitchen_light_on:
    name: On (3000,4000)
    initial: 3000
    max: 5000
    min: 2500
    step: 500
    mode: box

  kitchen_light_off:
    name: Off (3500,5000)
    initial: 3500
    max: 6000
    min: 3000
    step: 500
    mode: box

  morning_light_on:
    name: On (2000,3000)
    initial: 2000
    max: 4000
    min: 2000
    step: 500
    mode: box

  morning_light_off:
    name: Off (2500,4000)
    initial: 2500
    max: 5000
    min: 2000
    step: 500
    mode: box

  daylight_on:
    name: On (2000,3500)
    initial: 2000
    max: 5000
    min: 1500
    step: 500
    mode: box

  daylight_off:
    name: Off (2500,4500)
    initial: 2500
    max: 5000
    min: 2000
    step: 500
    mode: box

  awaylight_on:
    name: On (200)
    initial: 200
    max: 500
    min: 100
    step: 50
    mode: box

  awaylight_off:
    name: Off (250)
    initial: 250
    max: 500
    min: 100
    step: 50
    mode: box
#####################
### Input Boolean ###
#####################
input_boolean:
  snow_outside:
    name: Snö ute, anpassa ljusstyrka
    icon: mdi:pine-tree

  kitchen_light_on:
    name: Köksbelysning on

  morning_light_on:
    name: Morgonbelysning on

  daylight_on:
    name: Dagbelysning on

  awaylight_on:
    name: Bortabelysning on

##################
### Automation ###
##################

automation:
  ##################################
  - alias: Kitchen light on - inside
    trigger:
      - platform: template
        value_template: "{{((states('sensor.lightlevel_28') | int) | int(0)) < (states('input_number.inside_kitchen_light_on') | int(0) )}}"
      - platform: template
        value_template: "{{((states('sensor.lightlevel_30') | int) | int(0)) < (states('input_number.inside_kitchen_light_on') | int(0) )}}"

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id:  input_boolean.kitchen_light_on
          state: 'off'

    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.kitchen_light_on

  ###################################
  - alias: Kitchen light on - outside
    trigger:
      - platform: template
        value_template: "{{((states('sensor.ljusstyrka') | int) | int(0)) < (states('input_number.kitchen_light_on') | int(0) )}}"

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id:  input_boolean.kitchen_light_on
          state: 'off'

    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.kitchen_light_on

  ##################################
  - alias: Morning light on - inside
    trigger:
      - platform: template
        value_template: "{{((states('sensor.lightlevel_27') | int) | int(0)) < (states('input_number.inside_morning_light_on') | int(0) )}}"
      - platform: template
        value_template: "{{((states('sensor.lightlevel_29') | int) | int(0)) < (states('input_number.inside_morning_light_on') | int(0) )}}"

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id:  input_boolean.morning_light_on
          state: 'off'

    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.morning_light_on

  ###################################
  - alias: Morning light on - outside
    trigger:
      - platform: template
        value_template: "{{((states('sensor.ljusstyrka') | int) | int(0)) < (states('input_number.morning_light_on') | int(0) )}}"

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id:  input_boolean.morning_light_on
          state: 'off'

    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.morning_light_on

  #############################
  - alias: Daylight on - inside
    trigger:
      - platform: template
        value_template: "{{((states('sensor.lightlevel_27') | int) | int(0)) < (states('input_number.inside_daylight_on') | int(0) )}}"
      - platform: template
        value_template: "{{((states('sensor.lightlevel_29') | int) | int(0)) < (states('input_number.inside_daylight_on') | int(0) )}}"
    
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id:  input_boolean.daylight_on
          state: 'off'

    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.daylight_on

  ##############################
  - alias: Daylight on - outside
    trigger:
      - platform: template
        value_template: "{{((states('sensor.ljusstyrka') | int) | int(0)) < (states('input_number.daylight_on') | int(0) )}}"

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id:  input_boolean.daylight_on
          state: 'off'

    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.daylight_on

  #############################
  - alias: Awaylight on - inside
    trigger:
      - platform: template
        value_template: "{{((states('sensor.lightlevel_27') | int) | int(0)) < (states('input_number.inside_awaylight_on') | int(0) )}}"
      - platform: template
        value_template: "{{((states('sensor.lightlevel_29') | int) | int(0)) < (states('input_number.inside_awaylight_on') | int(0) )}}"

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id:  input_boolean.awaylight_on
          state: 'off'

    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.awaylight_on

  ##############################
  - alias: Awaylight on - outside
    trigger:
      - platform: template
        value_template: "{{((states('sensor.ljusstyrka') | int) | int(0)) < (states('input_number.awaylight_on') | int(0) )}}"

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id:  input_boolean.awaylight_on
          state: 'off'

    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.awaylight_on

  ##################################
  - alias: Kitchen light off - inside
    trigger:
      - platform: template
        value_template: "{{((states('sensor.lightlevel_28') | int) | int(0)) > (states('input_number.inside_kitchen_light_off') | int(0) )}}"
      - platform: template
        value_template: "{{((states('sensor.lightlevel_30') | int) | int(0)) > (states('input_number.inside_kitchen_light_off') | int(0) )}}"

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id:  input_boolean.kitchen_light_on
          state: 'on'

    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.kitchen_light_on

  ###################################
  - alias: Kitchen light off - outside
    trigger:
      - platform: template
        value_template: "{{((states('sensor.ljusstyrka') | int) | int(0)) > (states('input_number.kitchen_light_off') | int(0) )}}"

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id:  input_boolean.kitchen_light_on
          state: 'on'

    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.kitchen_light_on

  ##################################
  - alias: Morning light off - inside
    trigger:
      - platform: template
        value_template: "{{((states('sensor.lightlevel_27') | int) | int(0)) > (states('input_number.inside_morning_light_off') | int(0) )}}"
      - platform: template
        value_template: "{{((states('sensor.lightlevel_29') | int) | int(0)) > (states('input_number.inside_morning_light_off') | int(0) )}}"

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id:  input_boolean.morning_light_on
          state: 'on'

    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.morning_light_on

  ###################################
  - alias: Morning light off - outside
    trigger:
      - platform: template
        value_template: "{{((states('sensor.ljusstyrka') | int) | int(0)) > (states('input_number.morning_light_off') | int(0) )}}"

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id:  input_boolean.morning_light_on
          state: 'on'

    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.morning_light_on

  #############################
  - alias: Daylight off - inside
    trigger:
      - platform: template
        value_template: "{{((states('sensor.lightlevel_27') | int) | int(0)) > (states('input_number.inside_daylight_off') | int(0) )}}"
      - platform: template
        value_template: "{{((states('sensor.lightlevel_29') | int) | int(0)) > (states('input_number.inside_daylight_off') | int(0) )}}"

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id:  input_boolean.daylight_on
          state: 'on'

    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.daylight_on

  ##############################
  - alias: Daylight off - outside
    trigger:
      - platform: template
        value_template: "{{((states('sensor.ljusstyrka') | int) | int(0)) > (states('input_number.daylight_off') | int(0) )}}"

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id:  input_boolean.daylight_on
          state: 'on'

    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.daylight_on

  #############################
  - alias: Awaylight off - inside
    trigger:
      - platform: template
        value_template: "{{((states('sensor.lightlevel_27') | int) | int(0)) > (states('input_number.inside_awaylight_off') | int(0) )}}"
      - platform: template
        value_template: "{{((states('sensor.lightlevel_29') | int) | int(0)) > (states('input_number.inside_awaylight_off') | int(0) )}}"

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id:  input_boolean.awaylight_on
          state: 'on'

    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.awaylight_on

  ##############################
  - alias: Awaylight off - outside
    trigger:
      - platform: template
        value_template: "{{((states('sensor.ljusstyrka') | int) | int(0)) > (states('input_number.awaylight_off') | int(0) )}}"

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id:  input_boolean.awaylight_on
          state: 'on'

    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.awaylight_on


  ###############################
  - alias: Switch to snow outside
    mode: single

    trigger:
      - platform: state
        entity_id: input_boolean.snow_outside
        to: 'on'

    action:
      - service: input_number.set_value
        entity_id: input_number.kitchen_light_on
        data_template: 
          value: '4000'
      - service: input_number.set_value
        entity_id: input_number.kitchen_light_off
        data_template: 
          value: '5000'

      - service: input_number.set_value
        entity_id: input_number.morning_light_on
        data_template: 
          value: '3000'
      - service: input_number.set_value
        entity_id: input_number.morning_light_off
        data_template: 
          value: '4000'

      - service: input_number.set_value
        entity_id: input_number.daylight_on
        data_template: 
          value: '3500'
      - service: input_number.set_value
        entity_id: input_number.daylight_off
        data_template: 
          value: '4500'

  ##################################
  - alias: Switch to no snow outside
    mode: single

    trigger:
      - platform: state
        entity_id: input_boolean.snow_outside
        to: 'off'

    action:
      - service: input_number.set_value
        entity_id: input_number.kitchen_light_on
        data_template: 
          value: '3000'
      - service: input_number.set_value
        entity_id: input_number.kitchen_light_off
        data_template: 
          value: '3500'

      - service: input_number.set_value
        entity_id: input_number.morning_light_on
        data_template: 
          value: '2000'
      - service: input_number.set_value
        entity_id: input_number.morning_light_off
        data_template: 
          value: '2500'

      - service: input_number.set_value
        entity_id: input_number.daylight_on
        data_template: 
          value: '2000'
      - service: input_number.set_value
        entity_id: input_number.daylight_off
        data_template: 
          value: '2500'