##############
### notify ###
##############
notify:
  - name: file_lux
    platform: file
    filename: /home/homeassistant/.homeassistant/lux.csv
    timestamp: true

##################
### Automation ###
##################
automation:
  - alias: Under 2500 lux
    trigger:
      platform: numeric_state
      entity_id: sensor.ljusstyrka_flacksta
      below: 2500
    action:
      - service: notify.pushbullet
        data:
          message: 'Under 2500 lux ({{ states.sensor.ljusstyrka_flacksta.state }}): {{ states.sensor.ljusstyrka2.state }}'
      - service: notify.file_lux
        data_template: 
          message: 'Under 2500 lux ({{ states.sensor.ljusstyrka_flacksta.state }}): {{ states.sensor.ljusstyrka2.state }}'

  - alias: Under 1800 lux
    trigger:
      platform: numeric_state
      entity_id: sensor.ljusstyrka_flacksta
      below: 1800
    action:
      - service: notify.pushbullet
        data:
          message: 'Under 1800 lux ({{ states.sensor.ljusstyrka_flacksta.state }}): {{ states.sensor.ljusstyrka2.state }}'
      - service: notify.file_lux
        data_template: 
          message: 'Under 1800 lux ({{ states.sensor.ljusstyrka_flacksta.state }}): {{ states.sensor.ljusstyrka2.state }}'

  - alias: Under 250 lux
    trigger:
      platform: numeric_state
      entity_id: sensor.ljusstyrka_flacksta
      below: 250
    action:
      - service: notify.pushbullet
        data:
          message: 'Under 250 lux ({{ states.sensor.ljusstyrka_flacksta.state }}): {{ states.sensor.ljusstyrka2.state }}'
      - service: notify.file_lux
        data_template: 
          message: 'Under 250 lux ({{ states.sensor.ljusstyrka_flacksta.state }}): {{ states.sensor.ljusstyrka2.state }}'

  - alias: Under 200 lux
    trigger:
      platform: numeric_state
      entity_id: sensor.ljusstyrka_flacksta
      below: 200
    action:
      - service: notify.pushbullet
        data:
          message: 'Under 200 lux ({{ states.sensor.ljusstyrka_flacksta.state }}): {{ states.sensor.ljusstyrka2.state }}'
      - service: notify.file_lux
        data_template: 
          message: 'Under 200 lux ({{ states.sensor.ljusstyrka_flacksta.state }}): {{ states.sensor.ljusstyrka2.state }}'

  - alias: Under 150 lux
    trigger:
      platform: numeric_state
      entity_id: sensor.ljusstyrka_flacksta
      below: 150
    action:
      - service: notify.pushbullet
        data:
          message: 'Under 150 lux ({{ states.sensor.ljusstyrka_flacksta.state }}): {{ states.sensor.ljusstyrka2.state }}'
      - service: notify.file_lux
        data_template: 
          message: 'Under 150 lux ({{ states.sensor.ljusstyrka_flacksta.state }}): {{ states.sensor.ljusstyrka2.state }}'

  - alias: Under 40 lux
    trigger:
      platform: numeric_state
      entity_id: sensor.ljusstyrka_flacksta
      below: 40
    action:
      - service: notify.pushbullet
        data:
          message: 'Under 40 lux ({{ states.sensor.ljusstyrka_flacksta.state }}): {{ states.sensor.ljusstyrka2.state }}'
      - service: notify.file_lux
        data_template: 
          message: 'Under 40 lux ({{ states.sensor.ljusstyrka_flacksta.state }}): {{ states.sensor.ljusstyrka2.state }}'

  - alias: Under 5 lux
    trigger:
      platform: numeric_state
      entity_id: sensor.ljusstyrka_flacksta
      below: 5
    action:
      - service: notify.pushbullet
        data:
          message: 'Under 5 lux ({{ states.sensor.ljusstyrka_flacksta.state }}): {{ states.sensor.ljusstyrka2.state }}'
      - service: notify.file_lux
        data_template: 
          message: 'Under 5 lux ({{ states.sensor.ljusstyrka_flacksta.state }}): {{ states.sensor.ljusstyrka2.state }}'

  - alias: Under 1 lux
    trigger:
      platform: numeric_state
      entity_id: sensor.ljusstyrka_flacksta
      below: 1
    action:
      - service: notify.pushbullet
        data:
          message: 'Under 1 lux ({{ states.sensor.ljusstyrka_flacksta.state }}): {{ states.sensor.ljusstyrka2.state }}'
      - service: notify.file_lux
        data_template: 
          message: 'Under 1 lux ({{ states.sensor.ljusstyrka_flacksta.state }}): {{ states.sensor.ljusstyrka2.state }}'

############################################################
  - alias: Över 2500 lux
    trigger:
      platform: numeric_state
      entity_id: sensor.ljusstyrka_flacksta
      above: 2500
    action:
      - service: notify.pushbullet
        data:
          message: 'Över 2500 lux ({{ states.sensor.ljusstyrka_flacksta.state }}): {{ states.sensor.ljusstyrka2.state }}'
      - service: notify.file_lux
        data_template: 
          message: 'Över 2500 lux ({{ states.sensor.ljusstyrka_flacksta.state }}): {{ states.sensor.ljusstyrka2.state }}'

  - alias: Över 1800 lux
    trigger:
      platform: numeric_state
      entity_id: sensor.ljusstyrka_flacksta
      above: 1800
    action:
      - service: notify.pushbullet
        data:
          message: 'Över 1800 lux ({{ states.sensor.ljusstyrka_flacksta.state }}): {{ states.sensor.ljusstyrka2.state }}'
      - service: notify.file_lux
        data_template: 
          message: 'Över 1800 lux ({{ states.sensor.ljusstyrka_flacksta.state }}): {{ states.sensor.ljusstyrka2.state }}'

  - alias: Över 250 lux
    trigger:
      platform: numeric_state
      entity_id: sensor.ljusstyrka_flacksta
      above: 250 
    action:
      - service: notify.pushbullet
        data:
          message: 'Över 250 lux ({{ states.sensor.ljusstyrka_flacksta.state }}): {{ states.sensor.ljusstyrka2.state }}'
      - service: notify.file_lux
        data_template: 
          message: 'Över 250 lux ({{ states.sensor.ljusstyrka_flacksta.state }}): {{ states.sensor.ljusstyrka2.state }}'

  - alias: Över 150 lux
    trigger:
      platform: numeric_state
      entity_id: sensor.ljusstyrka_flacksta
      above: 150
    action:
      - service: notify.pushbullet
        data:
          message: 'Över 150 lux ({{ states.sensor.ljusstyrka_flacksta.state }}): {{ states.sensor.ljusstyrka2.state }}'
      - service: notify.file_lux
        data_template: 
          message: 'Över 150 lux ({{ states.sensor.ljusstyrka_flacksta.state }}): {{ states.sensor.ljusstyrka2.state }}'

  - alias: Över 60 lux
    trigger:
      platform: numeric_state
      entity_id: sensor.ljusstyrka_flacksta
      above: 60
    action:
      - service: notify.pushbullet
        data:
          message: 'Över 60 lux ({{ states.sensor.ljusstyrka_flacksta.state }}): {{ states.sensor.ljusstyrka2.state }}'
      - service: notify.file_lux
        data_template: 
          message: 'Över 60 lux ({{ states.sensor.ljusstyrka_flacksta.state }}): {{ states.sensor.ljusstyrka2.state }}'
