timer:
  # Timers för reset, eftersom närvarosensor inte gör reset ifall någon är i köket
  timer_rorelsedetektor_kok_reset:
    name: Rörelsedetektor kök timer reset
    duration: '00:00:30'

  # Timers för släck nattbelysning
  timer_rorelsedetektor_kok_short:
    name: Rörelsedetektor kök timer
    duration: '00:01:00'

  # Timers för släck köksbelysning
  timer_rorelsedetektor_kok_medium:
    name: Rörelsedetektor kök timer
    duration: '00:05:00'

automation:
    #############################################################
    ### Startar alla timers vid rörelse i kök                 ###
    ### T: binary_sensor.lumi_lumi_sensor_motion_aq2_rorelse  ###
    ###    binary_sensor.lumi_lumi_sensor_motion_aq2_motion_2 ###
    ###    binary_sensor.motion_sensor                        ###
    ### A: input_boolean.rorelsedetektor_kok_aktiv = on       ###
    ###    timer.timer_rorelsedetektor_kok_reset = cancel     ###
    ###    timer.timer_rorelsedetektor_kok_short = cancel     ###
    ###    timer.timer_rorelsedetektor_kok_medium = cancel    ###
    ###    timer.timer_rorelsedetektor_kok_reset = start      ###
    ###    timer.timer_rorelsedetektor_kok_short = start      ###
    ###    timer.timer_rorelsedetektor_kok_medium = start     ###
    #############################################################
  - alias: Startar timers kök
    trigger:
      - platform: state
        entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_rorelse # Köksskåp
        to: 'on'
      - platform: state
        entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_motion_2 # Kök kylskåp
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_sensor # Köksgolv IKEA
        to: 'on'
    action:
      # Aktiverar rorelsedetektor_kok_aktiv
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.rorelsedetektor_kok_aktiv

      # Cancel timers, återställer till maxtid
      - service: timer.cancel
        entity_id: timer.timer_rorelsedetektor_kok_reset
      - service: timer.cancel
        entity_id: timer.timer_rorelsedetektor_kok_short
      - service: timer.cancel
        entity_id: timer.timer_rorelsedetektor_kok_medium

      # Start timers, börjar räkna ner tiden
      - service: timer.start
        entity_id: timer.timer_rorelsedetektor_kok_reset
      - service: timer.start
        entity_id: timer.timer_rorelsedetektor_kok_short
      - service: timer.start
        entity_id: timer.timer_rorelsedetektor_kok_medium

    ###################################################################
    ### Vid timer rorelstimer_rorelsedetektor_kok_reset finished    ###
    ### T: timer.timer_rorelsedetektor_kok_medium == finished       ###
    ### C: binary_sensor.lumi_lumi_sensor_motion_aq2_rorelse == on  ###
    ###    binary_sensor.lumi_lumi_sensor_motion_aq2_motion_2 == on ###
    ###    binary_sensor.motion_sensor == on                        ###
    ### A: input_boolean.rorelsedetektor_kok_aktiv = off            ###
    ###################################################################
  - alias: Stänger av rörelsedetektor kök reset
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.timer_rorelsedetektor_kok_reset
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_rorelse
          state: 'on'
        - condition: state
          entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_motion_2
          state: 'on' 
        - condition: state
          entity_id: binary_sensor.motion_sensor
          state: 'on'
    action:
      # Cancel timers, återställer till maxtid
      - service: timer.cancel
        entity_id: timer.timer_rorelsedetektor_kok_reset
      - service: timer.cancel
        entity_id: timer.timer_rorelsedetektor_kok_short
      - service: timer.cancel
        entity_id: timer.timer_rorelsedetektor_kok_medium

      # Start timers, börjar räkna ner tiden
      - service: timer.start
        entity_id: timer.timer_rorelsedetektor_kok_reset
      - service: timer.start
        entity_id: timer.timer_rorelsedetektor_kok_short
      - service: timer.start
        entity_id: timer.timer_rorelsedetektor_kok_medium

    #############################################################
    ### Vid timer rorelsedetektor_kok_aktiv finished          ###
    ### T: timer.timer_rorelsedetektor_kok_medium == finished ###
    ### C: input_boolean.rorelsedetektor_kok_aktiv == on      ###
    ### A: input_boolean.rorelsedetektor_kok_aktiv = off      ###
    #############################################################
  - alias: Stänger av rörelsedetektor kök aktiv
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.timer_rorelsedetektor_kok_medium
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.rorelsedetektor_kok_aktiv
          state: 'on'
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.rorelsedetektor_kok_aktiv

    ######################################################################
    ### Vid timer rorelsedetektor_kok_aktiv för nattbelysning finished ###
    ### T: timer.timer_rorelsedetektor_kok_short == finished           ###
    ### C: input_select.light_inside == 'Nattbelysning'                ###
    ### A: input_boolean.rorelsedetektor_kok_aktiv = off               ###
    ######################################################################
  - alias: Stänger av rörelsedetektor kök aktiv för nattbelysning
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.timer_rorelsedetektor_kok_short
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.light_inside
          state: 'Nattbelysning'
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.rorelsedetektor_kok_aktiv