####################################################
#                                                  #
#                     INPUT_BOOLEAN                #
#                                                  #
####################################################
input_boolean:
  rorelsedetektor_louise_rum_aktiv:
    name: Rörelsedetektor Louise rum aktiv
    initial: off

####################################################
#                                                  #
#                        TIMER                     #
#                                                  #
####################################################
timer:
  # Timers för reset, eftersom närvarosensor inte gör reset ifall någon är i köket
  timer_rorelsedetektor_louise_rum_reset:
    name: Rörelsedetektor Louise rum timer reset
    duration: '00:00:30'

  # Timers för släck belysning
  timer_rorelsedetektor_louise_rum:
    name: Rörelsedetektor Louise rum timer
    duration: '01:00:00'

####################################################
#                                                  #
#                     AUTOMATION                   #
#                                                  #
####################################################
automation:
    ################################################################
    ### Startar alla timers vid rörelse i Louise rum             ###
    ### T: binary_sensor.motion_sensor                           ###
    ### A: input_boolean.rorelsedetektor_louise_rum_aktiv = on   ###
    ###    timer.timer_rorelsedetektor_louise_rum_reset = cancel ###
    ###    timer.timer_rorelsedetektor_louise_rum = cancel       ###
    ###    timer.timer_rorelsedetektor_louise_rum_reset = start  ###
    ###    timer.timer_rorelsedetektor_louise_rum = start        ###
    ################################################################
  - alias: Startar timers Louise rum
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor # Louise rum IKEA
        to: 'on'
    action:
      # Aktiverar rorelsedetektor_louise_rum_aktiv
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.rorelsedetektor_louise_rum_aktiv

      # Cancel timers, återställer till maxtid
      - service: timer.cancel
        entity_id: timer.timer_rorelsedetektor_louise_rum_reset
      - service: timer.cancel
        entity_id: timer.timer_rorelsedetektor_louise_rum

      # Start timers, börjar räkna ner tiden
      - service: timer.start
        entity_id: timer.timer_rorelsedetektor_louise_rum_reset
      - service: timer.start
        entity_id: timer.timer_rorelsedetektor_louise_rum

    #################################################################
    ### Vid timer timer_rorelsedetektor_louise_rum_reset finished ###
    ### T: timer.timer_rorelsedetektor_louise_rum == finished     ###
    ### C: input_boolean.rorelsedetektor_louise_rum_aktiv == on   ###
    ### A: input_boolean.rorelsedetektor_louise_rum_aktiv = off   ###
    #################################################################
  - alias: Stänger av rörelsedetektor Louise rum reset
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.timer_rorelsedetektor_louise_rum_reset
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id:  binary_sensor.motion_sensor
          state: 'on'
    action:
      # Cancel timers, återställer till maxtid
      - service: timer.cancel
        entity_id: timer.timer_rorelsedetektor_louise_rum_reset
      - service: timer.cancel
        entity_id: timer.timer_rorelsedetektor_louise_rum

      # Start timers, börjar räkna ner tiden
      - service: timer.start
        entity_id: timer.timer_rorelsedetektor_louise_rum_reset
      - service: timer.start
        entity_id: timer.timer_rorelsedetektor_louise_rum

    ###############################################################
    ### Vid timer timer_rorelsedetektor_louise_rum finished     ###
    ### T: timer.timer_rorelsedetektor_louise_rum == finished   ###
    ### C: input_boolean.rorelsedetektor_louise_rum_aktiv == on ###
    ### A: input_boolean.rorelsedetektor_louise_rum_aktiv = off ###
    ###############################################################
  - alias: Stänger av rörelsedetektor Louise rum aktiv
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.timer_rorelsedetektor_louise_rum
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id:  input_boolean.rorelsedetektor_louise_rum_aktiv
          state: 'on'
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.rorelsedetektor_louise_rum_aktiv
