##################
### Automation ###
##################
automation:
  ########################################
  ### MQTT Publish outside temperature ###
  ### Used by Thomas C.                ###
  ########################################
  - alias: MQTT Publish outside temperature
    id: '9256370676537'
    mode: single

    trigger:
      - platform: state
        entity_id: sensor.ute
    
    action:
      - service: mqtt.publish
        data_template:
          payload: "{{trigger.to_state.state}}"
          topic: !secret mqtt_path_publish_outside_temperaure

  #########################################
  ### MQTT Publish filtered outside lux ###
  ### Used by Thomas C.                 ###
  #########################################
  - alias: MQTT Publish filtered outside lux
    id: '9256370678754'
    mode: single

    trigger:
      - platform: state
        entity_id: sensor.ljusstyrka
    
    condition:

    action:
      - service: mqtt.publish
        data_template:
          payload: "{{trigger.to_state.state}}"
          topic: !secret mqtt_path_publish_outside_filtered_outside_lux