##################
### Automation ###
##################
automation:
  ########################################
  ### MQTT Publish outside temperature ###
  ### Used by Thomas C.                ###
  ########################################
  - alias: MQTT Publish outside temperature
    id: '9256370676537'
    mode: single

    trigger:
      - platform: state
        entity_id: sensor.ute
    
    action:
      - service: mqtt.publish
        data_template:
          payload: "{{trigger.to_state.state}}"
          topic: !secret mqtt_path_publish_outside_temperaure



  - alias: Pause MQTT Broker
    id: '9256370676345' 
    mode: single

    trigger:
      - platform: state
        entity_id: light.stralkastare_husgavel
        to: 'on'

    action:
      - service: hassio.addon_stop
        data:
          addon: core_mosquitto


  - alias: Resume MQTT Broker
    id: '9251230676345' 
    mode: single

    trigger:
      - platform: state
        entity_id: light.stralkastare_husgavel
        to: 'off'

    action:    
      - delay: "30"
      
      - service: hassio.addon_start
        data:
          addon: core_mosquitto
