##########
# Sensor #
##########
sensor:
    # https://home-assistant.io/components/sensor.command_line/

  - platform: command_line
    name: raspberry_pi_2_CPU_Temp
    friendly_name: Raspberry Pi 2 (hassbian) CPU Temperture
    command: ssh pi@192.168.1.12 "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'

  - platform: command_line
    name: raspberry_Pi3b_cpu_temp
    friendly_name: Raspberry Pi 3B (hagaholm) CPU Temperture
    command: ssh pi@192.168.1.10 "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'
