timer:
  timer_rorelsevakt_kok_short:
    duration: '00:01:00'
  timer_rorelsevakt_kok_medium:
    duration: '00:10:00'
  timer_rorelsevakt_kok_long:
    duration: '00:30:00'

automation:
  - alias: Set timers when there is movement in kitchen
    trigger:
      - platform: state
        entity_id: switch.rorelsevakt_kok
        to: 'on'
    action:
      # Reset switch.rorelsevakt_kok
      - service: homeassistant.turn_off
        entity_id: switch.rorelsevakt_kok

      # Aktiverar rorelsevakt_kok_aktiv
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.rorelsevakt_kok_aktiv

      # Cancel timers
      - service: timer.cancel
        entity_id: timer.timer_rorelsevakt_kok_short
      - service: timer.cancel
        entity_id: timer.timer_rorelsevakt_kok_medium
      - service: timer.cancel
        entity_id: timer.timer_rorelsevakt_kok_long

      #- delay: '00:00:01'

      # Start timers
      - service: timer.start
        entity_id: timer.timer_rorelsevakt_kok_short
      - service: timer.start
        entity_id: timer.timer_rorelsevakt_kok_medium
      - service: timer.start
        entity_id: timer.timer_rorelsevakt_kok_long
 
  - alias: Turn off pir at end of timer
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.timer_rorelsevakt_kok_short
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.rorelsevakt_kok_aktiv

