timer:
  # Timers för släck nattbelysning
  timer_rorelsevakt_kok_short:
    duration: '00:01:00'

  # Timers för släck köksbelysning
  timer_rorelsevakt_kok_medium:
    name: Tid kvar
    duration: '00:10:00'

automation:
    ######################################################
    ### Startar båda timers vid rörelse i kök          ###
    ### T: switch.rorelsevakt_kok == on                ###
    ### A: switch.rorelsevakt_kok = off                ###
    ###    input_boolean.rorelsevakt_kok_aktiv = on    ###
    ###    timer.timer_rorelsevakt_kok_short = cancel  ###
    ###    timer.timer_rorelsevakt_kok_medium = cancel ###
    ###    timer.timer_rorelsevakt_kok_short = start   ###
    ###    timer.timer_rorelsevakt_kok_medium = start  ###
    ######################################################
  - alias: Startar timers
    trigger:
      - platform: state
        entity_id: switch.rorelsevakt_kok
        to: 'on'
    action:
      # Reset switch.rorelsevakt_kok
      - service: homeassistant.turn_off
        entity_id: switch.rorelsevakt_kok

      # Aktiverar rorelsevakt_kok_aktiv
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.rorelsevakt_kok_aktiv

      # Cancel timers, återställer till maxtid
      - service: timer.cancel
        entity_id: timer.timer_rorelsevakt_kok_short
      - service: timer.cancel
        entity_id: timer.timer_rorelsevakt_kok_medium

      # Start timers, börjar räkna ner tiden
      - service: timer.start
        entity_id: timer.timer_rorelsevakt_kok_short
      - service: timer.start
        entity_id: timer.timer_rorelsevakt_kok_medium

    #########################################################
    ### Stänger av rorelsevakt_kok_aktiv (om aktiv)       ###
    ### T: timer.timer_rorelsevakt_kok_medium == finished ###
    ### C: input_boolean.rorelsevakt_kok_aktiv == on      ###
    ### A: input_boolean.rorelsevakt_kok_aktiv = off      ###
    #########################################################
  - alias: Stänger av rorelsevakt_kok_aktiv (om aktiv)
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.timer_rorelsevakt_kok_medium
    condition:
      - condition: state
        entity_id: input_boolean.rorelsevakt_kok_aktiv
        state: 'on'
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.rorelsevakt_kok_aktiv

    ###########################################################
    ### Stänger av rorelsevakt_kok_aktiv  för nattbelysning ###
    ### T: timer.timer_rorelsevakt_kok_short == finished    ###
    ### C: input_select.inside_lights == 'Nattbelysning'    ###
    ### A: input_boolean.rorelsevakt_kok_aktiv = off        ###
    ###########################################################
  - alias: Stänger av rorelsevakt_kok_aktiv för nattbelysning
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.timer_rorelsevakt_kok_short
    condition:
      - condition: state
        entity_id: input_select.inside_lights
        state: 'Nattbelysning'
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.rorelsevakt_kok_aktiv
