timer:
  # Timers för släck nattbelysning
  timer_rorelsevakt_1_short:
    duration: '00:01:00'

  # Timers för släck köksbelysning
  timer_rorelsevakt_1_medium:
    name: Tid kvar
    duration: '00:10:00'

automation:
    ####################################################
    ### Startar båda timers vid rörelse i kök        ###
    ### T: switch.rorelsevakt_1 == on                ###
    ### A: switch.rorelsevakt_1 = off                ###
    ###    input_boolean.rorelsevakt_1_aktiv = on    ###
    ###    timer.timer_rorelsevakt_1_short = cancel  ###
    ###    timer.timer_rorelsevakt_1_medium = cancel ###
    ###    timer.timer_rorelsevakt_1_short = start   ###
    ###    timer.timer_rorelsevakt_1_medium = start  ###
    ####################################################
  - alias: Startar timers
    trigger:
      - platform: state
        entity_id: switch.rorelsevakt_1
        to: 'on'
    action:
      # Reset switch.rorelsevakt_1
      - service: homeassistant.turn_off
        entity_id: switch.rorelsevakt_1

      # Aktiverar rorelsevakt_1_aktiv
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.rorelsevakt_1_aktiv

      # Cancel timers, återställer till maxtid
      - service: timer.cancel
        entity_id: timer.timer_rorelsevakt_1_short
      - service: timer.cancel
        entity_id: timer.timer_rorelsevakt_1_medium

      # Start timers, börjar räkna ner tiden
      - service: timer.start
        entity_id: timer.timer_rorelsevakt_1_short
      - service: timer.start
        entity_id: timer.timer_rorelsevakt_1_medium

    #######################################################
    ### Stänger av rorelsevakt_1_aktiv (om aktiv)       ###
    ### T: timer.timer_rorelsevakt_1_medium == finished ###
    ### C: input_boolean.rorelsevakt_1_aktiv == on      ###
    ### A: input_boolean.rorelsevakt_1_aktiv = off      ###
    #######################################################
  - alias: Stänger av rorelsevakt_1_aktiv (om aktiv)
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.timer_rorelsevakt_1_medium
    condition:
      - condition: state
        entity_id: input_boolean.rorelsevakt_1_aktiv
        state: 'on'
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.rorelsevakt_1_aktiv

    #########################################################
    ### Stänger av rorelsevakt_1_aktiv  för nattbelysning ###
    ### T: timer.timer_rorelsevakt_1_short == finished    ###
    ### C: input_select.inside_lights == 'Nattbelysning'  ###
    ### A: input_boolean.rorelsevakt_1_aktiv = off        ###
    #########################################################
  - alias: Stänger av rorelsevakt_1_aktiv för nattbelysning
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.timer_rorelsevakt_1_short
    condition:
      - condition: state
        entity_id: input_select.inside_lights
        state: 'Nattbelysning'
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.rorelsevakt_1_aktiv
