#########
# Group #
#########
group:
  system_info_view:
    name: System info
    icon: mdi:lan
    view: yes
    entities:
      - group.computer_states
      - group.media_states
      - group.mobile_states
      - group.network_states
      - group.system_monitor_card_pi_hassbian
      - group.system_monitor_card_pi_1_wire
      - group.system_monitor_card_pi_hagaholm

  computer_states:
    name: Dator status
    entities:
      - sensor.mickes_laptop
      - sensor.mickes_work_laptop
      - sensor.louise_dator

  media_states:
    name: Mediaspelare status
    entities:
      - sensor.harmony_hub
      - sensor.yamaha
      - sensor.classic
      - sensor.panasonic_tv
      - sensor.canal_digital
      - sensor.chromecast
      - sensor.chromecast_2
      - sensor.dns320

  mobile_states:
    name: Mobil status
    entities:
      - sensor.mobil_louise
      - sensor.mobil_annelie
      - sensor.mobil_annelie_jobb
      - sensor.mobil_micke
      - sensor.mobil_andreas
      - sensor.mobil_margareta
      - sensor.mobil_herbert
      - sensor.mobil_erik

  network_states:
    name: Nätverks status
    entities:
      - sensor.asus_rt_ac68u
      - sensor.asus_n66u
      - sensor.asuswrt_download
      - sensor.asuswrt_download_speed
      - sensor.asuswrt_upload
      - sensor.asuswrt_upload_speed
      - sensor.rt_ac68u_bytes_received
      - sensor.rt_ac68u_bytes_sent
      - sensor.rt_ac68u_kbyte_sec_received
      - sensor.rt_ac68u_kbyte_sec_sent
      - sensor.rt_ac68u_packets_received
      - sensor.rt_ac68u_packets_sec_received
      - sensor.rt_ac68u_packets_sec_sent
      - sensor.rt_ac68u_packets_sent

  system_monitor_card_pi_hassbian:
    name: Raspberry Pi 3B (hassbian)
    entities:
      - sensor.hassbian
      - sensor.cpu_temperature
      - sensor.cpuspeed
      - sensor.uptime
      - sensor.last_boot
#      - sensor.since_last_boot
      - sensor.memory_free
      - sensor.memory_use_percent
      - sensor.processor_use
      - sensor.disk_use_percent
      - sensor.disk_use_percent_home
      - sensor.swap_use_percent
      - sensor.load_1m
      - sensor.load_5m
      - sensor.load_15m
      - sensor.websocket_api

  system_monitor_card_pi_1_wire:
    name: Raspberry Pi 2 (1-Wire)
    entities:
      - sensor.raspberry_pi_2
      - sensor.raspberry_pi_2_temperature

  system_monitor_card_pi_hagaholm:
    name: Raspberry Pi 3B (hagaholm)
    entities:
      - sensor.raspberry_pi_3b
      - sensor.raspberry_pi_3b_temperature

##########
# Sensor #
##########
sensor:
    #####################
    # HA server metrics #
    #####################
    # https://home-assistant.io/components/sensor.systemmonitor/
  - platform: systemmonitor
    resources:
      - type: memory_free
      - type: memory_use_percent
      - type: processor_use
#      - type: since_last_boot
      - type: disk_use_percent
        arg: /home
      - type: swap_use_percent
      - type: load_1m
      - type: load_5m
      - type: load_15m
#      - type: network_in
#        arg: ens32
#      - type: network_out
#        arg: ens32

    ##########
    # uptime #
    ##########
  - platform: uptime
    unit_of_measurement: hours

    #############
    # CPU Speed #
    #############
    # https://home-assistant.io/components/sensor.cpuspeed/
  - platform: cpuspeed
    name: CPU

    #################
    # Websocket API #
    #################
    # https://www.home-assistant.io/components/websocket_api/
  - platform: websocket_api

    ######################
    # HA Current version #
    ######################
    # https://home-assistant.io/components/sensor.command_line/
  - platform: command_line
    command: python3 -c "import requests; print(requests.get('https://pypi.python.org/pypi/homeassistant/json').json()['info']['version'])"
    name: Current HA Version

    ########################
    # HA Installed version #
    ########################
  - platform: command_line
    name: Installed version
    command: "head -5 /home/homeassistant/.homeassistant/.HA_VERSION"

    ##########
    # Sensor #
    ##########
  - platform: command_line
    name: Raspberry Pi 2 temperature
    command: ssh pi@192.168.1.12 "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'

  - platform: command_line
    name: Raspberry Pi 3b temperature
    command: ssh pi@192.168.1.10 "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'

    ################################
    # Internet performance metrics #
    ################################
    # https://home-assistant.io/components/sensor.speedtest/
#  - platform: speedtest
#    server_id: 2229
#    monitored_conditions:
#      - download
#      - upload
#      - ping
#    hour:
#      - 0
#      - 6
#      - 12
#      - 18

  - platform: template
    sensors:
    ###########
    # Network #
    ###########
      asus_rt_ac68u:
        friendly_name: 'Asus RT-AC68U'
        value_template: "{{ 'Online' if is_state('device_tracker.asus_rt_ac68u', 'home') else 'Offline' }}"
      asus_n66u:
        friendly_name: 'Asus EA-N66U'
        value_template: "{{ 'Online' if is_state('device_tracker.asus_n66u', 'home') else 'Offline' }}"

    ###############
    # Mediaplayer #
    ###############
      harmony_hub:
        friendly_name: 'Harmony Hub'
        value_template: "{{ 'Online' if is_state('device_tracker.harmony_hub', 'home') else 'Offline' }}"
      canal_digital:
        friendly_name: 'Canal Digital'
        value_template: "{{ 'Online' if is_state('device_tracker.canal_digital', 'home') else 'Offline' }}"
      classic:
        friendly_name: 'SqueezeBox Classic'
        value_template: "{{ 'Online' if is_state('device_tracker.classic', 'home') else 'Offline' }}"
      yamaha:
        friendly_name: 'Yamaha RX-A1030'
        value_template: "{{ 'Online' if is_state('device_tracker.yamaha', 'home') else 'Offline' }}"
      chromecast:
        friendly_name: 'Chromecast'
        value_template: "{{ 'Online' if is_state('device_tracker.chromecast', 'home') else 'Offline' }}"
      chromecast_2:
        friendly_name: 'Chromecast Wifi'
        value_template: "{{ 'Online' if is_state('device_tracker.chromecast_2', 'home') else 'Offline' }}"
      panasonic_tv:
        friendly_name: 'Tv Panasonic'
        value_template: "{{ 'Online' if is_state('device_tracker.panasonic_tv', 'home') else 'Offline' }}"
      dns320:
        friendly_name: 'Nas DNS-320'
        value_template: "{{ 'Online' if is_state('device_tracker.dns320', 'home') else 'Offline' }}"

    #############
    # Raspberry #
    #############
      raspberry_pi_2:
        friendly_name: 'Raspberry Pi 2 (1-Wire)'
        value_template: "{{ 'Online' if is_state('device_tracker.raspberry_pi_2', 'home') else 'Offline' }}"
      raspberry_pi_3b:
        friendly_name: 'Raspberry Pi 3B (hagaholm)'
        value_template: "{{ 'Online' if is_state('device_tracker.raspberry_pi_3b', 'home') else 'Offline' }}"
      hassbian:
        friendly_name: 'Raspberry Pi 3B (hassbian)'
        value_template: "{{ 'Online' if is_state('device_tracker.hassbian', 'home') else 'Offline' }}"
      hassio:
        friendly_name: 'Raspberry Pi 3B+ (hassio)'
        value_template: "{{ 'Online' if is_state('device_tracker.hassio', 'home') else 'Offline' }}"

    ##########
    # Mobile #
    ##########
      mobil_louise:
        friendly_name: 'Louise'
        value_template: "{{ 'Online' if is_state('device_tracker.mobil_louise', 'home') else 'Offline' }}"
      mobil_annelie:
        friendly_name: 'Annelie'
        value_template: "{{ 'Online' if is_state('device_tracker.mobil_annelie', 'home') else 'Offline' }}"
      mobil_annelie_jobb:
        friendly_name: 'Annelie jobb'
        value_template: "{{ 'Online' if is_state('device_tracker.mobil_annelie_jobb', 'home') else 'Offline' }}"
      mobil_micke:
        friendly_name: 'Micke'
        value_template: "{{ 'Online' if is_state('device_tracker.mobil_micke', 'home') else 'Offline' }}"
      mobil_andreas:
        friendly_name: 'Andreas'
        value_template: "{{ 'Online' if is_state('device_tracker.mobil_andreas', 'home') else 'Offline' }}"
      mobil_margareta:
        friendly_name: 'Margareta'
        value_template: "{{ 'Online' if is_state('device_tracker.mobil_margareta', 'home') else 'Offline' }}"
      mobil_herbert:
        friendly_name: 'Herbert'
        value_template: "{{ 'Online' if is_state('device_tracker.v', 'home') else 'Offline' }}"
      mobil_erik:
        friendly_name: 'Erik'
        value_template: "{{ 'Online' if is_state('device_tracker.v', 'home') else 'Offline' }}"

      ##########
      # Laptop #
      ##########
      mickes_laptop:
        friendly_name: 'Mickes dator'
        value_template: "{{ 'Online' if is_state('device_tracker.mickes_laptop', 'home') else 'Offline' }}"
      mickes_work_laptop:
        friendly_name: 'Mickes jobb dator'
        value_template: "{{ 'Online' if is_state('device_tracker.mickes_work_laptop', 'home') else 'Offline' }}"
      louise_dator:
        friendly_name: 'Louise dator'
        value_template: "{{ 'Online' if is_state('device_tracker.louise_dator', 'home') else 'Offline' }}"
      herberts_dator:
        friendly_name: 'Louise dator'
        value_template: "{{ 'Online' if is_state('device_tracker.herberts_dator', 'home') else 'Offline' }}"

##############
# Automation #
##############
automation:
    ################################
    ### Hassbian startad         ###
    ### T: homeassistant = start ###
    ### A: notify.pushbullet     ###
    ################################
  - alias: 'Hassbian startad'
    initial_state: 'on'
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: notify.pushbullet
        data:
          title: "Hassbian startad!"
          message: ""

    ###################################
    ### Hassbian stoppad            ###
    ### T: homeassistant = shutdown ###
    ### A: notify.pushbullet        ###
    ###################################
  - alias: 'Hassbian stoppad'
    initial_state: 'on'
    trigger:
      platform: homeassistant
      event: shutdown
    action:
      - service: notify.pushbullet
        data:
          title: "Hassbian stoppad!"
          message: ""

    ############################
    ### Hassbian uppdatering ###
    ### T: updater.updater   ###
    ### A: notify.pushbullet ###
    ############################
  - alias: Hassbian uppdatering
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: updater.updater
    action:
      - service: notify.pushbullet
        data: 
          title: 'Ny Home Assistant Release'
          message: "Home Assistant {{ states.updater.updater.state }}"

    ####################################
    ### Ny enhet hittad              ###
    ### T: device_tracker_new_device ###
    ### A: notify.pushbullet         ###
    ####################################
  - alias: Ny enhet hittad
    initial_state: 'on'
    trigger:
      platform: event
      event_type: device_tracker_new_device
    action:
      - service: notify.pushbullet
        data:
          title: "Ny enhet hittad"
          message: "Enhet: {{trigger.event.data.host_name}} ({{trigger.event.data.entity_id}})"
