sensor:
  - platform: thermal_comfort
    sensors:
      - thermal_confort_badrum:
        friendly_name: Badrum komfort
        temperature_sensor: sensor.badrum_temperature
        humidity_sensor: sensor.badrum_humidity
      - thermal_confort_hall:
        friendly_name: Hall komfort
        temperature_sensor: sensor.hall_temperature
        humidity_sensor: sensor.hall_humidity