automation:
  - alias: Fj채rrkonotroll tv채ttstuga on
    trigger:
      - platform: state
        entity_id: switch.fjarrkontroll_tvattstuga
        to: 'on'
    action:
      - service: script.evening_lights_on

  - alias: Fj채rrkonotroll tv채ttstuga off
    trigger:
      - platform: state
        entity_id: switch.fjarrkontroll_tvattstuga
        to: 'off'
    action:
      - service: script.evening_lights_off