##############
### switch ###
##############
switch:
  - platform: command_line
    switches:
      fan_speed:
        command_on: python3 -c "import requests; requests.get('http://192.168.1.12:3001/uncached/12.A84D7D000000/?PIO.A=on&PIO.A=CHANGE');"
        command_off: python3 -c "import requests; requests.get('http://192.168.1.12:3001/uncached/12.A84D7D000000/?PIO.A=CHANGE');"
        friendly_name: Fläkthastighet Normal / Forcerad

# Hämta aktuell status: 'http://192.168.1.12:3001/text/12.A84D7D000000/PIO.A' 
# Sätt till Off: 'http://192.168.1.12:3001/uncached/12.A84D7D000000/?PIO.A=CHANGE'
# Sätt till On: 'http://192.168.1.12:3001/uncached/12.A84D7D000000/?PIO.A=on&PIO.A=CHANGE'

##################
### autoamtion ###
##################
automation:
    #############
    ### Larm ####
    #############
    ####################################################
    ### Larm! Hög fukt i badrummet, ingen hemma      ###
    ### T: sensor.fukt_badrumsfonster > 69           ###
    ### C: group.track_for_home_devices = 'not_home' ###
    ### A: switch.fan_speed = on                     ###
    ####################################################
  - alias: Badrumsfönster hög fukt larm
    trigger:
      platform: numeric_state
      entity_id: sensor.fukt_badrumsfonster
      above: '69'
    condition:
      condition: state
      entity_id: group.track_for_home_devices
      state: 'not_home'
    action:
      - service: notify.pushbullet
        data:
          message: 'Larm! Hög fukt i badrummet, ingen är hemma'

    #####################################
    ### Låg temp ventilation frånluft ###
    ### T: sensor.Franluft < 18       ###
    ### A: notify.pushbullet          ###
    #####################################
  - alias: Låg temp frånluft
    trigger:
      platform: numeric_state
      entity_id: sensor.Franluft
      below: '18'
    action:
      - service: notify.pushbullet
        data:
          message: 'Larm! Låg temp frånluft ventilation: {{ states.sensor.Franluft.state }} {{ states.sensor.Franluft.unit_of_measurement }}'

    #####################################
    ### Hög temp ventilation frånluft ###
    ### T: sensor.Franluft > 35       ###
    ### A: notify.pushbullet          ###
    #####################################
  - alias: Hög temp frånluft
    trigger:
      platform: numeric_state
      entity_id: sensor.Franluft
      above: '35'
    action:
      - service: notify.pushbullet
        data:
          message: 'Larm! Hög temp frånluft ventilation: {{ states.sensor.Franluft.state }} {{ states.sensor.Franluft.unit_of_measurement }}'

    ####################################
    ### Låg temp ventilation tilluft ###
    ### T: sensor.Tilluft < 15       ###
    ### A: notify.pushbullet         ###
    ####################################
  - alias: Låg temp tilluft
    trigger:
      platform: numeric_state
      entity_id: sensor.Tilluft
      below: '15'
    action:
      - service: notify.pushbullet
        data:
          message: 'Larm! Låg temp tilluft ventilation: {{ states.sensor.Tilluft.state }} {{ states.sensor.Tilluft.unit_of_measurement }}'

    ####################################
    ### Hög temp ventilation tilluft ###
    ### T: sensor.Tilluft > 35       ###
    ### A: notify.pushbullet         ###
    ####################################
  - alias: Hög temp tilluft
    trigger:
      platform: numeric_state
      entity_id: sensor.Tilluft
      above: '35'
    action:
      - service: notify.pushbullet
        data:
          message: 'Larm! Hög temp tilluft ventilation: {{ states.sensor.Tilluft.state }} {{ states.sensor.Tilluft.unit_of_measurement }}'

    ################
    ### Hög fukt ###
    ################
    ##########################################
    ### Hög fukt badrumsfönster            ###
    ### T: sensor.fukt_badrumsfonster > 69 ###
    ### A: switch.fan_speed = on           ###
    ##########################################
  - alias: Badrumsfönster hög fukt
    trigger:
      platform: numeric_state
      entity_id: sensor.fukt_badrumsfonster
      above: '69'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.fan_speed

    ################
    ### Låg fukt ###
    ################
    ##########################################
    ### Låg fukt badrumsfönster            ###
    ### T: sensor.fukt_badrumsfonster < 68 ###
    ### A: switch.fan_speed = off          ###
    ##########################################
  - alias: Badrumsfönster låg fukt
    trigger:
      platform: numeric_state
      entity_id: sensor.fukt_badrumsfonster
      below: '68'
    action:
      - service: homeassistant.turn_off
        entity_id: switch.fan_speed

    #######################
    ### Ventilation off ###
    #######################
    #####################################################
    ### Ventilation off                               ###
    ### T: group.track_for_home_devices == 'not_home' ###
    ### C: switch.ventilationsaggregat == on          ###
    ### C: sensor.ute > 24                            ###
    ### C: sensor.fukt_badrumsfonster < 60            ###
    ### C: sensor.inne_medel > 23                     ###
    ### A: switch.ventilationsaggregat = off          ###
    #####################################################
  - alias: Ventilation off (Borta, ute >24°C, <60%, Inne > 23°C)
    trigger:
      platform: state
      entity_id: group.track_for_home_devices
      from: 'home'
      to: 'not_home'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: switch.ventilationsaggregat
          state: 'on'
        - condition: numeric_state
          entity_id: sensor.ute
          above: '24'
        - condition: numeric_state
          entity_id: sensor.fukt_badrumsfonster
          below: '60'
        - condition: numeric_state
          entity_id: sensor.inne_medel
          above: '23'
    action:
      - service: homeassistant.turn_off
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_off
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_off
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_off
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_off
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_off
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_off
        entity_id: switch.ventilationsaggregat
      - service: notify.pushbullet
        data:
          message: 'Ventilation off (Borta, ute >24°C, <60%, Inne > 23°C)'

    #####################################################
    ### Ventilation off                               ###
    ### T: sensor.ute > 24                            ###
    ### C: switch.ventilationsaggregat == on          ###
    ### C: group.track_for_home_devices == 'not_home' ###
    ### C: sensor.fukt_badrumsfonster < 60            ###
    ### C: sensor.inne_medel > 23                     ###
    ### A: switch.ventilationsaggregat = off          ###
    #####################################################
  - alias: Ventilation off (Ute >24°C, Borta, <60%, Inne > 23°C)
    trigger:
      platform: numeric_state
      entity_id: sensor.ute
      above: '24'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: switch.ventilationsaggregat
          state: 'on'
        - condition: state
          entity_id: group.track_for_home_devices
          state: 'not_home'
        - condition: numeric_state
          entity_id: sensor.fukt_badrumsfonster
          below: '60'
        - condition: numeric_state
          entity_id: sensor.inne_medel
          above: '23'
    action:
      - service: homeassistant.turn_off
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_off
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_off
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_off
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_off
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_off
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_off
        entity_id: switch.ventilationsaggregat
      - service: notify.pushbullet
        data:
          message: Ventilation off (Ute >24°C, Borta, <60%, Inne > 23°C)

    #####################################################
    ### Ventilation off                               ###
    ### T: sensor.fukt_badrumsfonster < 60            ###
    ### C: switch.ventilationsaggregat == on          ###
    ### C: group.track_for_home_devices == 'not_home' ###
    ### C: sensor.ute > 24                            ###
    ### C: sensor.inne_medel > 23                     ###
    ### A: switch.ventilationsaggregat = off          ###
    #####################################################
  - alias: Ventilation off (<60%, Borta, Ute >24°C, Inne > 23°C)
    trigger:
      platform: numeric_state
      entity_id: sensor.fukt_badrumsfonster
      below: '60'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: switch.ventilationsaggregat
          state: 'on'
        - condition: state
          entity_id: group.track_for_home_devices
          state: 'not_home'
        - condition: numeric_state
          entity_id: sensor.ute
          above: '24'
        - condition: numeric_state
          entity_id: sensor.inne_medel
          above: '23'
    action:
      - service: homeassistant.turn_off
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_off
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_off
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_off
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_off
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_off
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_off
        entity_id: switch.ventilationsaggregat
      - service: notify.pushbullet
        data:
          message: 'Ventilation off (<60%, Borta, Ute >24°C, Inne > 23°C)'

    #####################################################
    ### Ventilation off                               ###
    ### T: sensor.inne_medel > 23                     ###
    ### C: switch.ventilationsaggregat == on          ###
    ### C: group.track_for_home_devices == 'not_home' ###
    ### C: sensor.fukt_badrumsfonster < 60            ###
    ### C: sensor.ute > 24                            ###
    ### A: switch.ventilationsaggregat = off          ###
    #####################################################
  - alias: Ventilation off (Inne >23°C, Borta, <60%, Ute > 24°C)
    trigger:
      platform: numeric_state
      entity_id: sensor.inne_medel
      above: '23'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: switch.ventilationsaggregat
          state: 'on'
        - condition: state
          entity_id: group.track_for_home_devices
          state: 'not_home'
        - condition: numeric_state
          entity_id: sensor.fukt_badrumsfonster
          below: '60'
        - condition: numeric_state
          entity_id: sensor.ute
          above: '24'
    action:
      - service: homeassistant.turn_off
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_off
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_off
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_off
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_off
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_off
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_off
        entity_id: switch.ventilationsaggregat
      - service: notify.pushbullet
        data:
          message: Ventilation off (Inne >23°C, Borta, <60%, Ute > 24°C)

    ######################
    ### Ventilation on ###
    ######################
    #################################################
    ### Ventilation on                            ###
    ### T: group.track_for_home_devices == 'home' ###
    ### C: switch.ventilationsaggregat == off     ###
    ### A: switch.ventilationsaggregat = on       ###
    #################################################
  - alias: Ventilation on (Hemma, Off)
    trigger:
      platform: state
      entity_id: group.track_for_home_devices
      from: 'not_home'
      to: 'home'
    condition:
      condition: state
      entity_id: switch.ventilationsaggregat
      state: 'off'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_on
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_on
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_on
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_on
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_on
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_on
        entity_id: switch.ventilationsaggregat
      - service: notify.pushbullet
        data:
          message: 'Ventilation on (Hemma, Off)'

    #############################################
    ### Ventilation on                        ###
    ### T: sensor.ute < 22                    ###
    ### C: switch.ventilationsaggregat == off ###
    ### A: switch.ventilationsaggregat = on   ###
    #############################################
  - alias: Ventilation on (Ute <22°C, Off)
    trigger:
      platform: numeric_state
      entity_id: sensor.ute
      below: '23'
    condition:
      condition: state
      entity_id: switch.ventilationsaggregat
      state: 'off'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_on
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_on
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_on
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_on
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_on
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_on
        entity_id: switch.ventilationsaggregat
      - service: notify.pushbullet
        data:
          message: 'Ventilation on (Ute <22°C, Off)'

    #############################################
    ### Ventilation on                        ###
    ### T: sensor.fukt_badrumsfonster > 60    ###
    ### C: switch.ventilationsaggregat == off ###
    ### A: switch.ventilationsaggregat = on   ###
    #############################################
  - alias: Ventilation on (>60%, Off)
    trigger:
      platform: numeric_state
      entity_id: sensor.fukt_badrumsfonster
      above: '60'
    condition:
      condition: state
      entity_id: switch.ventilationsaggregat
      state: 'off'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_on
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_on
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_on
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_on
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_on
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_on
        entity_id: switch.ventilationsaggregat
      - service: notify.pushbullet
        data:
          message: 'Ventilation on (>60%, Off)'

    #############################################
    ### Ventilation on                        ###
    ### T: sensor.inne_medel < 23             ###
    ### C: switch.ventilationsaggregat == off ###
    ### A: switch.ventilationsaggregat = on   ###
    #############################################
  - alias: Ventilation on (Inne <23°C, Off)
    trigger:
      platform: numeric_state
      entity_id: sensor.inne_medel
      below: '23'
    condition:
      condition: state
      entity_id: switch.ventilationsaggregat
      state: 'off'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_on
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_on
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_on
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_on
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_on
        entity_id: switch.ventilationsaggregat
      - delay: '00:00:05'
      - service: homeassistant.turn_on
        entity_id: switch.ventilationsaggregat
#      - service: notify.pushbullet
##        data:
#          message: 'Ventilation on (Inne <23°C, Off)'
