#####################
### Input boolean ###
#####################
input_boolean:
  working_at_home:
    name: Jobbar hemifrån


automation:
  ################################
  ### Tänd skrivbordsbelysning ###
  ################################
  - alias: Tänd skrivbordsbelysning
    mode: single

    trigger:
      - platform: state
        entity_id: sensor.mickes_work_laptop
        to: 'Online'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.working_at_home
          state: 'on'
        - condition: state
          entity_id: binary_sensor.workday_today
          state: 'on'

    action:
      - service: light.turn_on
        entity_id: light.louise_skrivbord

  #################################
  ### Släck skrivbordsbelysning ###
  #################################
  - alias: Släck skrivbordsbelysning
    mode: single

    trigger:
      - platform: state
        entity_id: sensor.mickes_work_laptop
        to: 'Offline'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.working_at_home
          state: 'on'
        - condition: state
          entity_id: binary_sensor.workday_today
          state: 'on'

    action:
      - service: light.turn_off
        entity_id: light.louise_skrivbord

  #########################################
  ### Blinka med lyset Louise skrivbord ###
  #########################################
  - alias: Blinka med lyset Louise skrivbord
    mode: single

    trigger:
      - platform: state
        entity_id: input_boolean.camera_light_control
        to: 'on'
      - platform: state
        entity_id: switch.ringklocka_tvattstuga
        to: 'on'
      - platform: state
        entity_id: switch.ringklocka_hall
        to: 'on'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.working_at_home
          state: 'on'
        - condition: state
          entity_id: binary_sensor.workday_today
          state: 'on'
        - condition: time
          after: '07:00:00'
          before: '17:00:00'
    action:
      - service: script.flash_light_louise_skrivbord


script:
  flash_light_louise_skrivbord:
    alias: Blinka lampa Louise skrivbord
    sequence:
      - service: light.toggle
        entity_id: light.louise_skrivbord

      - delay:
          seconds: 2

      - service: light.toggle
        entity_id: light.louise_skrivbord

      - delay:
          seconds: 2

      - service: light.toggle
        entity_id: light.louise_skrivbord

      - delay:
          seconds: 2

      - service: light.toggle
        entity_id: light.louise_skrivbord
