vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.144
    token: !secret vacuum_token

sensor:
  # Template sensors for Xiaomi Vacuum
  - platform: template
    sensors:
      vacuum_status:
        friendly_name: Status
        entity_id:
          - vacuum.xiaomi_vacuum_cleaner
        value_template: 'Status: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.status }}'
        icon_template: >
          {% set val =  states.vacuum.xiaomi_vacuum_cleaner.attributes.status  %}
          {% if val == 'Charging' %}
            mdi:battery-charging
          {% elif val == 'Cleaning' %}
            mdi:move-resize
          {% elif val == 'Returning home' %}
            mdi:keyboard-return
          {% elif val == 'Idle' %}
            mdi:dots-horizontal
          {% elif val == 'Paused' %}
            mdi:pause-circle
          {% else %}
            mdi:help-circle
          {% endif %}
      vacuum_fan_speed:
        friendly_name: Fan Speed
        entity_id:
          - vacuum.xiaomi_vacuum_cleaner
        value_template: 'Mode: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.fan_speed }}'
        icon_template: 'mdi:speedometer'
      vacuum_battery:
        friendly_name: Vacuum Battery
        entity_id:
          - vacuum.xiaomi_vacuum_cleaner
        value_template: 'Battery: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.battery_level }}'
        unit_of_measurement: '%'
        icon_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.battery_icon }}'
      vacuum_cleaning_time:
        friendly_name: Time of Last Cycle
        entity_id:
          - vacuum.xiaomi_vacuum_cleaner
        value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.cleaning_time }}'
        icon_template: 'mdi:timer'
      vacuum_cleaned_area:
        friendly_name: Area of Last Cycle
        unit_of_measurement: 'm ²'
        entity_id:
          - vacuum.xiaomi_vacuum_cleaner
        value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.cleaned_area }}'
        icon_template: 'mdi:ruler'
      vacuum_cleanmainbrush:
        friendly_name: Replace main brush
        unit_of_measurement: 'h'
        entity_id:
          - vacuum.xiaomi_vacuum_cleaner
        value_template: 'Main Brush: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.main_brush_left }}'
        icon_template: 'mdi:screwdriver'
      vacuum_cleansidebrush:
        friendly_name: Replace side brush
        unit_of_measurement: 'h'
        entity_id:
          - vacuum.xiaomi_vacuum_cleaner
        value_template: 'Side brush: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.side_brush_left }}'
        icon_template: 'mdi:screwdriver'
      vacuum_cleanfilter:
        friendly_name: Replace filter
        unit_of_measurement: 'h'
        entity_id:
          - vacuum.xiaomi_vacuum_cleaner
        value_template: 'Filter: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.filter_left }}'
        icon_template: 'mdi:screwdriver'
      vacuum_sensordirtyleft:
        friendly_name: Clean sensor
        unit_of_measurement: 'h'
        entity_id:
          - vacuum.xiaomi_vacuum_cleaner
        value_template: 'Sensor:  {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.sensor_dirty_left }}'
        icon_template: 'mdi:screwdriver'
      vacuum_do_not_disturb:
        friendly_name: Do Not Disturb
        entity_id:
          - vacuum.xiaomi_vacuum_cleaner
        value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.do_not_disturb }}'
        icon_template: >
          {% set val =  states.vacuum.xiaomi_vacuum_cleaner.attributes.do_not_disturb  %}
          {% if val == 'on' %}
            mdi:do-not-disturb
          {% else %}
            mdi:do-not-disturb-off
          {% endif %}
      vacuum_operation:
        value_template: 'Operation'
      vacuum_accessories:
        value_template: 'Maintenance'

script:
  vacuum_house:
    alias: "Huset"
    sequence:
      - service: vacuum.start
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner

  vacuum_daily:
    alias: "Dagligen"
    sequence:
      - service: vacuum.start
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:01:00'
      - service: vacuum.stop
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:00:02'
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          #         Start yta louise rum        Hall del 1                  Hall del 2                  Hall del 3                  Köket                       Mattan tvättstugan          Startyta Louise rum
          params: [[25006,28117,25706,28617,1],[27008,26977,28058,32227,1],[23778,32252,28028,34052,1],[26128,34092,27978,35792,1],[23786,36098,27836,40998,1],[27903,39379,29453,41029,2],[25006,28117,25706,28617,1]]

  vacuum_kitchen:
    alias: "Köket"
    sequence:
      - service: vacuum.start
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:01:00'
      - service: vacuum.stop
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:00:02'
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          params: [[23786,36098,27836,40998,1]]

  vacuum_kitchen_carpet:
    alias: "Köksmattan"
    sequence:
      - service: vacuum.start
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:01:00'
      - service: vacuum.stop
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:00:02'
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          params: [[24215,38583,27815,40283,1]]

  vacuum_laundry:
    alias: "Tvättstugan"
    sequence:
      - service: vacuum.start
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:01:00'
      - service: vacuum.stop
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:00:02'
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          params: [[27853,38491,31753,40991,1]]

  vacuum_laundry_carpet:
    alias: "Mattan i tvättstugan"
    sequence:
      - service: vacuum.start
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:01:00'
      - service: vacuum.stop
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:00:02'
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          params: [[27903,39379,29453,41029,2]]

  vacuum_hall:
    alias: "Hallen"
    sequence:
      - service: vacuum.start
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:01:00'
      - service: vacuum.stop
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:00:02'
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          params: [[27008,26977,28058,32227,1],[23778,32252,28028,34052,1],[26128,34092,27978,35792,1]]

  vacuum_sovrum:
    alias: "Sovrummet"
    sequence:
      - service: vacuum.start
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:01:00'
      - service: vacuum.stop
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:00:02'
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          params: [[28167,25130,32167,29130,1]]

#  vacuum_uterum:
#    alias: "Uterum"
#    sequence:
#      - service: vacuum.send_command
#        data:
#          entity_id: vacuum.xiaomi_vacuum_cleaner
#          command: app_zoned_clean
#          params: [[31423,33524,31923,34024,1]]
#      - delay: '00:01:10'
#      - service: vacuum.stop

  vacuum_louise_rum:
    alias: "Louise rum"
    sequence:
      - service: vacuum.start
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:01:00'
      - service: vacuum.stop
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:00:02'
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          params: [[24011,25173,26861,29373,1]]

  vacuum_andreas_rum:
    alias: "Andreas rum"
    sequence:
      - service: vacuum.start
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:01:00'
      - service: vacuum.stop
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:00:02'
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          params: [[28030,29476,31930,31976,1]]

  vacuum_vardagsrum:
    alias: "Vardagsrum"
    sequence:
      - service: vacuum.start
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:01:00'
      - service: vacuum.stop
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:00:02'
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          params: [[27928,32039,31928,38639,1]]

  vacuum_toalett:
    alias: "Toalett"
    sequence:
      - service: vacuum.start
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:01:00'
      - service: vacuum.stop
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:00:02'
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          params: [[23816,34397,25366,36047,1]]

automation:
  - alias: Dagligen måndag
    trigger:
      - platform: time
        at: '10:00:00'
    condition:
      - condition: time
        weekday:
          - mon
#          - tue
#          - wed
#          - thu
#          - fri
    action:
      - service: script.vacuum_daily

  - alias: Dagligen onsdag
    trigger:
      - platform: time
        at: '10:00:00'
    condition:
      - condition: time
        weekday:
          - wed
    action:
      - service: script.vacuum_daily

  - alias: Dagligen fredag
    trigger:
      - platform: time
        at: '10:00:00'
    condition:
      - condition: time
        weekday:
          - fri
    action:
      - service: script.vacuum_daily        

