################################################################################
# Not needed as it has been moved to an integration
#vacuum:
#  - platform: xiaomi_miio
#    host: 192.168.1.25
#    token: !secret vacuum_token

################################################################################
sensor:
  # Template sensors for Xiaomi Vacuum
  - platform: template
    sensors:
      vacuum_status:
        friendly_name: Status
        value_template: "Status: {{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'status') }}"
        icon_template: >
          {% set val =  state_attr('vacuum.xiaomi_vacuum_cleaner', 'status')  %}
          {% if val == 'Charging' %}
            mdi:battery-charging
          {% elif val == 'Cleaning' %}
            mdi:move-resize
          {% elif val == 'Returning home' %}
            mdi:keyboard-return
          {% elif val == 'Idle' %}
            mdi:dots-horizontal
          {% elif val == 'Paused' %}
            mdi:pause-circle
          {% else %}
            mdi:help-circle
          {% endif %}
      vacuum_fan_speed:
        friendly_name: Fan Speed
        value_template: "Mode: {{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'fan_speed') }}"
        icon_template: 'mdi:speedometer'
      vacuum_battery:
        friendly_name: Vacuum Battery
        value_template: "Battery: {{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'battery_level') }}"
        unit_of_measurement: '%'
        icon_template: "{{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'battery_icon') }}"
      vacuum_cleaning_time:
        friendly_name: Time of Last Cycle
        value_template: "{{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'cleaning_time') }}"
        icon_template: 'mdi:timer-outline'
      vacuum_cleaned_area:
        friendly_name: Area of Last Cycle
        unit_of_measurement: 'm²'
        value_template: "{{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'cleaned_area') }}"
        icon_template: 'mdi:ruler'
      vacuum_cleanmainbrush:
        friendly_name: Replace main brush
        unit_of_measurement: 'h'
        value_template: "Main Brush: {{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'main_brush_left') }}"
        icon_template: 'mdi:screwdriver'
      vacuum_cleansidebrush:
        friendly_name: Replace side brush
        unit_of_measurement: 'h'
        value_template: "Side brush: {{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'side_brush_left') }}"
        icon_template: 'mdi:screwdriver'
      vacuum_cleanfilter:
        friendly_name: Replace filter
        unit_of_measurement: 'h'
        value_template: "Filter: {{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'filter_left')}}"
        icon_template: 'mdi:screwdriver'
      vacuum_cleanstop:
        friendly_name: Clean stop
        unit_of_measurement: 'date'
        value_template: "Filter: {{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'clean_stop') }}"
        icon_template: 'mdi:stop'
      vacuum_sensordirtyleft:
        friendly_name: Clean sensor
        unit_of_measurement: 'h'
        value_template: "Sensor:  {{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'sensor_dirty_left') }}"
        icon_template: 'mdi:screwdriver'
      vacuum_do_not_disturb:
        friendly_name: Do Not Disturb
        value_template: "{{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'do_not_disturb') }}"
        icon_template: >
          {% set val =  state_attr('vacuum.xiaomi_vacuum_cleaner', 'do_not_disturb')  %}
          {% if val == 'on' %}
            mdi:do-not-disturb
          {% else %}
            mdi:do-not-disturb-off
          {% endif %}
      vacuum_operation:
        value_template: 'Operation'
      vacuum_accessories:
        value_template: 'Maintenance'

################################################################################
script:
  vacuum_house:
    alias: "Dammsug huset"
    sequence:
      - service: vacuum.start
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner

  vacuum_daily:
    alias: "Dammsug dagligen"
    sequence:
      - service: vacuum.start
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:01:00'
      - service: vacuum.stop
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:00:02'
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          #         Start yta louise rum        Hall del 1                  Hall del 2                  Hall del 3                  Köket                       Mattan tvättstugan          Startyta Louise rum
          params: [[25006,28117,25706,28617,1],[27008,26977,28058,32227,1],[23778,32252,28028,34052,1],[26128,34092,27978,35792,1],[23786,36098,27836,40998,1],[27903,39379,29453,41029,2],[25006,28117,25706,28617,1]]

  vacuum_kitchen:
    alias: "Dammsug köket"
    sequence:
      - service: vacuum.start
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:01:00'
      - service: vacuum.stop
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:00:02'
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          params: [[23786,36098,27836,40998,1]]

  vacuum_kitchen_carpet:
    alias: "Dammsug köksmattan"
    sequence:
      - service: vacuum.start
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:01:00'
      - service: vacuum.stop
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:00:02'
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          params: [[24215,38583,27815,40283,1]]

  vacuum_laundry:
    alias: "Dammsug tvättstugan"
    sequence:
      - service: vacuum.start
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:01:00'
      - service: vacuum.stop
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:00:02'
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          params: [[27853,38491,31753,40991,1]]

  vacuum_laundry_carpet:
    alias: "Dammsug mattan i tvättstugan"
    sequence:
      - service: vacuum.start
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:01:00'
      - service: vacuum.stop
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:00:02'
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          params: [[27903,39379,29453,41029,2]]

  vacuum_hall:
    alias: "Dammsug hallen"
    sequence:
      - service: vacuum.start
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:01:00'
      - service: vacuum.stop
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:00:02'
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          params: [[27008,26977,28058,32227,1],[23778,32252,28028,34052,1],[26128,34092,27978,35792,1]]

  vacuum_sovrum:
    alias: "Dammsug sovrummet"
    sequence:
      - service: vacuum.start
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:01:00'
      - service: vacuum.stop
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:00:02'
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          params: [[28167,25130,32167,29130,1]]

#  vacuum_uterum:
#    alias: "Dammsug uterum"
#    sequence:
#      - service: vacuum.send_command
#        data:
#          entity_id: vacuum.xiaomi_vacuum_cleaner
#          command: app_zoned_clean
#          params: [[31423,33524,31923,34024,1]]
#      - delay: '00:01:10'
#      - service: vacuum.stop

  vacuum_louise_rum:
    alias: "Dammsug Louise rum"
    sequence:
      - service: vacuum.start
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:01:00'
      - service: vacuum.stop
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:00:02'
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          params: [[24011,25173,26861,29373,1]]

  vacuum_andreas_rum:
    alias: "Dammsug Andreas rum"
    sequence:
      - service: vacuum.start
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:01:00'
      - service: vacuum.stop
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:00:02'
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          params: [[28030,29476,31930,31976,1]]

  vacuum_vardagsrum:
    alias: "Dammsug vardagsrum"
    sequence:
      - service: vacuum.start
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:01:00'
      - service: vacuum.stop
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:00:02'
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          params: [[27928,32039,31928,38639,1]]

  vacuum_toalett:
    alias: "Dammsug toalett"
    sequence:
      - service: vacuum.start
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:01:00'
      - service: vacuum.stop
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:00:02'
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          params: [[23816,34397,25366,36047,1]]

################################################################################
automation:
  - alias: Dagligen måndag
    trigger:
      - platform: time
        at: '10:00:00'
    condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - mon
#            - tue
#            - wed
#            - thu
#            - fri
        - condition: state
          entity_id: group.track_for_home_devices
          state: 'not_home'        
    action:
      - service: script.vacuum_daily

  - alias: Dagligen onsdag
    trigger:
      - platform: time
        at: '10:00:00'
    condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - wed
        - condition: state
          entity_id: group.track_for_home_devices
          state: 'not_home'        
    action:
      - service: script.vacuum_daily

  - alias: Dagligen fredag
    trigger:
      - platform: time
        at: '10:00:00'
    condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - fri
        - condition: state
          entity_id: group.track_for_home_devices
          state: 'not_home'        
    action:
      - service: script.vacuum_daily        

  - alias: "Dammsugaren har problem"
    trigger:
      - platform: state
        entity_id: vacuum.xiaomi_vacuum_cleaner
        to: "error"
    action:
      - service: notify.pushbullet
        data:
          title: "Dammsugaren har problem"
          message: "Sitter fast eller vill bara ha lite uppmärksamhet"